### ISSUE TITLE
Use of single quotes causes unexpected behaviour in bigip_command

### ISSUE THREAD

**Issue by alex-harvey-z3q** [F5Networks/terraform-provider-bigip#1018]
### Environment

 * TMOS/Bigip Version: n/a
 * Terraform Version: 1.9.3
 * Terraform bigip provider Version: master branch

### Summary

Use of single quotes in the bigip_command resource cause unexpected behaviour. For example:

```hcl
resource "bigip_command" "hello-world" {
  commands = ["bash -c 'echo hello world'"]
}

output "tmsh-test-result" {
  description = "Test"
  value       = bigip_command.hello-world.command_result
}
```

### Steps To Reproduce

```hcl
resource "bigip_command" "hello-world" {
  commands = ["bash -c 'echo hello world'"]
}

output "tmsh-test-result" {
  description = "Test"
  value       = bigip_command.hello-world.command_result
}
```

### Expected Behavior
The result should contain `hello world`.

### Actual Behavior
The result is an empty string.

**Comment by alex-harvey-z3q** [comment]
The root cause appears to be unsafe quoting here
https://github.com/F5Networks/terraform-provider-bigip/blob/d1eabd08c61fc53d497f9e39cce82899b026fe88/bigip/resource_bigip_command.go#L64

The possibility that the string itself contains a single quote does not appear to be handled leading to our issue.

**Comment by alex-harvey-z3q** [comment]
I assume that if the input contained only 1 single quote you'd end up with a syntax error but I haven't tested.

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1675.
