### ISSUE TITLE
Failing to create external bigip_ltm_datagroup resource

### ISSUE THREAD

**Issue by LuisPiedra** [F5Networks/terraform-provider-bigip#1024]
### Environment

 * TMOS/Bigip Version: 15.1.2
 * Terraform Version: 1.9.7
 * Terraform bigip provider Version: 1.22.4

### Summary

After creating a `bigip_ltm_datagroup` resource with `internal = false`, the data group and corresponding data group file are created, but then the provider fails to retrieve it when querying data groups lists.

This is happening after https://github.com/F5Networks/terraform-provider-bigip/pull/821/files and working properly in versions prior to that change.

### Steps To Reproduce

```
resource "local_file" "external" {
  content  = "foo := bar"
  filename = "foo.bar"
}

resource "bigip_ltm_datagroup" "external" {
  name     = "/Common/external-test"
  type     = "string"
  internal = false

  records_src = local_file.external.filename
}
```

### Expected Behavior
The data group and data group file are created and properly included in the state file.

### Actual Behavior
The data group and data group file are created, but not refreshed.

```
Error: Error retrieving Data Group List /Common/external-test: Object not found - /Common/external-test 
```

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1687.

**Comment by prateekramani** [comment]
Hi @LuisPiedra,

This issue is fixed, and it will be working in the upcoming release.

Thanks.
