### ISSUE TITLE
bigip_ltm_pool_attachment import block does not populate most properties

### ISSUE THREAD

**Issue by jtgasper3** [F5Networks/terraform-provider-bigip#1031]
### Environment

 * TMOS/Bigip Version: unknown
 * Terraform Version: 1.9.8
 * Terraform bigip provider Version: 1.22.5

### Summary

The bigip_ltm_pool_attachment import block does not populate most properties.

### Steps To Reproduce

1. Provide terraform resource config which you are facing trouble along with the output of it.
```
import {
  to = bigip_ltm_pool_attachment.pool_1
  id = "{\"pool\": \"/Common/terraform_pool\", \"node\": \"/Common/terraform_node:8443\"}"
}
```

2. To get to know more about the issue, provide terraform debug logs

3. To capture debug logs, export TF_LOG variable with debug ( export TF_LOG= DEBUG ) before 
  runnning terraform apply/plan

4. As3/DO json along with the resource config( for AS3/DO resource issues )

### Expected Behavior

Monitor, ratio, priority_group should be set; perhaps more properties should also be set, but these are ones that I know are an issue for us:

```
resource "bigip_ltm_pool_attachment" "pool_1" {
  connection_limit      = null
  connection_rate_limit = null
  dynamic_ratio         = null
  fqdn_autopopulate     = null
  monitor               = "/Common/https_head_8443"
  node                  = "/Common/terraform_node:8443"
  pool                  = "/Common/terraform_pool"
  priority_group        = "2"
  ratio                 = "1"
  state                 = null
}
```

### Actual Behavior

```
resource "bigip_ltm_pool_attachment" "pool_1" {
  connection_limit      = null
  connection_rate_limit = null
  dynamic_ratio         = null
  fqdn_autopopulate     = null
  monitor               = null
  node                  = "/Common/terraform_node:8443"
  pool                  = "/Common/terraform_pool"
  priority_group        = null
  ratio                 = null
  state                 = null
}
```

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1699.
