### ISSUE TITLE
VCMP Support?

### ISSUE THREAD

**Issue by stobias123** [F5Networks/terraform-provider-bigip#157]
Is there any intention to support VCMP? 
is that already possible here - https://www.terraform.io/docs/providers/bigip/r/bigip_sys_provision.html

**Comment by scshitole** [comment]
@stobias123 you mean to create VCMP on the F5 Chassis ? The virtual BIG-IP in VCMP should work as it is as the APIs are same.

**Comment by stobias123** [comment]
I want to do this - https://docs.ansible.com/ansible/2.5/modules/bigip_vcmp_guest_module.html

**Comment by papineni87** [comment]
Currently we don't have terraform resources to create cores per slot, creating /deleting virtual disk ...... etc for VCMP , but we will take it up as enhancement  and provide it in coming releases.

**Comment by stobias123** [comment]
Yeah - would be really cool, I have a client that wants to do this badly.

**Comment by RavinderReddyF5** [comment]
Fixed in v1.16.1
