### ISSUE TITLE
Feature Request: Add Pool Priority Group Activation

### ISSUE THREAD

**Issue by skorfmann** [F5Networks/terraform-provider-bigip#16]
We'd like to configure the "Priority Group Activation" on the pool, plus the actual "Priority Group" on the pool members via Terraform.

Is this on the roadmap already, or would you accept PRs?

**Comment by scshitole** [comment]
@skorfmann thanks  we do accept PR as well

**Comment by howsTricks** [comment]
Wanted to check in on this, we use priority groups quite a bit in our setup. Would like to be able to define them in Terraform instead of manually configuring later. Thanks!

**Comment by papineni87** [comment]
we have this enhancement in our product backlog items, and will fixed up in coming releases

**Comment by ddcrjlalumiere** [comment]
I was also just today in need of this functionality...

**Comment by papineni87** [comment]
@nmenant

**Comment by howsTricks** [comment]
Definitely still interested in this too, still having to track this manually via documentation and GUI configuration. Looking forward to when we can backfill with Terraform.

**Comment by nmenant** [comment]
Sorry for not answering earlier. We are going to look into it. Tracking internally with TER-480

**Comment by howsTricks** [comment]
Hi @nmenant Really appreciate it, looking forward to getting this into our tf code and out of our manual configuration step.

**Comment by papineni87** [comment]
@howsTricks  Added the enhancement in 1.4 release

**Comment by howsTricks** [comment]
Awesome! Thanks for this!
