### ISSUE TITLE
Authorization error when trying to create virtual server using Manager role

### ISSUE THREAD

**Issue by dhawal55** [F5Networks/terraform-provider-bigip#160]
I'm using a BigIP F5 user with `manager` role in a single partition to create a `bigip_ltm_virtual_server`, `bigip_ltm_pool` and `bigip_ltm_pool_attachment` resources in that partition. 

I get the following error:
```
Error: Error running plan: 1 error occurred:
	* provider.bigip: Authorization failed: user=https://localhost/mgmt/shared/authz/users/test resource=/mgmt/tm/net/self verb=GET uri:http://localhost:8100/mgmt/tm/net/self referrer:xy.xy.xy.xy sender:xx.xx.xx.xx
```

What am I missing?

**Comment by dhawal55** [comment]
I figured out the issue. I'm running F5 version v12.1.3.6 and as per documentation I need admin role to access API:

```In BIG-IP 11.5.x to 13.0.x, by default, only users with the Administrator role are granted access to the iControl REST API. In BIG-IP 13.1.x and later, any user you create regardless of role is automatically given access to the iControl REST API, but are limited by their role to what objects they can view and edit.```

I will try after upgrading to v14.1.x.

**Comment by dhawal55** [comment]
It failed in BigIP v14.1.x too. As per this issue, it looks like a BigIP bug: https://github.com/F5Networks/f5-ansible/issues/1175

One workaround suggested in the above post is to not set any metadata but I can't find any option to disable metadata in terraform provider

**Comment by KrithikaChidambaram** [comment]
Hi, closing this request now. 
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
