### ISSUE TITLE
Issue with irule resource preferred method - Loading from a file.

### ISSUE THREAD

**Issue by soumik612** [F5Networks/terraform-provider-bigip#161]
When I try to add a new irule using files, it works fine.
However while pushing changes for other resources, TF tries to re-apply the irule entries, although there's nothing changed in the file.
this does not seem efficient, since we have more than 20odd irules and the changes for these irules will pop up during every TF plan.
Is there a way, TF can check make a diff of the contents of the file with the state file and apply changes only if there is any ?

**Comment by dannyk81** [comment]
@soumik612 interesting, we load up irules from files as well, specifically we use something like below in the `bigip_ltm_irule` resource configuration:
```
irule = file("path/to/irule-file.tcl")
```

with above we never hit an issue that you are describing, as long as the `tcl` files are not modified we never have these false-positive diffs you describe.

Terraform does make a diff between the `irule` attribute content in the state and the content being loaded using the `file()` function and as long as they are the same a diff situation shouldn't be triggered.

can you share your configuration example? and steps to reproduce?

**Comment by KrithikaChidambaram** [comment]
Hi, closing this request now. 
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
