### ISSUE TITLE
Feature Request: Add support for Analytics profile

### ISSUE THREAD

**Issue by soumik612** [F5Networks/terraform-provider-bigip#225]
Can you please add resources for Analytics profile for TCP and HTTP ?

**Comment by trinaths** [comment]
Created [INFRAANO-699] for internal tracking.

**Comment by KrithikaChidambaram** [comment]
Hi, closing this request now. 
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
