### ISSUE TITLE
F5 LTM default custom profile values should calculated rather than hardcoded in code.

### ISSUE THREAD

**Issue by soumik612** [F5Networks/terraform-provider-bigip#298]
I have come across issues, wherein I have to profile values in the TF resource config code.
I suggestion is to get the provider to fetch the custom values from LTM. This will make it easier to maintain config sanity in case the default values change after a software upgrade.

**OBSERVED ISSUE**:

While testing the resource "bigip_ltm_profile_fastl4", my basic resource config looks like this ,
![image](https://user-images.githubusercontent.com/35273569/84040174-96eafc80-a9a2-11ea-9b83-9aace61d9a9b.png)
A TF apply pushes the config in LTM. However, on subsequent , although there are no changes to the config, the plan op shows,

![image](https://user-images.githubusercontent.com/35273569/84040339-cdc11280-a9a2-11ea-8c0f-76c009020921.png)

The workaround is to set default values in the resource code and TF provider does not show the changes during a TF plan, even though the attributes are OPTIONAL.

 
![image](https://user-images.githubusercontent.com/35273569/84041011-9b63e500-a9a3-11ea-8dc9-858fd29ddbdc.png)

**EXPECTED BEHAVIOR:**

TF provider should fetch default values form the LTM. Only values that need to be changed or customised should be required to be added in the resource code.

**Comment by focrensh** [comment]
Tracking via TER-401

**Comment by focrensh** [comment]
see https://github.com/terraform-providers/terraform-provider-bigip/issues/43#issuecomment-484498699 around using computed for TMOS default values.

**Comment by papineni87** [comment]
Issue is fixed in 1.3 release, closing the issue
