### ISSUE TITLE
bigip_ltm_policy resource seems broken

### ISSUE THREAD

**Issue by pkustner** [F5Networks/terraform-provider-bigip#30]
can also reference https://github.com/f5devcentral/terraform-provider-bigip/issues/112

Using a very slightly modified version of the example code for the provider I get the following error when I try to apply.
`bigip_ltm_policy.test-policy: 0107186c:3: Policy '/Common/Drafts/my_policy', rule 'rule6'; missing or invalid target.`

Here's the terraform Policy I'm trying with.
```resource "bigip_ltm_policy" "test-policy" {
name = "my_policy"
strategy = "first-match"
 requires = ["http"]
published_copy = "Drafts/my_policy"
 controls = ["forwarding"]
 rule  {
 name = "rule6"

  action = {
    tm_name = "20"
    redirect = true
     location = "https://www.auctionsniper.com/help/support/"
  }
 }
# depends_on = ["bigip_ltm_pool.mypool"]
}```

**Comment by techspecguy** [comment]
I can confirm this behavior.  Policies also do not show up in the state when importing a Virtual Server resource.  The virtual's policies always show #0 and each time applying, terraform thinks it needs to add the policies that are defined in the tf config.
The policies if defined actually get created when adding a virtual server, but state still shows none.

When trying to create a policy resource, it will always add the policy to drafts in the F5, but will not publish the policy.

**Comment by jlosito** [comment]
Any update on fixing this bug?
