### ISSUE TITLE
bigip_ltm_virtual_address advertize_route not getting set for the first time

### ISSUE THREAD

**Issue by Ankmat** [F5Networks/terraform-provider-bigip#308]
I am trying to create a virtual server and enable the route advertisement for the vip. Though Terraform plan says it will be updating the flag after it creates the virtual server, it doesnot happen. Subsequent running of plan shows the discrepancy and another pass is required to set it. 
Following are the references:

`terraform version Terraform v0.12.17`

**Terraform code:**
```
Add the https virtual server
resource "bigip_ltm_virtual_server" "https" {
  name        = "/${local.partition_name}/${var.zone}_vs_${local.app_name}_https"
  description = "${infoblox_ip_allocation.f5_vip.vm_name}.${infoblox_ip_allocation.f5_vip.zone}"
  destination = infoblox_ip_allocation.f5_vip.ip_addr
  ip_protocol = "tcp"
  port        = var.vip_port
  pool        = bigip_ltm_pool.pool.name
  profiles = var.ssl_offloading ? [bigip_ltm_profile_tcp.f5_tcp_lan_optimized_profile["std_profiles"].name,
  bigip_ltm_profile_http.f5_http_xff_profile["std_profiles"].name, bigip_ltm_profile_httpcompress.f5_http_compression_profile["std_profiles"].name] : [bigip_ltm_profile_fastl4.f5_pf_fastl4["std_profiles"].name]
  client_profiles = var.ssl_offloading != true ? null : [var.ssl_cert != "" ? bigip_ltm_profile_client_ssl.ssl["ssl_profile"].name : "/Common/clientssl"]
  server_profiles              = var.backend_encrypted ? [var.backend_profile == null ? "/Common/serverssl" : var.backend_profile] : null
  source        = "0.0.0.0/0"
  source_address_translation   = "automap"
  translate_address            = "enabled"
  translate_port               = "enabled"
  persistence_profiles         = var.ssl_offloading ? [bigip_ltm_persistence_profile_cookie.f5_pers_profile_cookie["cookie"].name] : [bigip_ltm_persistence_profile_srcaddr.f5_pf_persist_srcip_mirror.name]
  vlans_enabled                = true
  vlans                        = local.env_base.TRANSIT_VLANS
  fallback_persistence_profile = var.ssl_offloading ? bigip_ltm_persistence_profile_srcaddr.f5_pf_persist_srcip_mirror.name : ""
  depends_on = [bigip_ltm_pool.pool]
}


resource "bigip_ltm_virtual_address" "vs_va" {
  name            = "/${local.partition_name}/${infoblox_ip_allocation.f5_vip.ip_addr}"
  advertize_route = true
  depends_on = [bigip_ltm_virtual_server.https, bigip_ltm_pool.pool]
}
```

**'terraform plan -out  "test.out"'**
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

module.lodablancer.infoblox_ip_allocation.f5_vip: Refreshing state... [id=record:host/ZG5zLmhvc3QkLm5vbl9ETlNfaG9zdF9yb290LjguMTU5NTA3NzQyOTk5OS5hdS5lZHUudW5pbWVsYi50ZXN0Mi1hcHA:test2-app.unimelb.edu.au/%20]
module.lodablancer.bigip_ltm_persistence_profile_srcaddr.f5_pf_persist_srcip_mirror: Refreshing state... [id=/app_test_app_dev/pf_persist_srcip_mirror_test2_app]
module.lodablancer.bigip_ltm_profile_fastl4.f5_pf_fastl4["std_profiles"]: Refreshing state... [id=/app_test_app_dev/pf_fastL4_test2_app]
module.lodablancer.bigip_ltm_monitor.monitor: Refreshing state... [id=/app_test_app_dev/mon_gateway_icmp_test2_app]
module.lodablancer.bigip_ltm_pool.pool: Refreshing state... [id=/app_test_app_dev/pl_test2_app_80]
module.lodablancer.bigip_ltm_virtual_server.https: Refreshing state... [id=/app_test_app_dev/z1_vs_test2_app_https]
module.lodablancer.bigip_ltm_virtual_address.vs_va: Refreshing state... [id=/app_test_app_dev/<hidden_ip>]
module.lodablancer.bigip_command.cmd_sync["SYNC_FAILOVER_GROUP"]: Refreshing state... [id=apply]

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

`  # module.lodablancer.bigip_ltm_virtual_address.vs_va will be created`
  + resource "bigip_ltm_virtual_address" "vs_va" {
      **+ advertize_route = true**
      + arp             = true
      + auto_delete     = true
      + conn_limit      = 0
      + enabled         = true
      + icmp_echo       = true
      + id              = (known after apply)
      + name            = "/app_test_app_dev/<hidden_ip>"
      + traffic_group   = "/Common/traffic-group-1"
    }

`  # module.lodablancer.bigip_ltm_virtual_server.https will be created`
  + resource "bigip_ltm_virtual_server" "https" {
      + client_profiles              = (known after apply)
      + description                  = "test2-app.unimelb.edu.au"
      + destination                  = "hidden"
      + fallback_persistence_profile = (known after apply)
      + id                           = (known after apply)
      + ip_protocol                  = "tcp"
      + mask                         = (known after apply)
      + name                         = "/app_test_app_dev/z1_vs_test2_app_https"
      + persistence_profiles         = [
          + "/app_test_app_dev/pf_persist_srcip_mirror_test2_app",
        ]
      + pool                         = "/app_test_app_dev/pl_test2_app_80"
      + port                         = 443
      + profiles                     = [
          + "/app_test_app_dev/pf_fastL4_test2_app",
        ]
      + server_profiles              = (known after apply)
      + snatpool                     = (known after apply)
      + source                       = "0.0.0.0/0"
      + source_address_translation   = "automap"
      + state                        = "enabled"
      + translate_address            = "enabled"
      + translate_port               = "enabled"
      + vlans                        = [
          + "/Common/Z1_V305_DEV_EXT_TRANSIT",
        ]
      + vlans_enabled                = true
    }

Plan: 2 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: test.out

To perform exactly these actions, run the following command to apply:
    terraform apply "test.out"
```

 **`terraform apply "test.out"`**
```
module.lodablancer.bigip_ltm_virtual_server.https: Creating...
module.lodablancer.bigip_ltm_virtual_server.https: Provisioning with 'local-exec'...
module.lodablancer.bigip_ltm_virtual_server.https (local-exec): Executing: ["/bin/sh" "-c" "sleep 5"]
module.lodablancer.bigip_ltm_virtual_server.https: Creation complete after 8s [id=/app_test_app_dev/z1_vs_test2_app_https]
module.lodablancer.bigip_ltm_virtual_address.vs_va: Creating...
module.lodablancer.bigip_ltm_virtual_address.vs_va: Creation complete after 1s [id=/app_test_app_dev/<>]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate
```

**Running the Plan again shows that the route advertisement was not actually enabled. The same is seen in the F5 hardware as well**
```
**`terraform plan -out  "test.out"`**
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

module.lodablancer.infoblox_ip_allocation.f5_vip: Refreshing state... [id=record:host/ZG5zLmhvc3QkLm5vbl9ETlNfaG9zdF9yb290LjguMTU5NTA3NzQyOTk5OS5hdS5lZHUudW5pbWVsYi50ZXN0Mi1hcHA:test2-app.unimelb.edu.au/%20]
module.lodablancer.bigip_ltm_profile_fastl4.f5_pf_fastl4["std_profiles"]: Refreshing state... [id=/app_test_app_dev/pf_fastL4_test2_app]
module.lodablancer.bigip_ltm_persistence_profile_srcaddr.f5_pf_persist_srcip_mirror: Refreshing state... [id=/app_test_app_dev/pf_persist_srcip_mirror_test2_app]
module.lodablancer.bigip_ltm_monitor.monitor: Refreshing state... [id=/app_test_app_dev/mon_gateway_icmp_test2_app]
module.lodablancer.bigip_ltm_pool.pool: Refreshing state... [id=/app_test_app_dev/pl_test2_app_80]
module.lodablancer.bigip_ltm_virtual_server.https: Refreshing state... [id=/app_test_app_dev/z1_vs_test2_app_https]
module.lodablancer.bigip_ltm_virtual_address.vs_va: Refreshing state... [id=/app_test_app_dev/<hidden_ip>]
module.lodablancer.bigip_command.cmd_sync["SYNC_FAILOVER_GROUP"]: Refreshing state... [id=apply]

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.lodablancer.bigip_ltm_virtual_address.vs_va will be updated in-place
  ~ resource "bigip_ltm_virtual_address" "vs_va" {
      ~ advertize_route = false -> true
        arp             = true
        auto_delete     = true
        conn_limit      = 0
        enabled         = true
        icmp_echo       = true
        id              = "/app_test_app_dev/<hidden_ip>"
        name            = "/app_test_app_dev/<hidden_ip>"
        traffic_group   = "/Common/traffic-group-1"
    }

Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: test.out

To perform exactly these actions, run the following command to apply:
    terraform apply "test.out"
```

Please let me know if I am missing something or there is some workaround to achieve this.

**Comment by focrensh** [comment]
Tracking with TER-413

**Comment by papineni87** [comment]
@Ankmat 

I am able to see route_advertisement enabled in bigip in the first run, when advertize_route=true in resource "bigip_ltm_virtual_address" .  what is the bigip version you are using and what is terraform-provider-bigip version ?

![image](https://user-images.githubusercontent.com/48274565/88919023-0f29bc00-d288-11ea-96ea-60c90838275d.png)



Below is the config i have tried

resource "bigip_ltm_pool" "pool" {
  name                = "/Common/terraform-pool"
  load_balancing_mode = "round-robin"
  allow_snat          = "yes"
  allow_nat           = "yes"
}
resource "bigip_ltm_virtual_server" "http" {
  pool                       = "/Common/terraform-pool"
  name                       = "/Common/terraform_vs_http"
  destination                = "100.1.1.100"
  port                       = 80
  source_address_translation = "automap"
  depends_on                 = [bigip_ltm_pool.pool]
}

resource "bigip_ltm_virtual_address" "vs_va" {
  name            = "/Common/1.1.1.1"
  advertize_route = true
  depends_on = [bigip_ltm_virtual_server.http, bigip_ltm_pool.pool]
}



HYD-ML-00064439:terraform-provider-bigip papineni$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # bigip_ltm_pool.pool will be created
  + resource "bigip_ltm_pool" "pool" {
      + allow_nat           = "yes"
      + allow_snat          = "yes"
      + id                  = (known after apply)
      + load_balancing_mode = "round-robin"
      + monitors            = (known after apply)
      + name                = "/Common/terraform-pool"
      + reselect_tries      = (known after apply)
      + service_down_action = (known after apply)
      + slow_ramp_time      = (known after apply)
    }

  # bigip_ltm_virtual_address.vs_va will be created
  + resource "bigip_ltm_virtual_address" "vs_va" {
      + advertize_route = true
      + arp             = true
      + auto_delete     = true
      + conn_limit      = 0
      + enabled         = true
      + icmp_echo       = true
      + id              = (known after apply)
      + name            = "/Common/1.1.1.1"
      + traffic_group   = "/Common/traffic-group-1"
    }

  # bigip_ltm_virtual_server.http will be created
  + resource "bigip_ltm_virtual_server" "http" {
      + client_profiles              = (known after apply)
      + destination                  = "100.1.1.100"
      + fallback_persistence_profile = (known after apply)
      + id                           = (known after apply)
      + ip_protocol                  = (known after apply)
      + mask                         = (known after apply)
      + name                         = "/Common/terraform_vs_http"
      + persistence_profiles         = (known after apply)
      + pool                         = "/Common/terraform-pool"
      + port                         = 80
      + profiles                     = (known after apply)
      + server_profiles              = (known after apply)
      + snatpool                     = (known after apply)
      + source                       = (known after apply)
      + source_address_translation   = "automap"
      + state                        = "enabled"
      + translate_address            = (known after apply)
      + translate_port               = (known after apply)
      + vlans_enabled                = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

bigip_ltm_pool.pool: Creating...
bigip_ltm_pool.pool: Creation complete after 2s [id=/Common/terraform-pool]
bigip_ltm_virtual_server.http: Creating...
bigip_ltm_virtual_server.http: Creation complete after 5s [id=/Common/terraform_vs_http]
bigip_ltm_virtual_address.vs_va: Creating...
bigip_ltm_virtual_address.vs_va: Creation complete after 1s [id=/Common/1.1.1.1]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
HYD-ML-00064439:terraform-provider-bigip papineni$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

bigip_ltm_pool.pool: Refreshing state... [id=/Common/terraform-pool]
bigip_ltm_virtual_server.http: Refreshing state... [id=/Common/terraform_vs_http]
bigip_ltm_virtual_address.vs_va: Refreshing state... [id=/Common/1.1.1.1]

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
HYD-ML-00064439:terraform-provider-bigip papineni$ terraform apply
bigip_ltm_pool.pool: Refreshing state... [id=/Common/terraform-pool]
bigip_ltm_virtual_server.http: Refreshing state... [id=/Common/terraform_vs_http]
bigip_ltm_virtual_address.vs_va: Refreshing state... [id=/Common/1.1.1.1]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
HYD-ML-00064439:terraform-provider-bigip papineni$

**Comment by papineni87** [comment]
Issue is not reproducible,  please reopen the issue if you see it again.
