### ISSUE TITLE
F5 and Hashicorp Vault

### ISSUE THREAD

**Issue by hlayson** [F5Networks/terraform-provider-bigip#321]
I am fairly new to this and sorry if this is the wrong place to post this.

Does the bigip provider support passing in username / password from a vault module that outputs the kv pair? It looks like I am running into the provider loading and failing to have those values before the module is invoked even if I put it first in the main.

**Comment by focrensh** [comment]
I am not sure what versions you are running. But this sometimes depends on which providers/resources are being used.

Below is an example from awssecretsmanager that works for me,  I would caution that this would store the pw in clear text within your state file.

```
data "aws_secretsmanager_secret" "bippw" {
  name = "bip_password"
}

data "aws_secretsmanager_secret_version" "creds" {
  secret_id = data.aws_secretsmanager_secret.bippw.id
}

provider "bigip" {
  username = var.f5un
  password = data.aws_secretsmanager_secret_version.creds.secret_string
  address = var.bigipaddr
  port = var.bigipport
}
```
