### ISSUE TITLE
Failing to create Virtual Server 

### ISSUE THREAD

**Issue by Vittitow** [F5Networks/terraform-provider-bigip#327]
Tried bigip provider 1.3 and 1.3.1. Using bigip version 14.1.2.6 and both terraform versions 0.12.29 and 0.12.26.

This just randomly started happening because we've been able to provision virtual servers over the past two weeks. This seems to be the only resource type causing the issue, we're still able to create everything else.

Thanks!

```
Error: HTTP 400 :: {"code":400,"message":"One of the following features must be licensed/provisioned for the URI ltm/virtual/fw-enforced-policy : afm","errorStack":[],"apiError":1}

  on ..\..\src\bigip_ltm_virtual_server.tf line 1, in resource "bigip_ltm_virtual_server" "server":
   1: resource "bigip_ltm_virtual_server" "server" {
```

**Comment by nmenant** [comment]
Hi Vittitow, 

in order to reproduce your issue, is it possible to share the content of bigip_ltm_virtual_server.tf ? Just want to make sure we work on the same setup

thanks

**Comment by Vittitow** [comment]
The exact .tf is the first code snippet. The second code snippet is replaced with example values that we're trying to create. We have two BIGIP's a non-production and production version. It works on the non-production version but not on our production version. However, it worked on the production version in the past so we've been unable to identify what has changed (aside from upgrading the BIGIP version). I can create a repo with more detail if that'll be helpful as well.

```
resource "bigip_ltm_virtual_server" "server" {
  for_each = { 
    for server in var.servers : "vs_${lower(var.partition)}_${server.name}_${server.port}" => server
    if server.address != null
  }

  name = "/${var.partition}/${each.key}"
  destination = each.value.address
  description = "Virtual server for ${lower(var.partition)} partition, ${each.value.name} server using port ${each.value.port}."
  port = each.value.port
  source_address_translation = "automap"
  irules = tolist([for rule in each.value.rules : bigip_ltm_irule.rule["rule_${lower(var.partition)}_${rule}"].name])
  profiles = each.value.profiles
  client_profiles = each.value.client_profiles
  server_profiles = each.value.server_profiles
  vlans_enabled = true
  vlans = each.value.vlans
}
```

```
resource "bigip_ltm_virtual_server" "server" {
  name = "/Staging/vs_staging_arc_443"
  destination = "10.XXX.XX.X"
  description = "Virtual server for staging partition, arc server using port 443."
  port = "443"
  source_address_translation = "automap"
  irules = []
  profiles = []
  client_profiles = []
  server_profiles = []
  vlans_enabled = true
  vlans = []
}
```

**Comment by RavinderReddyF5** [comment]
@Vittitow 

Are you referencing any afm profiles/policies in virtual server ?  because from error it says like afm need to provisioned.

```
Error: HTTP 400 :: {"code":400,"message":"One of the following features must be licensed/provisioned for the URI ltm/virtual/fw-enforced-policy : afm","errorStack":[],"apiError":1}

  on ..\..\src\bigip_ltm_virtual_server.tf line 1, in resource "bigip_ltm_virtual_server" "server":
   1: resource "bigip_ltm_virtual_server" "server" {
```


Did you make sure afm is provisioned after upgrade?

>  However, it worked on the production version in the past so we've been unable to identify what has changed (aside from upgrading the BIGIP version).

**Comment by Vittitow** [comment]
That's the strangeness, we aren't using any AFM profiles. I can manually create the virtual server using the web GUI with the exact same configuration that terraform is attempting to apply but when ran via terraform that is the error that is returned.

**Comment by Vittitow** [comment]
Closing this. After rebooting the F5, everything worked. Not sure what was preventing it before but we're no longer able to reproduce the issue.

Edit: For anyone that may end up in this same boat, we were able to figure out what the issue was. We have a backup inactive F5. We were deleting and recreating the VIP inside of the active F5 but since the inactive F5 still had the old virtual server config it wouldn't work until we did a sync.
