### ISSUE TITLE
bigip_ltm_profile_http -> 01070281:3: Invalid \"http response chunking\" 

### ISSUE THREAD

**Issue by rabru** [F5Networks/terraform-provider-bigip#329]
I run into this issue deploying the following code:

     resource "bigip_ltm_profile_http" "myhttp" {
      name                  = "/Common/my-http"
      defaults_from         = "/Common/http"
    }

Here is the output of the deployment:

    $ terraform apply

    An execution plan has been generated and is shown below.
    Resource actions are indicated with the following symbols:
      + create

    Terraform will perform the following actions:

      # bigip_ltm_profile_http.myhttp will be created
      + resource "bigip_ltm_profile_http" "myhttp" {
          + accept_xff                 = "disabled"
          + basic_auth_realm           = "none"
          + defaults_from              = "/Common/http"
          + fallback_host              = "none"
          + head_erase                 = "none"
          + head_insert                = "none"
          + id                         = (known after apply)
          + insert_xforwarded_for      = "disabled"
          + lws_separator              = "none"
          + name                       = "/Common/my-http"
          + oneconnect_transformations = "enabled"
          + proxy_type                 = "reverse"
          + redirect_rewrite           = "none"
          + request_chunking           = "preserve"
          + response_chunking          = "preserve"
          + server_agent_name          = "BigIP"
          + via_host_name              = "none"
          + via_request                = "preserve"
          + via_response               = "preserve"
        }

    Plan: 1 to add, 0 to change, 0 to destroy.

    Do you want to perform these actions?
      Terraform will perform the actions described above.
      Only 'yes' will be accepted to approve.
    
      Enter a value: yes

    bigip_ltm_profile_http.myhttp: Creating...

    Error: HTTP 400 :: {"code":400,"message":"01070281:3: Invalid \"http response chunking\" value for profile /Common/my-http. Invalid entry, check allowed values.","errorStack":[],"apiError":3}

      on lb.tf line 8, in resource "bigip_ltm_profile_http" "myhttp":
       8: resource "bigip_ltm_profile_http" "myhttp" {

    $ terraform -v
    Terraform v0.12.29
    + provider.bigip v1.3.1
    + provider.local v1.4.0
    + provider.template v2.1.2

    Your version of Terraform is out of date! The latest version

If I define the request_chunking and response_chunking manuelly, it works fine:

    resource "bigip_ltm_profile_http" "myhttp" {
      name                  = "/Common/my-http"
      defaults_from         = "/Common/http"
      request_chunking      = "rechunk"
      response_chunking     = "unchunk"
    }

It looks like the default setup of `request_chunking` and `response_chunking` is not matching the allowed parameter list:

      request_chunking      = { "sustain", "rechunk" }
      response_chunking     = { "sustain", "rechunk", "unchunk" }

BIG-IP version is v15.0.1.1

**Comment by papineni87** [comment]
Tracking with TER-427

**Comment by papineni87** [comment]
@rabru  Issue is fixed and pushed the commit to master branch, can you clone the latest master branch and try it out ?

Bigip version : v15

resource "bigip_ltm_profile_http" "myhttp" {
  name                  = "/Common/my-http"
  defaults_from         = "/Common/http"
}

$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # bigip_ltm_profile_http.test-http will be created
  + resource "bigip_ltm_profile_http" "test-http" {
      + accept_xff                 = (known after apply)
      + basic_auth_realm           = (known after apply)
      + defaults_from              = "/Common/http"
      + description                = (known after apply)
      + fallback_host              = (known after apply)
      + head_erase                 = (known after apply)
      + head_insert                = (known after apply)
      + id                         = (known after apply)
      + insert_xforwarded_for      = (known after apply)
      + lws_separator              = (known after apply)
      + name                       = "/Common/test-http"
      + oneconnect_transformations = (known after apply)
      + proxy_type                 = (known after apply)
      + redirect_rewrite           = (known after apply)
      + request_chunking           = (known after apply)
      + response_chunking          = (known after apply)
      + response_headers_permitted = (known after apply)
      + server_agent_name          = (known after apply)
      + via_host_name              = (known after apply)
      + via_request                = (known after apply)
      + via_response               = (known after apply)
      + xff_alternative_names      = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

bigip_ltm_profile_http.test-http: Creating...
bigip_ltm_profile_http.test-http: Creation complete after 3s [id=/Common/test-http]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
$ terraform destroy
bigip_ltm_profile_http.test-http: Refreshing state... [id=/Common/test-http]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # bigip_ltm_profile_http.test-http will be destroyed
  - resource "bigip_ltm_profile_http" "test-http" {
      - defaults_from              = "/Common/http" -> null
      - id                         = "/Common/test-http" -> null
      - name                       = "/Common/test-http" -> null
      - response_headers_permitted = [] -> null
      - xff_alternative_names      = [] -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

bigip_ltm_profile_http.test-http: Destroying... [id=/Common/test-http]
bigip_ltm_profile_http.test-http: Destruction complete after 0s

Destroy complete! Resources: 1 destroyed.

**Comment by RavinderReddyF5** [comment]
fixed in latest release
