### ISSUE TITLE
Can support GTM ? 

### ISSUE THREAD

**Issue by luruiqiang** [F5Networks/terraform-provider-bigip#332]
We plan to use terraform to manage LTM and GTM .  Now the terraform-provider-bigip has supported LTM. If we use it to manage GTM, we only use AS3. 
I want to ask whether terraform-provider-bigip can support GTM without AS3.  if yes, when or which version ?

thanks.

**Comment by papineni87** [comment]
Adding   @focrensh   @nmenant

**Comment by focrensh** [comment]
The direction from GTM support is through the AS3 resource. This provides a similar user experience and input regardless of the automation tool used.

**Comment by luruiqiang** [comment]
Got it. Thanks.
