### ISSUE TITLE
Seemingly no way to specify iRule order

### ISSUE THREAD

**Issue by ddcrjlalumiere** [F5Networks/terraform-provider-bigip#340]
The setup for one of our vServers has ~30 iRules that get applied to it. While many of them are order independent several of them are required to be in a particular order. AFAICT the `bigip_ltm_irule` resource does not have a way to accommodate this. Is there an existing workaround and/or can ordering be added as a parameter for the resource?

**Comment by ddcrjlalumiere** [comment]
As an update I was able to set `priority` in the iRules themselves to accomplish this, but that leaves the rules unintuitively out of order from what folks expect the processing to look like so is not ideal.

**Comment by nmenant** [comment]
Hi,

Are you referring to bigip_ltm_virtual_server ? https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_ltm_virtual_server 

When you supply a list iRule to this resource, are they not assigned to the VS in the same order ? I'll try to replicate this later but if you have some insights on this, it will save time. 

thanks

**Comment by ddcrjlalumiere** [comment]
Digging in to our code I think the issue in our case is we have a list of iRules that lives with the main vServer code, and then a separate list that gets passed in as a variable and then those two are concatenated together in the actual vServer resource. Within each list they are processed in order but that's not necessarily the order we want when they are ultimately combined. I think however splitting up those lists even further (e.g., to add "first" & "last" lists) will be an acceptable work around.

**Comment by focrensh** [comment]
In my testing, order within the resource itself does match what is provisioned onto the BIG-IP.

TF: 0.13
Provider: bigip v1.3.2

```
resource "bigip_ltm_virtual_server" "http" {
  name        = "/Common/terraform_vs_http"
  destination = "10.1.2.3"
  ip_protocol = "tcp"
  port        = 80
  profiles    = ["/Common/http"]
  # irules      = ["_sys_https_redirect", "/Common/Shared/telemetry_local_rule"]
  irules      = ["/Common/Shared/telemetry_local_rule","_sys_https_redirect"]
}
```
