### ISSUE TITLE
ssl forward proxy configuration is not supported

### ISSUE THREAD

**Issue by tizianorosato-gr** [F5Networks/terraform-provider-bigip#341]
ssl forward proxy configuration is not supported

**Comment by nmenant** [comment]
Have you looked into using AS3 and our AS3 terraform resource ?  SSL forward proxy is supported there: 

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/tls-encryption.html#configuring-explicit-forward-proxy-settings-in-ssl-tls-profiles

https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_as3

**Comment by tizianorosato-gr** [comment]
Hi, Yes I'm aware that is supported on AS3 and I'm using it already.
But sometimes is useful to use Terraform only without AS3.

**Comment by focrensh** [comment]
Tracking with TER-472

**Comment by papineni87** [comment]
@tizianorosato-gr  Added ssl forward proxy config in v1.5.0. Please reopen the issue if you still see any issue with it.

**Comment by tizianorosato-gr** [comment]
> in v1.5.0.

great news!

**Comment by tizianorosato-gr** [comment]
> @tizianorosato-gr Added ssl forward proxy config in v1.5.0. Please reopen the issue if you still see any issue with it.

online docs has been already updated? 
I see difference between:
https://github.com/F5Networks/terraform-provider-bigip/blob/master/docs/resources/bigip_ltm_profile_client_ssl.md
and
https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_ltm_profile_client_ssl

**Comment by RavinderReddyF5** [comment]
@tizianorosato-gr looks documentation change is not reflected in registry, we will work with hashicorp in addressing this ? meanwhile can u take reference documentation from : https://github.com/F5Networks/terraform-provider-bigip/blob/master/docs/resources/bigip_ltm_profile_client_ssl.md
