### ISSUE TITLE
add support for event driven service discovery

### ISSUE THREAD

**Issue by chen23** [F5Networks/terraform-provider-bigip#343]
Please add support to use the event driven service API:

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/discovery.html#event-driven-service-discovery

GET / PATCH / DELETE
i.e. https://192.0.2.14/mgmt/shared/service-discovery/task/~tenant~AjMMFWdDfZCYK2WIsFBAgiBP5611AKu1R2DnpmlLFpk3D

GET / POST
i.e. https://192.0.2.14/mgmt/shared/service-discovery/task/~tenant~AjMMFWdDfZCYK2WIsFBAgiBP5611AKu1R2DnpmlLFpk3D/nodes

POST/DELETE TO:
 i.e. https://192.0.2.14/mgmt/shared/service-discovery/task

event driven (read/write on nodes)
```
{
    "id": "~tenant~AjMMFWdDfZCYK2WIsFBAgiBP5611AKu1R2DnpmlLFpk3D",
    "schemaVersion": "1.0.0",
    "provider": "event",
    "resources": [
        {
            "type": "pool",
            "path": "/Common/test_pool",
            "options": {
                "servicePort": 8080
            }
        }
    ],
    "nodePrefix": "/Common/"
}
```

example of creating consul endpoint (POST) read-only on nodes
```
{
    "id": "~tenant~AjMMFWdDfZCYK2WIsFBAgiBP5611AKu1R2DnpmlLFpk3D",
    "schemaVersion": "1.0.0",
    "updateInterval": 10,
    "provider": "consul",
    "providerOptions": {
                        "uri": "http://10.1.1.8:8500/v1/catalog/service/app001"
    }
    ,
    "resources": [
        {
            "type": "pool",
            "path": "/Common/test_pool",
            "options": {
                "servicePort": 8080
            }
        }
    ],
    "nodePrefix": "/Common/"
}
```

**Comment by nmenant** [comment]
TER-482 has been added to track this feature request

**Comment by papineni87** [comment]
@chen23  added new resource for event driven service discovery. Let me know any issue with it.
