### ISSUE TITLE
Feature request ClientLdap and ServerLdap profiles

### ISSUE THREAD

**Issue by Ankmat** [F5Networks/terraform-provider-bigip#348]
Can we have a resource for creating clientLdap and ServerLdap profiles. Please suggest if there is some current workaround which can be used to accomplish at present.

**Comment by Ankmat** [comment]
The corresponding LDAP monitor will also be required.

**Comment by papineni87** [comment]
I guess AS3 has support for ldap monitor and profiles, we can use terraform as3 resource to configure ldap things.

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/health-monitors.html
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/tls-encryption.html#securing-client-and-server-side-ldap-traffic

Terraform As3 resource:
https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_as3


@Ankmat  can you try with as3 resource  to configure it

**Comment by KrithikaChidambaram** [comment]
Hi, closing this request now. 
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
