### ISSUE TITLE
add feature - bigip_ltm_persistence_profile_ssl - cookie_method

### ISSUE THREAD

**Issue by Luubosi** [F5Networks/terraform-provider-bigip#351]
hi,
please add to bigip_ltm_persistence_profile_ssl cookie_method.
https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_ltm_persistence_profile_ssl

It would be graet to use rewrite...

Thanks

_Error: Unsupported argument
  on lb_config.tf line 72, in resource "bigip_ltm_persistence_profile_cookie" "persistence_profile_cookie":
  72:   cookie_method                = rewrite
An argument named "cookie_method" is not expected here._

**Comment by nmenant** [comment]
We created TER-500 internally to update https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_ltm_persistence_profile_cookie to support a new method parameter (optional). Default value will be insert

**Comment by papineni87** [comment]
@Luubosi  Added cookie method in v1.5.0 release. Please reopen the issue if you still see any issue with it
