### ISSUE TITLE
alias does not work with bigip_provider

### ISSUE THREAD

**Issue by tomservo3428** [F5Networks/terraform-provider-bigip#358]
bigip_provider version: 1.3.2
terraform version : 0.12.24

I am attempting to use two BIGIP providers, one for each of my BIGIPs. To do so, I attempted the following in my providers file:

```
provider "bigip" {
  alias = "bigip_1"
  address = "1.1.1.1"
  username = "un"
  password = "pw"
}

provider "bigip" {
  alias = "bigip_2"
  address = "2.2.2.2"
  username = "un"
  password = "pw"
}
```

When I run terraform plan, I get the following errors:

_Error: Missing required argument
The argument "username" is required, but was not set._

_Error: Missing required argument
The argument "address" is required, but was not set._

_Error: Missing required argument
The argument "password" is required, but was not set._

In an attempt to troubleshoot the errors, I removed one of the providers and the alias of the remaining provider, leaving this:

```
provider "bigip" {
  address = "1.1.1.1"
  username = "un"
  password = "pw"
}
```

Which worked fine. When I added the alias back to the provider...

```
provider "bigip" {
  alias = "bigip_1"
  address = "1.1.1.1"
  username = "un"
  password = "pw"
}
```

I get the "missing required argument" errors again. Using aliases for providers is pretty standard for Terraform, so that I am seeing errors when I attempt to do so with the bigip_provider seems inconsistent with how Terraform should behave. 

I would recommend adding support for the alias property in the bigip_provider resource.

Thanks!

**Comment by papineni87** [comment]
@fustilarian01  I am able to use alias with the bigip provider and able to create multiple pools each with different bigip.

provider "bigip" {
   address  = "xxxxxxx"
  alias = "east"
  username = "xxxxx"
  password = "xxxxxx"
}

resource "bigip_ltm_pool" "pool-east" {
  name                = "/Common/terraform-pool-east"
  provider             = "bigip.east"
  load_balancing_mode = "round-robin"
  description         = "Test-Pool-east"
  allow_snat          = "yes"
  allow_nat           = "yes"
}

provider "bigip" {
   address = "xxxxxxx"
  alias = "west"
  username = "xxxx"
  password = "xxxxx"
}

resource "bigip_ltm_pool" "pool-west" {
  name                = "/Common/terraform-pool-west"
  provider            = "bigip.west"
  load_balancing_mode = "round-robin"
  description         = "Test-Pool-west"
  allow_snat          = "yes"
  allow_nat           = "yes"
}

Can you try using alias in the above way, to see if it works ?

**Comment by tomservo3428** [comment]
I'll try your suggestion and let you know. One difference between your approach and mine: my provider definitions are in providers.tf, yours are defined alongside the resources using them. Is there a reason for going with your approach?

**Comment by papineni87** [comment]
I tried in another way also, with the providers.tf and resources.tf . It worked out without any issues.

providers.tf
>>>>>>>>>>>>>>>>>>>>
provider "bigip" {
address = "xxxxxxx"
alias = "east"
username = "xxxxx"
password = "xxxxxx"
}


provider "bigip" {
address = "xxxxxxx"
alias = "west"
username = "xxxx"
password = "xxxxx"
}



resources.tf
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
resource "bigip_ltm_pool" "pool-east" {
name = "/Common/terraform-pool-east"
provider = "bigip.east"
load_balancing_mode = "round-robin"
description = "Test-Pool-east"
allow_snat = "yes"
allow_nat = "yes"
}

resource "bigip_ltm_pool" "pool-west" {
name = "/Common/terraform-pool-west"
provider = "bigip.west"
load_balancing_mode = "round-robin"
description = "Test-Pool-west"
allow_snat = "yes"
allow_nat = "yes"
}

**Comment by RavinderReddyF5** [comment]
@fustilarian01 closing this issue, if you still see any issue please open new issue
