### ISSUE TITLE
Provider try to connect to host even when module count is 0

### ISSUE THREAD

**Issue by siwyroot** [F5Networks/terraform-provider-bigip#360]
Hello,

It's more of the question then bug, I have a terraform code that sometimes requires big lb configuration for some infra and in some cases count for it is 0. I cannot get provider to be "silent" even when there's nothing to do for it. Is this is normal behavior? I could not find a way to disable provider other then changing file name with that part of code so terraform will ignore it.

**Comment by papineni87** [comment]
I guess that is a normal behaviour when have you bigip provider in config and all the bigip resources with count as 0. I think terraform will do the basic connectivity check for any provider defined in the config.
