### ISSUE TITLE
1.3.3 completely breaks bigip_ltm_pool_attachment

### ISSUE THREAD

**Issue by ghost** [F5Networks/terraform-provider-bigip#363]
### Environment

 * TMOS/Bigip Version: 14.1.2.6
 * Terraform Version: v0.12.29
 * Terraform bigip provider Version: 1.3.3

### Summary

1.3.3 completely breaks bigip_ltm_pool_attachment.  I've seen the following issues.

* Code that works on 1.3.2 now throws this error on 1.3.3.
`Error: "node" must match Node-address:Port and Node Address is IP/FQDN. e.g. 1.1.1.1:80/www.google.com:80`

I tried changing the TF code to give what is now suggested as required, however ran into these issues.
* Cannot add existing host by hostname if it uses a static IP (TF throws an error that the host is set to a static IP when trying to add by hostname)
* Cannot add existing host by IP. TF now throws an error that the host already exists. 

I can however have bigip_ltm_pool_attachment create a new node, however I cannot name that node if I want to use a static IP address. Also the TF name bigip_ltm_pool_attachment would suggest that I can attach nodes that already exist to a pool (like was allowed in 1.3.2).

### Steps To Reproduce

1. Provide terraform resource config which you are facing trouble along with the output of it.
`resource "bigip_ltm_node" "test-node" {
    name     = "/LB_Stage/Test-Node-01"
    address  = "10.20.30.40%1"
}

resource "bigip_ltm_pool" "test-pool" {
    name                = "/LB_Stage/Test-Pool-01"
}

resource "bigip_ltm_pool_attachment" "test-node-pool-attach-name" {
    pool = bigip_ltm_pool.test-pool.name
    node = "${bigip_ltm_node.test-node.name}:443"
}`

`Error: "node" must match Node-address:Port and Node Address is IP/FQDN. e.g. 1.1.1.1:80/www.google.com:80`

### Expected Behavior
I expected the existing node to be added to the pool

### Actual Behavior
An error is thrown after saying yes to apply the changes. 
`Error: "node" must match Node-address:Port and Node Address is IP/FQDN. e.g. 1.1.1.1:80/www.google.com:80`

**Comment by howsTricks** [comment]
We're also experiencing this issue, but for a different node definition:

resource "bigip_ltm_pool_attachment" "node-pool-attach1" {
  depends_on = [bigip_ltm_pool.pool]
  pool       = "/${var.partition}/pool.${var.name}"
  node       = "/${var.partition}/nodehostname:1234"
}

I've confirmed by downgrading to 1.3.2 and not experiencing this error that this is new in 1.3.3

**Comment by zx1986** [comment]
same issue? https://github.com/F5Networks/terraform-provider-bigip/issues/361

**Comment by ghost** [comment]
@zx1986 Yep that looks like the same issue. I looked through previous tickets but missed that one because the title is junk.

**Comment by focrensh** [comment]
Closing into https://github.com/F5Networks/terraform-provider-bigip/issues/361

**Comment by papineni87** [comment]
@zx1986 @howsTricks @tmashos @ivey 

we have added legacy support of pool attachment with new release 1.4 where node input will taken from node resource along with new behaviour where node input will be given directly with ip:port/fqdn:port.

Let me know any issues with 1.4 release, and sure we will address the concerns in the new behaviour of pool attachment.
