### ISSUE TITLE
Failure to Install Provider 1.4.0

### ISSUE THREAD

**Issue by merps** [F5Networks/terraform-provider-bigip#366]
### Environment

 * TMOS/Bigip Version: AWS AMI *F5 BIGIP-15.1.0.2-0.0.9 PAYG-Best 25Mbps*
 * Terraform Version: *Terraform v0.13.3*
 * Terraform bigip provider Version: *1.4.0*

### Summary

Attempting to upgrade from provider from **1.3.3** to **1.4.0** and receive the 
```
Error: Failed to install provider

Error while installing f5networks/bigip v1.4.0: could not query provider
registry for registry.terraform.io/f5networks/bigip: failed to retrieve
authentication checksums for provider: 404 Not Found
```

### Steps To Reproduce

1. Update `providers.tf` for new version:
```
terraform {
  required_providers {
    bigip = {
      source = "F5Networks/bigip"
      version = "1.4.0"
    }
  }
  required_version = ">= 0.13"
}
```
2. Perform `terraform init` to install updated provider:
```
terraform init
```

### Expected Behavior

For provider to be downloaded an installed as per BIG-IP Provider `1.3.3`:
```
✗ terraform init

Initializing provider plugins...
- Finding f5networks/bigip versions matching "1.3.3"...
- Installing f5networks/bigip v1.3.3...
- Installed f5networks/bigip v1.3.3 (signed by a HashiCorp partner, key ID 8D69F031B13946D3)
```
...*output snipped*

### Actual Behavior

As per problem statement;

```➜  infra git:(master) ✗ terraform init   
Initializing provider plugins...
- Finding f5networks/bigip versions matching "1.4.0"...
```
...*output snipped*
```
Error: Failed to install provider

Error while installing f5networks/bigip v1.4.0: could not query provider
registry for registry.terraform.io/f5networks/bigip: failed to retrieve
authentication checksums for provider: 404 Not Found
```

**Comment by merps** [comment]
Additional Information:
* reference repo: [f5-cwl-telegraf](https://github.com/merps/f5-cwl-telegraf)
* module repo: [terraform-aws-bigip](https://github.com/merps/terraform-aws-bigip/tree/ip-outputs)

**Comment by RavinderReddyF5** [comment]
@merps we worked with hashicorp team to address this issue, you should be able to download `v1.4.0` now.

**Comment by papineni87** [comment]
terraform init
2020/10/26 20:30:48 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2020/10/26 20:30:48 [INFO] Terraform version: 0.13.5  
2020/10/26 20:30:48 [INFO] Go runtime version: go1.14.7
2020/10/26 20:30:48 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init"}
2020/10/26 20:30:48 [DEBUG] Attempting to open CLI config file: /Users/papineni/.terraformrc
2020/10/26 20:30:48 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/10/26 20:30:48 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/10/26 20:30:48 [DEBUG] ignoring non-existing provider search directory /Users/papineni/.terraform.d/plugins
2020/10/26 20:30:48 [DEBUG] ignoring non-existing provider search directory /Users/papineni/Library/Application Support/io.terraform/plugins
2020/10/26 20:30:48 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2020/10/26 20:30:48 [INFO] CLI command args: []string{"init"}
2020/10/26 20:30:48 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----

Initializing the backend...
2020/10/26 20:30:48 [DEBUG] New state was assigned lineage "c640b5ee-d1a8-be63-e3d1-e49f0545c6ca"
2020/10/26 20:30:48 [DEBUG] checking for provisioner in "."
2020/10/26 20:30:48 [DEBUG] checking for provisioner in "/usr/local/bin"
2020/10/26 20:30:48 [INFO] Failed to read plugin lock file .terraform/plugins/darwin_amd64/lock.json: open .terraform/plugins/darwin_amd64/lock.json: no such file or directory

Initializing provider plugins...
2020/10/26 20:30:48 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
- Finding latest version of f5networks/bigip...
2020/10/26 20:30:48 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2020/10/26 20:30:48 [DEBUG] GET https://registry.terraform.io/v1/providers/f5networks/bigip/versions
2020/10/26 20:30:49 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2020/10/26 20:30:49 [DEBUG] GET https://registry.terraform.io/v1/providers/f5networks/bigip/1.4.0/download/darwin/amd64
2020/10/26 20:30:49 [DEBUG] GET https://github.com/F5Networks/terraform-provider-bigip/releases/download/v1.4.0/terraform-provider-bigip_1.4.0_SHA256SUMS
2020/10/26 20:30:50 [DEBUG] GET https://github.com/F5Networks/terraform-provider-bigip/releases/download/v1.4.0/terraform-provider-bigip_1.4.0_SHA256SUMS.sig
- Installing f5networks/bigip v1.4.0...
2020/10/26 20:30:56 [DEBUG] Provider signed by 8D69F031B13946D3 terraform_devs (GPG key for Terraform provider repo) <terraform_devs@f5.com>
- Installed f5networks/bigip v1.4.0 (signed by a HashiCorp partner, key ID 8D69F031B13946D3)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, we recommend adding version constraints in a required_providers block
in your configuration, with the constraint strings suggested below.

* f5networks/bigip: version = "~> 1.4.0"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

**Comment by merps** [comment]
thank you @RavinderReddyF5 it appears to be functioning as expected:
```
- Finding f5networks/bigip versions matching "1.4.0"...
- Installing f5networks/bigip v1.4.0...
- Installed f5networks/bigip v1.4.0 (signed by a HashiCorp partner, key ID 8D69F031B13946D3)
```
