### ISSUE TITLE
Allow setting the node monitor when creating using bigip_ltm_pool_attachment

### ISSUE THREAD

**Issue by ajchiarello** [F5Networks/terraform-provider-bigip#369]
### Is your feature request related to a problem? Please describe.
After upgrading to 1.4.0, I converted my script to no longer use the bigip_ltm_node resource, since the documentation says this is deprecated, and instead only used the bigip_ltm_pool_attachment to create both the node and add it to the pool. This worked, except that it assigned the node the default monitor (icmp), when I needed it to have a different one (https_443).  I had previously set this in the bigip_ltm_node resource, but there is no way to set it in the bigip_ltm_pool_attachment. I have set this as the monitor for the bigip_ltm_pool resource, but the node did not inherit it.

### Describe the solution you'd like
The ability to set the monitors for the node in the bigip_ltm_pool_attachment resource, as I could in the bigip_ltm_node resource. Alternatively, that the nodes inherit the monitors in the bigip_ltm_pool resource.

**Comment by nmenant** [comment]
Can you expand on the requirement to have monitors on the node level ? Is it to just be able to differentiate node state (ie service available and server replying to ping) ?

If you have a monitor on your pool (https_443), then this monitor will be inherited by all the pool members assigned to this pool. This will allow you to make sure that the service is up and running as expected. 

if you need to assign gateway_icmp / icmp monitor to your node, why not setting this up by default on your big-ip ? 

![image](https://user-images.githubusercontent.com/13098758/97994691-d7ca2e80-1de5-11eb-8ad7-8ef224c1d93a.png)

this way, all nodes will get this icmp monitor by default

**Comment by ajchiarello** [comment]
When I originally posted this, it looked like the node wasn't inheriting the check from the bigip_ltm_pool resource. Ever since then, however, it has inherited, which resolves this for me.
