### ISSUE TITLE
Possibly change create behaviour to not overwrite existing configuration

### ISSUE THREAD

**Issue by ehlomarcus** [F5Networks/terraform-provider-bigip#386]
### Is your feature request related to a problem? Please describe.
I would also like to see a change in behaviour in creation of resourse which hasn't been imported. The scenario I'm seeing is the possibility of overwriting an existing tenant/partition, which may or may not have been created using AS3.

### Describe the solution you'd like
If possible, use different methods for Create and Update.

Assuming I have defined resource and it is not in my state yet.
```hcl
resource "bigip_as3" "partition1" {
  as3_json = data.template_file.partition1.rendered
  tenant_list = "Partition1"
  tenant_filter = "Partition1"
}
```
Also assume that Partition1 already exist in BIGIP.

With those assumptions in mind, I would think I could get responce: tenant/partition already exist, when trying to create resource with terraform apply.

If I would import that resource first with terraform import bigip_as3.partition1 Partition1 and it is not created with AS3, then return an error of not found. If it is an AS3 definition, then return the imported object to state.

Now assume import succeded, then I would be able to run terraform apply and get a proper diff of what I would like to change.

### Describe alternatives you've considered
Trying to find different RBAC settings for specific users which would restrict which partition a user can access. No success.

### Additional context
The behaviour we are seeing is that any user with access can submit AS3 definition and possibly overwrite configuration unintentially, regardless of it being AS3 or not. So it not strictly a terraform "issue".

**Comment by nmenant** [comment]
i'm reviewing a behavior of bigip_as3 resource. Based on this, i may have an option for you. I'll come back to you asap 

thanks

**Comment by nmenant** [comment]
Hi,

I did some research and would like to provide an way to restrict a terraform user to a specific partition: 

You have different "safety" mechanism: 

- tenant_filter will ensure that we only update the relevant partition. This would ensure that a typo/mistake in the AS3 declaration won't impact another tenant
- Restrict an API user to a specific partition with AS3. By default the API endpoint for AS3 is: https://<BIG-IP>/mgmt/shared/appsvcs/declare. However you can make sure your AS3 will influence a specific tenant by using https://<BIG-IP>/mgmt/shared/appsvcs/declare/<tenant_name>. If you use this uri, then you'll make sure that you won't impact any other tenant
- BIG-IP has the ability to create API user that will only be allowed specific method and specific URI on the BIG-IP. It is documented here: https://devcentral.f5.com/s/articles/icontrol-rest-fine-grained-role-based-access-control-30773

How does it help you? Let's imagine you want to restrict a user to partition PEPSI

- Create a new user with admin rights 
- use https://devcentral.f5.com/s/articles/icontrol-rest-fine-grained-role-based-access-control-30773 to allow this user to only send API call to https://<BIG-IP>/mgmt/shared/appsvcs/declare/PEPSI. This user shouldn't be allowed to communicate with https://<BIG-IP>/mgmt/shared/appsvcs/declare

This user is now restricted on using AS3 with this specific URI https://<BIG-IP>/mgmt/shared/appsvcs/declare/PEPSI. This user won't be able to change/modify/delete by mistake another partition

Going back to terraform, this is what is happening when you use: 

``` 
resource "bigip_as3" "partition1" {
  as3_json = data.template_file.partition1.rendered
  tenant_filter = "PEPSI"
}
``` 

when you specify tenant_filter, the URI used by the TF resource will be https://<BIG-IP>/mgmt/shared/appsvcs/declare/PEPSI and not https://<BIG-IP>/mgmt/shared/appsvcs/declare

So this will be consistent with you RBAC setting. 

Do you see this as a viable way to restrict your user to his partition and not be able to change any other partition via AS3?

**Comment by ehlomarcus** [comment]
Thank you @nmenant 

That was exactly what we where looking for. Good explenation of how tenant_filter filter works, much like how I though my self.

Rbac also seem to work as you describe, so we'll have to look more at it. I think it was the fact that we use Radius that messed it up for us. It is hard when the UI behave differently than the API. And that you have to use the API to create local users and roles is not really user friendly.

A final note:

AS3 is a nice addition to how you manage a bigip, but the fact that it is sort of one single API is a bit frustrating and confusing. 
Looking at it from a Kubernetes point of view, then each of the configurable options in an application should be it's own API endpoint and resource. A tenant should be seen as a Kubernetes namespace, and should not be able to interact with items out side of it.

You can take that to terraform as well. I would really like to see each of the classes in a ADC application to be defined as a terraform resource. Each with it's own data lookup and possibility to import and also update each individual piece, instead of one whole blob of json. You could look at terraform-provider-rke and terraform-provider-ignition, they some examples of how AS3 could look like in the future.
