### ISSUE TITLE
bigip_ltm_pool_attachment - not able to assign name

### ISSUE THREAD

**Issue by centran** [F5Networks/terraform-provider-bigip#395]
### Problem - Old method vs New
**OLD**: With the `bigip_ltm_node` resource (which is being deprecated) there was both a _name_ and an _address_ argument. This allowed to having the node be named differently than the IP:PORT/FQDN:PORT

**NEW**: Now `bigip_ltm_pool_attachment` will create the node for you (which is nice) but we have lost the ability to name the node how we like.

### Solution - Change node argument to a block
Add two arguments in a block for the _node_ argument in `bigip_ltm_pool_attachment`

- `address` - (Required) Pool member address/fqdn with service port, (ex: 1.1.1.1:80/www.google.com:80). (Note: Member will be in same partition of Pool)
- `name` - (Optional) Name of the node if different from addess/fqdn

### bigip_ltm_pool_attachment
```
resource "bigip_ltm_pool_attachment" "attach_node" {
  pool = bigip_ltm_pool.pool.name
  node {
    address = "1.1.1.1:80"
    name = "One_dot_one"
  }
}
```
### Issues

- Would the new name argument need the full /partition/node_name or would the partition be prepending based on the pool partition?

**Comment by papineni87** [comment]
Tracking with TER-520

**Comment by nmenant** [comment]
Hi Centran,

For users requiring to setup the node name, we will recommend to use the "original" Method: 

- Create the node
- Assign the node to the pool via bigip_ltm_pool_attachment

There is a mistake in the documentation. This resource will not be deprecated and can still be used, my apologies for the confusion

Changing the node parameter to a block is likely to introduce a breaking change for many customers. We need to be careful on this kind of change.

We will work on updating documentation accordingly. 

let me know if you have any feedback/question

thanks

**Comment by davidfischer-ch** [comment]
Hello @nmenant,

Thank you for your response, we had the same issue (Etat de Genève) and we were going to open an issue about this deprecation.

Thank you for the good news.

**Comment by RavinderReddyF5** [comment]
Hi @centran @davidfischer-ch as per comments from [nmenat](https://github.com/F5Networks/terraform-provider-bigip/issues/395#issuecomment-740687572) closing this issue. please open new issue if you have any concerns
