### ISSUE TITLE
Error checking is not needed on primitive types

### ISSUE THREAD

**Issue by dannyk81** [F5Networks/terraform-provider-bigip#4]
Throughout the code there are many `Read` method implementation that perform error checking on primitive types (TypeBool, TypeInt, TypeFloat, TypeString).

However this is not needed, since only Aggregate types require Error checking.

Example where this is not needed:
https://github.com/terraform-providers/terraform-provider-bigip/blob/0ce45fa06c32a7a173a91bc436ff92345dc6c363/bigip/resource_bigip_cm_device.go#L117-L127

All three of the attributes above are of TypeString type and don't require error checking.

Reference: https://www.terraform.io/docs/extend/best-practices/detecting-drift.html#error-checking-aggregate-types

@scshitole

**Comment by focrensh** [comment]
Closing stale issue, please open a new issue if it is still possible to reproduce on newest provider version.
