### ISSUE TITLE
feature request: license revocation

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/terraform-provider-bigip#417]
### Is your feature request related to a problem? Please describe.
The problem is that if a VM is destroyed by Terraform without the license revoked, that license is considered used and a call to support is required to release it.

### Describe the solution you'd like
We have a customer that uses Terraform to deploy BIG-IP and then licenses the device via DO. They eventually destroy the VE using Terraform destroy. There is no nice way to revoke the license before blowing away the VM, so they are currently running a bash script of "tmsh revoke sys license" at destroy, from within Terraform.

They would like a "nicer" way to know that a license has been revoked before the VM is destroyed. Could this be achieved via the BIG-IP provider for Terraform?

This is somewhat related to a feature request in DO: https://github.com/F5Networks/f5-declarative-onboarding/issues/9

However in the case of this customer we would also be happy if the license could be applied and revoked via the Terraform provider.

### Describe alternatives you've considered
The alternative right now is to run a bash script via Terraform at time of VM resource deletion.

**Comment by Eric-Jckson** [comment]
Here is an example of the workaround that we are using to revoke the license in an azure linux vm using a provisioner block in the azurerm resource "azurerm_linux_virtual_machine". If a f5 bigip terraform resource was available it would be able to update/change the license if needed.

```  
provisioner "remote-exec" {
    when    = destroy
    inline = [
      "tmsh revoke /sys license"
    ]
    connection {
      type     = "ssh"
      user     = "admin"
      password = random_password.f5_password.result
      host     = self.private_ip_address
    }
  }
  ```

**Comment by RavinderReddyF5** [comment]
@mikeoleary from your requirement it is best to use @Eric-Jckson work-around way, because normally terraform provider bigip resources supported for Create/Read/Update/Delete Operation. But your requirement is only needed incase of destroy operation, in addition to work-around we also have `bigip_command` resource: https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_command which might be helpful for your requirement.

**Comment by trinaths** [comment]
Based on the suggested workaround, closing this issue.
