### ISSUE TITLE
Extend documentation with Import usage and Attributes References

### ISSUE THREAD

**Issue by CSimpiFoN** [F5Networks/terraform-provider-bigip#419]
### Is your feature request related to a problem? Please describe.
Documentation would need to contain how to use the import functionality of the provider with examples, like other providers. Also, attribute references should be added, so no investigation is needed what outputs can be configured.

### Describe the solution you'd like
Add the missing details to the resources' documentations

### Describe alternatives you've considered
No alternatives needed

### Additional context
Should look like RabbitMQ  binding resource for example:
Attributes Reference
In addition to all arguments above, the following attributes are exported:

properties_key - A unique key to refer to the binding.

Import
Bindings can be imported using the id which is composed of vhost/source/destination/destination_type/properties_key. E.g.

$ terraform import rabbitmq_binding.test test/test/test/queue/%23

**Comment by trinaths** [comment]
Created [INFRAANO-813] for internal tracking
