### ISSUE TITLE
BIG-IQ resource use requires BIG-IP login

### ISSUE THREAD

**Issue by jkknorr** [F5Networks/terraform-provider-bigip#442]
In our organization we'd like to use BIG-IQ as the exclusive front-end for automation tasks with our technical partners.  However, the only Terraform provider available to interact with BIG-IQ requires a BIG-IP login, which is something we'd like to avoid.

Would it be possible to add a feature to the provider to use a BIG-IQ login, if using only BIG-IQ-related resources?

**Comment by nmenant** [comment]
Tracking this requirement internally with INFRAANO-272

**Comment by dan-da-man-86** [comment]
Hello jkknorr,
We have a similar desire in our environment. For the time being, I have been able to use the BIG-IQ to authenticate the BIGIP provider using the following TF provider config. The BIG-IQ is the only device that is online when the BIG-IPs need to be built, so we only want to rely on BIG-IQ being online when TF runs. It's worth noting that we're currently having some issues, but those appear to be unrelated to this at face value (issue 436 and 437 - we do have some workarounds in the meantime). 

provider "bigip" {
  address         = var.bigIqHost
  username        = var.bigIqUsername
  password        = var.bigIqPassword
  token_auth      = true
  login_ref       = "tmos"
}

**Comment by jkknorr** [comment]
dan-da-man-86,

Thanks for the suggested provider - it doesn't work in our environment, I'm pretty sure because we're using LDAP auth instead of local and I'm having trouble figuring out how "login_ref" correlates with "loginProviderName".

**Comment by RavinderReddyF5** [comment]
@jkknorr fixed in v1.11.0
