### ISSUE TITLE
Unable to set a custom parent for a monitor

### ISSUE THREAD

**Issue by ghost** [F5Networks/terraform-provider-bigip#45]
Hi,

Seems I am unable to set a custom parent for a monitor. I get the following error:

    bigip_ltm_monitor.MON_HTTP_DP_EVAL_CHILD: parent must be one of /Common/http, /Common/https, /Common/icmp, /Common/gateway-icmp, /Common/tcp-half-open,  or /Common/tcp

Can this restriction be relaxed?

Regards,

Dan

**Comment by scshitole** [comment]
@dpeachey can you please give the example TF so I can test and fix it?

**Comment by scshitole** [comment]
@dpeachey  it is tied to the API you cannot have custom parent only these are possible
![image](https://user-images.githubusercontent.com/13858248/52820282-6d48ec00-3060-11e9-89f2-93a1cd7c3cbd.png)
![image](https://user-images.githubusercontent.com/13858248/52820302-7b970800-3060-11e9-9cec-dd3359185724.png)

**Comment by soumik612** [comment]
@scshitole , 
What we basically need is,
1. Creating a custom Monitor "HC4_HTTP_EVAL_PARENT", which inherits parameters from a default monitor, say "http".
2. Creating custom monitor "HC4_HTTP_EVAL", which inherits parameters from HM "A-PARENT".

I have added the API calls below for your reference. 

**Parent - "HC4_HTTP_EVAL_PARENT"** :
{"manualResume" : "disabled","adaptiveLimit" : 200,"name" : "HC4_HTTP_EVAL_PARENT","defaultsFrom" : "/Common/http","upInterval" : 0,"kind" : "tm:ltm:monitor:http:httpstate","ipDscp" : 0,"generation" : 0,"adaptiveDivergenceValue" : 25,"adaptive" : "disabled","adaptiveDivergenceType" : "relative","timeout" : 16,"interval" : 5,"destination" : "*:*","transparent" : "disabled","reverse" : "disabled","timeUntilUp" : 60,"description" : "Custom Parent Monitor","send" : "GET /\\r\\n","fullPath" : "HC4_HTTP_EVAL_PARENT"}

**Child - "HC4_HTTP_EVAL"** :

{"generation" : 0,"adaptiveSamplingTimespan" : 300,"fullPath" : "HC4_HTTP_EVAL","send" : "GET / HTTP/1.1\\r\\nHost: test\\r\\nConnection: Close\\r\\n\\r\\n","timeout" : 16,"name" : "HC4_HTTP_EVAL","adaptive" : "disabled","ipDscp" : 0,"recv" : "HTTP/1.1 200 OK","adaptiveLimit" : 200,"destination" : "*:*","reverse" : "disabled","timeUntilUp" : 0,"transparent" : "disabled","interval" : 5,"upInterval" : 0,"manualResume" : "disabled","defaultsFrom" : "/Common/HC4_HTTP_EVAL_PARENT"}

**Comment by soumik612** [comment]
@scshitole , 
The issue still persists.  I tried using both parameter "defaults_from" and "parent". However TF overrides/ignores the "default_from" parameters.

Example resource config:

resource "bigip_ltm_monitor" "MON_HTTP_PARENT" {
  name          = "/Common/MON_HTTP_PARENT"
  parent        = "/Common/http"
  send          = "GET /\r\n"
  reverse       = "disabled"
  interval      = 5
}

resource "bigip_ltm_monitor" "MON_TEST" {
  name              = "/Common/MON_TEST_HTTP"
  defaults_from     = "${bigip_ltm_monitor.MON_HTTP_PARENT.name}"
  parent            = "/Common/http"
  send              = "GET /\\r\\n"
  receive           = ""
  destination       = "*:8008"
  reverse           = "disabled"
}

**Comment by RavinderReddyF5** [comment]
closing this issue, please reopen new issue if anything needs attention
