### ISSUE TITLE
 Error: HTTP 401 :: {"code":401,"message":"Authorization failed: no user authentication header or token detected." }

### ISSUE THREAD

**Issue by Vittitow** [F5Networks/terraform-provider-bigip#468]
### Environment

 * TMOS/Bigip Version: BIG-IP 14.1.4 Build 0.0.11 Final
 * Terraform Version: 0.13.3
 * Terraform bigip provider Version: 1.8.0

### Summary

We have a large amount of state managed via terraform in our f5 bigip; close to a thousand resources. As our state has grown we've been seeing intermittent failures to generate plans. When refreshing state an error is sometimes thrown that is always a 401 unauthorized. However, authentication is occurring because it's able to refresh the state of many of the resources prior to it failing. Additionally, when running the same exact code with only ~100 resources the plan always succeeds and we never see unauthorized errors.

### Expected Behavior
Able to generate plan/refresh state successfully.

### Actual Behavior
Plans intermittently fail/succeed depending on how long it takes for the plan to refresh state. Failure responses look like the following:
```
Error: HTTP 401 :: {"code":401,"message":"Authorization failed: no user authentication header or token detected. Uri:http://localhost:8100/mgmt/tm/ltm/monitor/tcp-half-open Referrer:XX.XXX.XX.XXX Sender:XX.XXX.XX.XXX","referer":"XX.XXX.XX.XXX","restOperationId":100730102,"kind":":resterrorresponse"}

Error: HTTP 401 :: {"code":401,"message":"Authorization failed: no user authentication header or token detected. Uri:http://localhost:8100/mgmt/tm/ltm/monitor/gateway-icmp Referrer:XX.XXX.XX.XXX Sender:XX.XXX.XX.XXX","referer":"XX.XXX.XX.XXX","restOperationId":100571657,"kind":":resterrorresponse"}

Error: HTTP 401 :: {"code":401,"message":"Authorization failed: no user authentication header or token detected. Uri:http://localhost:8100/mgmt/tm/ltm/monitor/ftp Referrer:XX.XXX.XX.XXX Sender:XX.XXX.XX.XXX","referer":"XX.XXX.XX.XXX","restOperationId":100559097,"kind":":resterrorresponse"}

Error: HTTP 401 :: {"code":401,"message":"Authorization failed: no user authentication header or token detected. Uri:http://localhost:8100/mgmt/tm/ltm/monitor/tcp Referrer:XX.XXX.XX.XXX Sender:XX.XXX.XX.XXX","referer":"XX.XXX.XX.XXX","restOperationId":100102283,"kind":":resterrorresponse"}

Error: HTTP 401 :: {"code":401,"message":"Authorization failed: no user authentication header or token detected. Uri:http://localhost:8100/mgmt/tm/ltm/monitor/udp Referrer:XX.XXX.XX.XXX Sender:XX.XXX.XX.XXX","referer":"XX.XXX.XX.XXX","restOperationId":100112423,"kind":":resterrorresponse"}

Error: HTTP 401 :: {"code":401,"message":"Authorization failed: no user authentication header or token detected. Uri:http://localhost:8100/mgmt/tm/ltm/monitor/udp Referrer:XX.XXX.XX.XXX Sender:XX.XXX.XX.XXX","referer":"XX.XXX.XX.XXX","restOperationId":100104992,"kind":":resterrorresponse"}
```

**Comment by Vittitow** [comment]
So I'm going to close this issue even though I just opened it... 

I found the optional `token_auth` flag for the provider and when setting it to true our plans generate just fine and quicker than before. Not sure when that was introduced but it had been working previously without that flag for several months.

**Comment by tizianorosato-gr** [comment]
I'm having similar issues.
My environment is:
F5 BigIP ver 14.1.4 0.0.11
Terraform Enterprise 0.12
bigip provider 1.8.0

a local admin user with full access.

I'm using token_auth set to true as suggested.
an extract from main.tf:

provider "bigip" {
  address = "bigip"
  username = "myadmin"
  password   = "mypassword
  login_ref  = "tmos"
  token_auth = true
}

resource "bigip_as3" "Tenant1" {
  as3_json = file("./AS3/Tenant1.json")
}
 

Randomly I can see a successful "terraform plan"
But then any other terraform apply will fail with below message:

Error: HTTP 401 :: {"code":401,"message":"Authentication failed.","referer":"172.28.3.1","restOperationId":6394286,"kind":":resterrorresponse"}


restjavad.0.log show below messages:

[WARNING][6240][18 May 2021 09:51:48 UTC][RestOperationIdentifier] Failed to validate Authentication failed.
[I][6241][18 May 2021 09:51:50 UTC][8100/shared/authn/login AuthnWorker] User XXXX failed to login from XXXX using the tmos authentication provider
[WARNING][6244][18 May 2021 09:51:59 UTC][RestOperationIdentifier] Failed to validate Authentication failed.

**Comment by tizianorosato-gr** [comment]
Tried to use the more recent bigip provider 1.9.0 but no difference in result.

**Comment by nmenant** [comment]
Hi,

it will be easier for us to track your issue with a new issue. Would you mind opening a new issue wrt this ? 

Another question: If you communicate heavily with the BIG-IP API Control plane, it is recommended to increase memory allocation to the control plane: https://support.f5.com/csp/article/K26427018

Depending on your platform, assigning 512 to 1024 extra memory can help

``` 
Log in to tmsh by entering the following command:
tmsh

To view the current configured extra system memory, enter the following command:
list sys db provision.extramb all-properties

Output appears similar to the following:

sys db provision.extramb {
    default-value "0"
    scf-config "true"
    value "0"
    value-range "integer min:0 max:8192"
}

Note The previous example outputs the value of 0, meaning that no additional memory is allocated to the Management system beyond the provisioned setting.

To modify the provisioned memory value, use the following command syntax:
modify  /sys db provision.extramb value <numeric value>

Note: <numeric value> is the number of MB to additionally allocate to the host Management system.

Save the configuration change by entering the following command:
save /sys config partitions all
``` 

Be aware that it can be disruptive to traffic so use it carefully and during a maintenance window
