### ISSUE TITLE
"code":401,"message":"Authorization failed: no user authentication header or token detected.

### ISSUE THREAD

**Issue by qsoltys** [F5Networks/terraform-provider-bigip#469]
### Environment

 * TMOS/Bigip Version: BIG-IP 15.1.2.1 Build 0.0.10 Point Release 1
 * Terraform Version: v0.13.5
 * Terraform bigip provider Version: 1.17

### Summary

Many runs ends with
`Error: Error updating json  X: HTTP 401 :: {"code":401,"message":"Authorization failed: no user authentication header or token detected. Uri:http://localhost:8100/mgmt/shared/appsvcs/task/1a7497d1-bdf5-4dbd-bda5-686d13bc1beb Referrer:172.16.28.95 Sender:172.16.28.95","referer":"172.16.28.95","restOperationId":32036553,"kind":":resterrorresponse"}
  on .terraform/modules/tenant_X_dmz_2/main.tf line 1, in resource "bigip_as3" "tenant":
   1: resource "bigip_as3" "tenant" {`

but after start pipeline again pass correctly. 

provider configuration below:
`terraform {
  required_providers {
    bigip = {
      source  = "F5Networks/bigip"
      version = "1.7.0"
    }
  }
}

provider "bigip" {
  alias    = "env"
  address  = var.f5-address
  username = var.f5_user
  password = var.f5_password
}
`
Terraform debug log

`2021-04-08T08:24:15.810Z [DEBUG] plugin.terraform-provider-bigip_v1.7.0: 2021/04/08 08:24:15 [DEBUG]Sucessfully Created Application with ID  = ca6b5a7b-fd23-4119-aa24-8ff30531f2d9
2021-04-08T08:24:15.810Z [DEBUG] plugin.terraform-provider-bigip_v1.7.0: 2021/04/08 08:24:15 [INFO] Reading As3 config
2021-04-08T08:24:15.810Z [DEBUG] plugin.terraform-provider-bigip_v1.7.0: 2021/04/08 08:24:15 [DEBUG] Tenants in AS3 get call : X
2021/04/08 08:24:20 [DEBUG] module.tenant_X_dmz_2.bigip_as3.tenant[0]: apply errored, but we're indicating that via the Error pointer rather than returning it: Error updating json  X: HTTP 401 :: {"code":401,"message":"Authorization failed: no user authentication header or token detected. Uri:http://localhost:8100/mgmt/shared/appsvcs/task/d5d7e275-4eaa-4078-b6b8-bbabca31aaa7 Referrer:172.16.28.95 Sender:172.16.28.95","referer":"172.16.28.95","restOperationId":32052326,"kind":":resterrorresponse"}
2021/04/08 08:24:20 [ERROR] eval: *terraform.EvalApplyPost, err: Error updating json  X: HTTP 401 :: {"code":401,"message":"Authorization failed: no user authentication header or token detected. Uri:http://localhost:8100/mgmt/shared/appsvcs/task/d5d7e275-4eaa-4078-b6b8-bbabca31aaa7 Referrer:172.16.28.95 Sender:172.16.28.95","referer":"172.16.28.95","restOperationId":32052326,"kind":":resterrorresponse"}
2021/04/08 08:24:20 [ERROR] eval: *terraform.EvalSequence, err: Error updating json  X: HTTP 401 :: {"code":401,"message":"Authorization failed: no user authentication header or token detected. Uri:http://localhost:8100/mgmt/shared/appsvcs/task/d5d7e275-4eaa-4078-b6b8-bbabca31aaa7 Referrer:172.16.28.95 Sender:172.16.28.95","referer":"172.16.28.95","restOperationId":32052326,"kind":":resterrorresponse"}
module.tenant_X_dmz.bigip_as3.tenant[0]: Still modifying... [id=X, 40s elapsed]`

### Expected Behavior
No authorization problem with correct username / password

### Actual Behavior
authorization problem with correct username / password

**Comment by nmenant** [comment]
I can't reproduce this issue. coud you provide some more information: 
- your AS3 declaration (please obfuscate any sensitive data)
- the role of the user used with terraform (manager, admin, something else ? )
-

**Comment by qsoltys** [comment]
bellow example of AS3 plan presented by terraform, user with Administator role for all partitions.

> ~ resource "bigip_as3" "dns" {
        application_list = "brand-id-example.com"
      ~ as3_json         = jsonencode(
          ~ {
                action      = "deploy"
                class       = "AS3"
              ~ declaration = {
                    class         = "ADC"
                  + controls      = {
                      + trace = true
                    }
                    id            = "s-0000dummy"
                    label         = "s-0000dummy"
                    remark        = "s-0000dummy"
                  ~ s-0000dummy   = {
                      - brand-id-example.com = {
                          - brand-id-example.com      = {
                              - class              = "GSLB_Domain"
                              - domainName         = "brand-id-example.com"
                              - poolLbMode         = "round-robin"
                              - pools              = [
                                  - {
                                      - use = "brand-id-example.com-pool"
                                    },
                                ]
                              - resourceRecordType = "A"
                            }
                          - brand-id-example.com-pool = {
                              - bpsLimitEnabled         = false
                              - class                   = "GSLB_Pool"
                              - connectionsLimitEnabled = false
                              - enabled                 = true
                              - fallbackIP              = "0.0.0.0"
                              - lbModeAlternate         = "round-robin"
                              - lbModeFallback          = "return-to-dns"
                              - manualResumeEnabled     = false
                              - maxAnswersReturned      = 1
                              - members                 = [
                                  - {
                                      - ratio         = 10
                                      - server        = {
                                          - bigip = "/Common/dmz-f5-uat-r1"
                                        }
                                      - virtualServer = "/brand-id/example.com/example.com"
                                    },
                                ]
                              - ppsLimitEnabled         = false
                              - resourceRecordType      = "A"
                              - verifyMemberEnabled     = true
                            }
                          - class                             = "Application"
                        } -> null
                        class                        = "Tenant"
                      + brand-id-r1                    = {
                          + brand-id-example.com      = {
                              + class              = "GSLB_Domain"
                              + domainName         = "brand-id-example.com"
                              + poolLbMode         = "round-robin"
                              + pools              = [
                                  + {
                                      + use = "brand-id-example.com-pool"
                                    },
                                ]
                              + resourceRecordType = "A"
                            }
                          + brand-id-example.com-pool = {
                              + bpsLimitEnabled         = false
                              + class                   = "GSLB_Pool"
                              + connectionsLimitEnabled = false
                              + enabled                 = true
                              + fallbackIP              = "0.0.0.0"
                              + lbModeAlternate         = "round-robin"
                              + lbModeFallback          = "return-to-dns"
                              + manualResumeEnabled     = false
                              + maxAnswersReturned      = 1
                              + members                 = [
                                  + {
                                      + ratio         = 10
                                      + server        = {
                                          + bigip = "/Common/dmz-f5-uat-r1"
                                        }
                                      + virtualServer = "/brand-id/example.com/example.com"
                                    },
                                ]
                              + ppsLimitEnabled         = false
                              + resourceRecordType      = "A"
                              + verifyMemberEnabled     = true
                            }
                          + class                             = "Application"
                        }
                    }
                    schemaVersion = "3.0.0"
                }
                persist     = true
            }
        )
        id               = "s-0000dummy"
        tenant_list      = "s-0000dummy"
    }

and the error
> Error: Error updating json  s-0000dummy: HTTP 401 :: {"code":401,"message":"Authorization failed: no user authentication header or token detected. Uri:http://localhost:8100/mgmt/shared/appsvcs/task/bf5ff03b-9d5f-4489-96c2-48b5ec5f5cb8 Referrer:172.16.28.91 Sender:172.16.28.91","referer":"172.16.28.91","restOperationId":22561928,"kind":":resterrorresponse"}
  on .terraform/modules/tenant_sandbox_dns_f5_ew1/main.tf line 1, in resource "bigip_as3" "dns":
   1: resource "bigip_as3" "dns" {

**Comment by papineni87** [comment]
@qsoltys  just to confirm the credentials are working , can you try below curl command and see if it is working

curl -k https://$bigip_address/mgmt/shared/appsvcs/info -u $user:$password


I wanted to try on above as3 resource, but i am getting json issue, can just provide as3 json which i can try ?

**Comment by qsoltys** [comment]
After upgrade TMOS to 15.1.3 this problem doesn't show again.
