### ISSUE TITLE
Please create bigip_ltm_profile_ftp to allow Custom FTP Profiles

### ISSUE THREAD

**Issue by oniGino** [F5Networks/terraform-provider-bigip#480]
### Is your feature request related to a problem? Please describe.
Want to Create LTM FTP Profile

### Describe the solution you'd like
 bigip_ltm_profile_ftp {} function support
### Describe alternatives you've considered
create outside of terraform

**Comment by nmenant** [comment]
tracking this request internally with INFRAANO-337

**Comment by RavinderReddyF5** [comment]
@oniGino fixed in v1.11.0
