### ISSUE TITLE
updating FAST template does not trigger an update

### ISSUE THREAD

**Issue by chen23** [F5Networks/terraform-provider-bigip#492]
### Environment

 * TMOS/Bigip Version: 15.1.2.1
 * Terraform Version: 0.14.9
 * Terraform bigip provider Version: 1.9.0

### Summary

When you update the zip file used by "bigip_fast_template" it does not trigger an update

### Steps To Reproduce

use "bigip_fast_template"

update zip file

run apply again

### Expected Behavior

should trigger a change

### Actual Behavior

does not trigger a change

**Comment by nmenant** [comment]
Tracking this with INFRAANO-362

**Comment by RavinderReddyF5** [comment]
@chen23 fixed in v1.10.0, please check and open new issue if u see any problem.
