### ISSUE TITLE
Inconsistent documentation locations, docs vs website/docs

### ISSUE THREAD

**Issue by AliAllomani** [F5Networks/terraform-provider-bigip#515]
The repository has 2 different directories for documentation

* docs/
* website/docs

some resources are updated in one and not the other

for example,

c3d params for bigip_ltm_profile_server_ssl  are mentioned in

https://github.com/F5Networks/terraform-provider-bigip/blob/v1.9.0/docs/resources/bigip_ltm_profile_server_ssl.md

but not

https://github.com/F5Networks/terraform-provider-bigip/blob/v1.9.0/website/docs/r/bigip_ltm_profile_server_ssl.html.markdown

and don’t appear in terraform registry documentation for the provider

https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_ltm_profile_server_ssl

**Comment by RavinderReddyF5** [comment]
Tracking with : INFRAANO-409

**Comment by RavinderReddyF5** [comment]
@AliAllomani fixed in v1.10.0, please check and open new issue if u see any problem.

**Comment by AliAllomani** [comment]
@RavinderReddyF5 Thanks for the update, would it be possible to advise what was the fix for this ?

from what i can see, the mentioned missing params has been added to `website/docs/r/bigip_ltm_profile_server_ssl.html.markdown`

but i think there should be more long-term solution for this, as having 2 separately managed directories makes confusion to the contributors, and there might be several resources that were updated in one location but not the other.

for example, all the data sources exist in `/website/docs` but not `/docs`

ref. : https://www.terraform.io/docs/registry/providers/docs.html#migrating-legacy-providers-docs

**Comment by RavinderReddyF5** [comment]
@AliAllomani For Now Hashicorp supporting documentation from both places, and i think it is picking up documentation from `website` directory if it exists, we are pushing all documentation into `website/docs`. we make sure all reflected in `docs` folder also.
as you mentioned if there are any discrepancy we will try to address the same. we will work on retiring one of directory in upcoming releases.
