### ISSUE TITLE
terraform destroy fails while trying to destroy big_ltm_virtual_address resource

### ISSUE THREAD

**Issue by rsawant23** [F5Networks/terraform-provider-bigip#519]
### Environment

 * TMOS/Bigip Version: BIG-IP v15.1.0.3 (Build 0.0.12)
 * Terraform Version: v0.13
 * Terraform bigip provider Version: v1.8.0

### Summary

After working with @papineni87 on [Issue#432](https://github.com/F5Networks/terraform-provider-bigip/issues/432) I was able to successfully deploy virtual servers in conjunction with virtual address. 

Using the same code, I now get an error while running the destroy plan with the error message:
`
HTTP 404 :: {"code":404,"message":"01020036:3: The requested Virtual Address (/Common/1.1.1.1) was not found.","errorStack":[],"apiError":3} 
`

I am guessing this is because virtual addresses are linked to the virtual server on the f5 and destroying the virtual server also destroys the virtual address linked to it by default and hence when terraform tries to destroy the virtual address seperately it is unable to find it

Terraform Code:
`
resource "bigip_ltm_virtual_address" "vs_va" {
name = "/Common/1.1.1.1"
advertize_route = "selective"
  icmp_echo       = "enabled"
}

resource "bigip_ltm_virtual_server" "http" {
name = "/Common/terraform_vs_http"
destination = bigip_ltm_virtual_address.vs_va.name
port = 80
pool = bigip_ltm_pool.pool.name
client_profiles = [bigip_ltm_profile_client_ssl.clientssl_profile.name]
depends_on                 = [bigip_ltm_virtual_address.address] //I added this to create an extrinsic dependency on the virtual_address resource. But the destroy still fails with to without this line
}
`

### Steps To Reproduce

1. terraform apply the above  resource blocks

2. run a terraform destroy

### Expected Behavior
Terraform should destroy all resources without any error.

### Actual Behavior
Gives an error

**Comment by papineni87** [comment]
Tracking with Infraano-429

**Comment by papineni87** [comment]
@rsawant23 Added a check before destroy and make sure terraform destroys the virtual address only if it exists.

Can you clone the latest devel branch and see the issue is fixed or not ?

**Comment by trinaths** [comment]
@rsawant23 - Please share your findings with latest devel branch.

**Comment by ghalevy** [comment]
I'm experiencing the same issue - will try with devel branch and report back.
