### ISSUE TITLE
bigip_ltm_node does not show difference after monitor modification 

### ISSUE THREAD

**Issue by andreivnst** [F5Networks/terraform-provider-bigip#526]
### Environment

 * TMOS/Bigip Version: BIG-IP 15.1.3 Build 0.0.11 Final
 * Terraform Version: Terraform v0.14.2
 * Terraform bigip provider Version: 1.6.0

### Summary

Bigip terraform provider does not see a difference for the deployed bigip_ltm_node resource after it has been manually modified (in this case for Health Monitor modification).

### Steps To Reproduce

1. Deploy a bigip_ltm_node resource without a health monitor setup (as it is an optional resource and it sets the Default Monitor setup in BIGIP, in my case being /Common/icmp).

ex.

resource "bigip_ltm_node" "nodes" {
  for_each = {for node in var.nodes : node.fqdn => node}

  name = "/${var.partition}/${each.value.fqdn}"
  address = "${each.value.ip}%${var.routing_domain}"
  description = local.description
}

2. Modify the health check as anything but the one already setup as default

3. Run terraform plan again in the working workspace and sense no difference whatsoever

No changes. Infrastructure is up-to-date.

even though in the terraform pg database backend the health check is known to be the icmp one:

{
          ""index_key"": ""*****"",
          ""schema_version"": 0,
          ""attributes"": {
            ""address"": ""*****"",
            ""connection_limit"": 0,
            ""description"": ""by Terraform"",
            ""dynamic_ratio"": 1,
            ""fqdn"": [],
            ""id"": ""*****"",
            **""monitor"": ""/Common/icmp"",**
            ""name"": ""*****"",
            ""rate_limit"": ""disabled"",
            ""ratio"": 1,
            ""state"": null
          }

### Expected Behavior

Terraform provider sees the modification and outputs as a difference

### Actual Behavior
Terraform does not show the difference. This bug leads to service unavailability in case of manual modifications on terraform deployed objects.

**Comment by trinaths** [comment]
@andreivnst - I see no issues with provider version 1.10.0. Please try the same manifest with BIGIP provider 1.10.0 and share your findings.
