### ISSUE TITLE
bigip_fast_application fails with null exception error.

### ISSUE THREAD

**Issue by s-archer** [F5Networks/terraform-provider-bigip#527]
### Environment

 * TMOS/Bigip Version: 15.1.2.1
 * Terraform Version: Tested 0.13.7 and 1.0.1
 * Terraform bigip provider Version: 1.10.0

### Summary

Create bigip_fast_application resource fails with error: 

> Error: HTTP 400 :: {"code":400,"message":"request failed with null exception","referer":"<my ip removed>","restOperationId":6556319,"kind":":resterrorresponse"}
> │ 
> │   with bigip_fast_application.post_app,
> │   on main.tf line 46, in resource "bigip_fast_application" "post_app":
> │   46: resource "bigip_fast_application" "post_app" {

Also, the documentation states that the 'template' argument is optional, but it is not.

### Steps To Reproduce

Steps to reproduce the behaviour:

Terraform resource config:

```
resource "bigip_fast_application" "post_app" {
  template         = "examples/simple_http"
  fast_json        = file("${path.module}/fast.json")
}
```

fast.json :

```
{
    "name": "examples/simple_http",
    "parameters": {
        "application_name": "App01",
        "server_addresses": [
            "10.2.1.201",
            "10.2.1.202"
        ],
        "server_port": 80,
        "tenant_name": "terraformFAST",
        "virtual_address": "10.2.1.101",
        "virtual_port": 80
    }
}
```

Partial Terraform debug log:

> 2021-07-05T20:04:37.550+0100 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/f5networks/bigip/1.10.0/darwin_amd64/terraform-provider-bigip_v1.10.0 args=[.terraform/providers/registry.terraform.io/f5networks/bigip/1.10.0/darwin_amd64/terraform-provider-bigip_v1.10.0]
> 2021-07-05T20:04:37.553+0100 [DEBUG] provider: plugin started: path=.terraform/providers/registry.terraform.io/f5networks/bigip/1.10.0/darwin_amd64/terraform-provider-bigip_v1.10.0 pid=65938
> 2021-07-05T20:04:37.554+0100 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/f5networks/bigip/1.10.0/darwin_amd64/terraform-provider-bigip_v1.10.0
> 2021-07-05T20:04:37.570+0100 [INFO]  provider.terraform-provider-bigip_v1.10.0: configuring server automatic mTLS: timestamp=2021-07-05T20:04:37.569+0100
> 2021-07-05T20:04:37.609+0100 [DEBUG] provider.terraform-provider-bigip_v1.10.0: plugin address: address=/var/folders/kw/pv1mmzqn49d8chjgfr3v0fkrbkvc6k/T/plugin911984289 network=unix timestamp=2021-07-05T20:04:37.609+0100
> 2021-07-05T20:04:37.609+0100 [DEBUG] provider: using plugin: version=5
> 2021-07-05T20:04:37.661+0100 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unimplemented desc = unknown service plugin.GRPCStdio"
> 2021-07-05T20:04:37.663+0100 [DEBUG] No provider meta schema returned
> 2021-07-05T20:04:37.671+0100 [WARN]  ValidateProviderConfig from "provider[\"registry.terraform.io/f5networks/bigip\"]" changed the config value, but that value is unused
> 2021-07-05T20:04:37.671+0100 [DEBUG] provider.terraform-provider-bigip_v1.10.0: 2021/07/05 20:04:37 [INFO] Initializing BigIP connection
> 2021-07-05T20:04:37.905+0100 [WARN]  Provider "registry.terraform.io/f5networks/bigip" produced an invalid plan for bigip_fast_application.post_app, but we are tolerating it because it is using the legacy plugin SDK.
>     The following problems may be the cause of any confusing errors from downstream operations:
>       - .fast_json: planned value cty.StringVal("{\"name\":\"examples/simple_http\",\"parameters\":{\"application_name\":\"App01\",\"server_addresses\":[\"10.2.1.201\",\"10.2.1.202\"],\"server_port\":80,\"tenant_name\":\"terraformFAST\",\"virtual_address\":\"10.2.1.101\",\"virtual_port\":80}}") does not match config value cty.StringVal("{\n    \"name\": \"examples/simple_http\",\n    \"parameters\": {\n        \"application_name\": \"App01\",\n        \"server_addresses\": [\n            \"10.2.1.201\",\n            \"10.2.1.202\"\n        ],\n        \"server_port\": 80,\n        \"tenant_name\": \"terraformFAST\",\n        \"virtual_address\": \"10.2.1.101\",\n        \"virtual_port\": 80\n    }\n}")
> bigip_fast_application.post_app: Creating...
> 2021-07-05T20:04:37.905+0100 [INFO]  Starting apply for bigip_fast_application.post_app
> 2021-07-05T20:04:37.905+0100 [DEBUG] bigip_fast_application.post_app: applying the planned Create change
> 2021-07-05T20:04:37.906+0100 [DEBUG] provider.terraform-provider-bigip_v1.10.0: 2021/07/05 20:04:37 [INFO] Creating FastApp config
> ╷
> │ Error: HTTP 400 :: {"code":400,"message":"request failed with null exception","referer":"90.255.235.127","restOperationId":6562504,"kind":":resterrorresponse"}
> │ 
> │   with bigip_fast_application.post_app,
> │   on main.tf line 46, in resource "bigip_fast_application" "post_app":
> │   46: resource "bigip_fast_application" "post_app" {
> │ 
> ╵
> 2021-07-05T20:04:38.050+0100 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/f5networks/bigip/1.10.0/darwin_amd64/terraform-provider-bigip_v1.10.0 pid=65938
> 2021-07-05T20:04:38.050+0100 [DEBUG] provider: plugin exited

### Expected Behavior
I expect 202 response and for it to deploy successfully.  Using the same fast.json with Terraform null_resource (curl) works.

```
resource "null_resource" "fast_app" {
  provisioner "local-exec" {
    command = "curl -k -u ${data.terraform_remote_state.aws_demo.outputs.f5_username}:${data.terraform_remote_state.aws_demo.outputs.f5_password} -X POST -H 'Content-type: application/json' --data-binary \"@${path.module}/fast.json\" ${data.terraform_remote_state.aws_demo.outputs.f5_ui}/mgmt/shared/fast/applications"
  }
}
```

### Actual Behaviour

There is a null error response.  I collected the following logs from the BIG-IP:

/var/log/restnoded/restnoded.log : 

> Mon, 05 Jul 2021 18:50:38 GMT - fine: FAST Worker [71]: received request method=Post; path=/shared/fast/applications; userAgent=
> Mon, 05 Jul 2021 18:50:38 GMT - info: FAST Worker [71]: Entering gathering config data
> Mon, 05 Jul 2021 18:50:38 GMT - info: FAST Worker [71]: Exiting gathering config data
> Mon, 05 Jul 2021 18:50:38 GMT - fine: FAST Worker [71]: gathering config data took 0ms to complete
> Mon, 05 Jul 2021 18:50:38 GMT - info: FAST Worker [71]: Entering fetching template set data for examples
> Mon, 05 Jul 2021 18:50:38 GMT - info: FAST Worker [71]: Exiting fetching template set data for examples
> Mon, 05 Jul 2021 18:50:38 GMT - fine: FAST Worker [71]: fetching template set data for examples took 1ms to complete
> Mon, 05 Jul 2021 18:50:38 GMT - info: FAST Worker [71]: Entering loading template (examples/simple_http)
> Mon, 05 Jul 2021 18:50:38 GMT - info: FAST Worker [71]: Exiting loading template (examples/simple_http)
> Mon, 05 Jul 2021 18:50:38 GMT - fine: FAST Worker [71]: loading template (examples/simple_http) took 0ms to complete
> Mon, 05 Jul 2021 18:50:38 GMT - info: FAST Worker [71]: Entering rendering template (examples/simple_http)
> Mon, 05 Jul 2021 18:50:38 GMT - info: FAST Worker [71]: Exiting rendering template (examples/simple_http)
> Mon, 05 Jul 2021 18:50:38 GMT - fine: FAST Worker [71]: rendering template (examples/simple_http) took 0ms to complete
> Mon, 05 Jul 2021 18:50:38 GMT - info: FAST Worker [71]: sending response after 4ms
> {
>   "method": "Post",
>   "path": "/shared/fast/applications",
>   "status": 400
> }
> Mon, 05 Jul 2021 18:50:43 GMT - finest: socket 255 closed

/var/log/restjavad.0.log : 

> [WARNING][766][05 Jul 2021 18:45:05 UTC][RestOperation] Unable to generate error body for POST http://localhost:8100/mgmt/shared/fast/applications 400: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 2049 path $.message

**Comment by trinaths** [comment]
Created INFRAANO-436 for internal tracking.

**Comment by papineni87** [comment]
@s-archer  can you try below fast.json, i am able to deploy it successfully.

```
{
    
        "application_name": "App01",
        "server_addresses": [
            "10.2.1.201",
            "10.2.1.202"
        ],
        "server_port": 80,
        "tenant_name": "terraformFAST",
        "virtual_address": "10.2.1.101",
        "virtual_port": 80
}

```

As per the documentation, we have to provide following variables in json

https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_fast_application

```
Argument Reference
fast_json - (Required) Path/Filename of Declarative FAST JSON which is a json file used with builtin file function

template - (Optional) Name of installed FAST template used to create FAST application. This parameter is required when creating new resource.

tenant - (Optional) A FAST tenant name on which you want to manage application.

application - (Optional) A FAST application name.
```

we don't need to mention name and parameter in fast application json
