### ISSUE TITLE
bigip_ltm_virtual_server vlans_disabled documented but not implemented

### ISSUE THREAD

**Issue by Otimun** [F5Networks/terraform-provider-bigip#533]
### Environment

 * TMOS/Bigip Version: 15.1.3
 * Terraform Version: v1.0.2
 * Terraform bigip provider Version: v1.10.0

### Summary
When trying to use vlans_disabled on bigip_ltm_virtual_server it doesnt seem to exist. 

│ Error: Extraneous JSON object property
│
│   on test_terraform.tf.json line 13488, in resource.bigip_ltm_virtual_server."name_of_virtual_server":
│ 13488:         "vlans_disabled": "true"
│
│ No argument or block type is named "vlans_disabled".

Comand doesn't show the property implemented:
terraform providers schema -json | jq ".provider_schemas.\"registry.terraform.io/f5networks/bigip\".resource_schemas.bigip_ltm_virtual_server"

description on website https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_ltm_virtual_server:

vlans_disabled - (Optional Bool) Disables the virtual server on the VLANs specified by the VLANs option.

**Comment by trinaths** [comment]
Created INFRAANO-458 for internal PM tracking

**Comment by RavinderReddyF5** [comment]
fixed in v1.12.2
