### ISSUE TITLE
bigip_ltm_policy datasource

### ISSUE THREAD

**Issue by andreivnst** [F5Networks/terraform-provider-bigip#547]
### Is your feature request related to a problem? Please describe.
A datasource for bigip_ltm_policy. In order to setup an existing policy on a virtual server you need a datasource to read it from F5

### Describe the solution you'd like
Create a datasource for bigip_ltm_policy that could be queried in order to set it up on one/multiple VSs

### Describe alternatives you've considered
no alternative found

### Additional context
In terraform bigip_ltm_virtual_server there is an input field(that by the way is not described in https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_ltm_virtual_server) called policies. This field requires a policy as an input (the policy you want to attach on VS). This works if the policy is created in the same workspace the VS is created (direct reference of it). But if you have a policy already created in F5 or a policy created in another workspace, you cannot do this due to the missing datasource, hence the opened issue.

**Comment by trinaths** [comment]
Created  INFRAANO-505 for internal tracking.
