### ISSUE TITLE
X-F5-Auth-Token expired. Requesting that a property be added to the provider that can specify a token timeout value.

### ISSUE THREAD

**Issue by josephjonko** [F5Networks/terraform-provider-bigip#55]
Resources that are provisioning prior to the use for BigIp resources takes longer than 20Minutes and by then the F5 token has already expired.

Error: Error applying plan:

2 error(s) occurred:

* module.web-farm.bigip_ltm_node.app_nodes[1]: 1 error(s) occurred:

* bigip_ltm_node.app_nodes.1: X-F5-Auth-Token has expired.
* module.web-farm.bigip_ltm_node.app_nodes[0]: 1 error(s) occurred:

* bigip_ltm_node.app_nodes.0: X-F5-Auth-Token has expired.

**Comment by KrithikaChidambaram** [comment]
Hi, closing this request now. 
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
