### ISSUE TITLE
BIG-IP terraform provider produces invalid plan

### ISSUE THREAD

**Issue by gwolfis** [F5Networks/terraform-provider-bigip#551]
This issue could hit the same problem:  (as3)provider produced inconsistent final plan #481 

### Environment

 * TMOS/Bigip Version: 16.1
 * Terraform Version: 0.13.5
 * Terraform bigip provider Version: 1.10.0

### Summary

Deployment of BIG-IP in AWS uses Terraform to automate the app services via AS3.
Since each tenant consists out of multiple applications the following approach is used:
1. POST/Deploy AS3 declaration with only tenant and include the app generic profiles, certs, irules, etc.
2. PATCH/Deploy a separate AS3 declaration for each application.

### Steps To Reproduce

Use the BIG-IP TF module to deploy tenant and application and watch the TF log.

### Actual Behavior
You will see:
2021/09/14 12:10:53 [WARN] Provider "registry.terraform.io/f5networks/bigip" produced an invalid plan for <tenant>, but we are tolerating it because it is using the legacy plugin SDK.
- The following problems may be the cause of any confusing errors from downstream operations <AS3.json omitted>

Same warning is repeated when the application gets created.

And than the log shows this error:
2021/09/14 12:14:05 [ERROR] eval: *terraform.EvalApplyPost, err: Provider produced inconsistent result after apply: When applying changes to <application>, provider "registry.terraform.io/f5networks/bigip" produced an unexpected new value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Expected Behavior
TF provider should not generate this bug.

**Comment by trinaths** [comment]
Created INFRAANO-515 for internal tracking.

**Comment by trinaths** [comment]
Created INFRAANO-624 for further investigation of this issue.

**Comment by apollocreed** [comment]
Hello,
I've the same issue but without AS3/DO. I use standard provider resources i.e. virtual_ip, virtual_server, monitor etc...

here is my terraform output after a terraform apply
~~~bash
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to bigip_ltm_pool_attachment.attach_node["node2"], provider
│ "provider[\"registry.terraform.io/f5networks/bigip\"]" produced an unexpected new value: Root resource was present, but
│ now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
~~~

To fix the problem I have to run the same command twice or more.
Seems to be a race condition or something like that

**Comment by RavinderReddyF5** [comment]
@apollocreed is it consistent? can you please help us with reproduction.

**Comment by RavinderReddyF5** [comment]
@gwolfis @apollocreed closing this issue, please open new issue if you have seen any issue from provider latest versions
