### ISSUE TITLE
Incorrect 'bigip_ltm_monitor' parent profile name validation

### ISSUE THREAD

**Issue by rsawant23** [F5Networks/terraform-provider-bigip#553]
### Environment

 * TMOS/Bigip Version: BIG-IP v15.1.0.3 (Build 0.0.12)
 * Terraform Version: 0.13.5
 * Terraform bigip provider Version: 1.11.1

### Summary

Get the following error when trying to create an ltm monitor with gateway_icmp as the parent profile

`Error: parent must be one of /Common/udp, /Common/postgresql, /Common/http, /Common/https, /Common/icmp, /Common/gateway-icmp, /Common/tcp-half-open, /Common/tcp, /Common/ftp`

The parent profile is actually gateway_icmp and not gateway-icmp

![Screen Shot 2021-09-21 at 3 08 18 PM](https://user-images.githubusercontent.com/56733745/134232686-7bf99046-c7fe-4725-bb26-8e49c175c189.png)

### Steps To Reproduce

1. Just create a big_ltm_monitor resource using the parent gateway-icmp
```
resource "bigip_ltm_monitor" "potential-provider-bug" {
  name        = "/Common/potential-bug"
  parent      = "/Common/gateway-icmp"
  timeout     = "16"
  interval    = "5"
  destination = "10.10.10.10:*"
}
```

Using gateway-icmp as the parent returns the following error

`Error: HTTP 400 :: {"code":400,"message":"01070043:3: Monitor /Common/potential-provider-bug parent not found.","errorStack":[],"apiError":3}`

**Comment by trinaths** [comment]
Created INFRAANO-553 for internal tracking.
