### ISSUE TITLE
name needs to be the same as the source when using bigip-fast-template resource

### ISSUE THREAD

**Issue by gwolfis** [F5Networks/terraform-provider-bigip#555]
Using the terraform resource bigip-fast-template it is noticed that the name of your template needs to match the name of the .zip file which is your resource.

### Environment

 * TMOS/Bigip Version: v16.0.1.1
 * Terraform Version: v0.14.11
 * Terraform bigip provider Version: v1.11

### Summary

It should not be mandatory to use the same template name as what is being the source. The source is a .zip file and when created from 'fast packageTemplateSet' the file creates its own name which is not always usefull as being the name for your template.

### Steps To Reproduce

1. Create an .mst file and .zip it.

2. use the bigip-fast-template resource to make TF install the .zip source on the BIG-IP.

3. toggle between using a random name first and then the the same name as the .zip resource when performing a terraform apply.

### Expected Behavior
You should be able to pick a random name which makes sense to the template and not being forced to use the same name as the .zip resource.

### Actual Behavior
A clear and concise description of what actually happens.
Please include any applicable error output.

When selecting a different name:

resource "bigip_fast_template" "tenant" {
  name     = "appB"
  source   = "appA.zip"
  md5_hash = filemd5("appA.zip")
}

---Terraform log---
NET-ML-00011666:Testing wolfis$ terraform apply --auto-approve
bigip_as3.log: Refreshing state... [id=Common]
bigip_fast_template.tenant: Creating...
bigip_as3.profiles: Creating...
bigip_as3.profiles: Still creating... [10s elapsed]

Error: Provider produced inconsistent result after apply

When applying changes to bigip_as3.profiles, provider
"registry.terraform.io/f5networks/bigip" produced an unexpected new value:
Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: error in creating FAST template set (appB): HTTP 404 :: {"code":404,"message":"/var/config/rest/downloads/appB.zip does not exist"}

  on main.tf line 29, in resource "bigip_fast_template" "tenant":
  29: resource "bigip_fast_template" "tenant" {

----

**Comment by trinaths** [comment]
Created INFRAANO-554 for internal tracking

**Comment by RavinderReddyF5** [comment]
@gwolfis fixed in v1.12.1
