### ISSUE TITLE
terraform provider plugin crashed when deploying AS3 via BIG-IQ with defaultRouteDomain property

### ISSUE THREAD

**Issue by nobiac0922** [F5Networks/terraform-provider-bigip#558]
### Environment

 * TMOS/Bigip Version: 13.1.3.6
 * Terraform Version: v1.0.7
 * Terraform bigip provider Version: v1.11.1
 * BIG-IQ version: 8.1

### Summary

Terraform plugin crashed when deploying AS3 declaration via BIG-IQ with defaultRouteDomain property set.  The AS3 deployment seems to be successful in BIG-IQ and config was deployed in BIG-IP. But due to the error, resource state is not there in terraform.

If I remove defaultRouteDomain property in my declaration it works fine via BIG-IQ. If I deploy the same AS3 declaration directly to BIG-IP with Route Domain set to 10, it works fine.

### Steps To Reproduce

resource "bigip_bigiq_as3"  "Sample01" {
     bigiq_address = var.bigiq_address
     bigiq_user = "admin"
     bigiq_password = var.bigiq_password
     as3_json = "${file("bigiq_as3.json")}"
}

AS3 Declaration
{
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.28.0",
        "id": "autogen_449936cc-682f-4c9b-891d-405289eab874",
        "label": "Sample01",
        "remark": "Simple HTTP application with RR pool",
        "target": {
            "address": "192.168.100.100"
        },
        "Sample01": {
            "class": "Tenant",
            "defaultRouteDomain": 10,
            "A1": {
                "class": "Application",
                "test-sample.com": {
                    "class": "Service_HTTP",
                    "virtualAddresses": [
                        "172.23.1.1"
                    ],
                    "pool": "web_pool"
                },
                "web_pool": {
                    "class": "Pool",
                    "monitors": [
                        "http"
                    ],
                    "members": [
                        {
                            "servicePort": 8080,
                            "serverAddresses": [
                                "172.23.2.1",
                                "172.23.2.2"
                            ]
                        }
                    ]
                }
            }
        }
    }
}

### Expected Behavior
The resource is created successfully with no errors.

### Actual Behavior
bigip_bigiq_as3.Sample01: Creating...
bigip_bigiq_as3.Sample01: Still creating... [10s elapsed]
bigip_bigiq_as3.Sample01: Still creating... [20s elapsed]
bigip_bigiq_as3.Sample01: Still creating... [30s elapsed]
╷
│ Error: Plugin did not respond
│ 
│   with bigip_bigiq_as3.Sample01,
│   on main.tf line 12, in resource "bigip_bigiq_as3" "Sample01":
│   12: resource "bigip_bigiq_as3"  "Sample01" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-bigip_v1.11.1 plugin:

panic: interface conversion: interface {} is float64, not map[string]interface {}

goroutine 49 [running]:
github.com/f5devcentral/go-bigip.(*BigIP).GetAs3Bigiq(0xc00013ea80, 0xc000036d00, 0xf, 0xc000036d10, 0x8, 0x1, 0xc00066e480, 0x2, 0x2)
        github.com/f5devcentral/go-bigip@v0.0.0-20210915090336-5089db0c53ef/bigiq.go:409 +0x1be2
github.com/F5Networks/terraform-provider-bigip/bigip.resourceBigiqAs3Read(0xc0003fe620, 0x1252900, 0x0, 0x2, 0x2)
        github.com/F5Networks/terraform-provider-bigip/bigip/resource_bigiq_as3.go:137 +0x609
github.com/F5Networks/terraform-provider-bigip/bigip.resourceBigiqAs3Create(0xc0003fe620, 0x1252900, 0x0, 0x0, 0x0)
        github.com/F5Networks/terraform-provider-bigip/bigip/resource_bigiq_as3.go:110 +0x554
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0004c5200, 0xc0000c3090, 0xc00052a3a0, 0x1252900, 0x0, 0x10d3d01, 0xc0004a8f08, 0xc0004e7050)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/resource.go:305 +0x365
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc0004c5580, 0xc0006218e0, 0xc0000c3090, 0xc00052a3a0, 0xc0004a8f50, 0xc00000e020, 0x10d5b00)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0000bcbb8, 0x1510060, 0xc0004e6480, 0xc00050c3c0, 0xc0000bcbb8, 0xc0004e6480, 0xc00056ba48)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/helper/plugin/grpc_provider.go:885 +0x882
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1207020, 0xc0000bcbb8, 0x1510060, 0xc0004e6480, 0xc00050c360, 0x0, 0x1510060, 0xc0004e6480, 0xc0004f5000, 0xec7)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000e6000, 0x151b640, 0xc0002da300, 0xc00067c000, 0xc000099770, 0x1d53840, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.23.0/server.go:995 +0x460
google.golang.org/grpc.(*Server).handleStream(0xc0000e6000, 0x151b640, 0xc0002da300, 0xc00067c000, 0x0)
        google.golang.org/grpc@v1.23.0/server.go:1275 +0xd3d
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000b6370, 0xc0000e6000, 0x151b640, 0xc0002da300, 0xc00067c000)
        google.golang.org/grpc@v1.23.0/server.go:710 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.23.0/server.go:708 +0xa1

Error: The terraform-provider-bigip_v1.11.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by anilvarmab** [comment]
I am having the same problem with the new version and had to change the version back to 1.10.0 where it works. 
Versions 1.11.0 and 1.11.1 both give me the same plugin crashed errors.

**Comment by nobiac0922** [comment]
> I am having the same problem with the new version and had to change the version back to 1.10.0 where it works. Versions 1.11.0 and 1.11.1 both give me the same plugin crashed errors.

@anilvarmab, I tried using version 1.10.0 but I'm still getting the plugin crashed errors. 

_Error: The terraform-provider-bigip_v1.10.0 plugin crashed!_

Which Terraform and BIG-IQ/BIG-IP versions are you using? Thank you.

**Comment by trinaths** [comment]
Created INFRAANO-557 for internal tracking.

**Comment by RavinderReddyF5** [comment]
fixed in v1.12.0. please reopen new issue if still issue seen
