### ISSUE TITLE
"Declaration is invalid" error when using multiple GSLB Server Devices on bigip_bigiq_as3

### ISSUE THREAD

**Issue by nobiac0922** [F5Networks/terraform-provider-bigip#563]
### Environment

 * TMOS/Bigip Version: 13.1.1 (BIG-IQ ver. 8.1)
 * Terraform Version: 1.07
 * Terraform bigip provider Version: 1.11

### Summary

When using TF resource "bigip_bigiq_as3" there is an error when more than 1 GSLB Server Devices are defined. The same declaration works fine if I use TF resource bigip_as3 or if I post the AS3 declaration directly to BIG-IP, but it fails when via BIG-IQ. 

From AS3 schema reference under GSLB_Server, "devices (array<GSLB_Server_Device>)"

### Steps To Reproduce

1. Provide terraform resource config which you are facing trouble along with the output of it.
resource "bigip_bigiq_as3"  "COMMON" {
     bigiq_address = var.bigiq_address
     bigiq_user = "admin"
     bigiq_password = var.bigiq_password
     as3_json = "${file("test_GSLB.tpl")}"
}

2. To get to know more about the issue, provide terraform debug logs

[tflog_debug.txt](https://github.com/F5Networks/terraform-provider-bigip/files/7356064/tflog_debug.txt)

4. As3/DO json along with the resource config( for AS3/DO resource issues )

{
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.30.0",
        "label": "Test DNS onfig",
        "id": "urn:uuid:158c4f1f-5a00-46ad-9f56-3a30e5656c05",
        "remark": "testing DNS config",
        "Common": {
            "class": "Tenant",
            "Shared": {
                "class": "Application",
                "template": "shared",
                "LAB": {
                    "class": "GSLB_Data_Center"
                },
                "labve01-02.test.com": {
                    "class": "GSLB_Server",
                    "dataCenter": {
                        "use": "LAB"
                    },
                    "exposeRouteDomainsEnabled": true,
                    "devices": [
                        {
                            "address": "1.1.1.1"
                        },
                        {
                            "address": "1.1.1.2"
                        }
                    ]
                }
            }
        }
    }
}

### Expected Behavior
There should be no error and GSLB Server is created successfully with two device addresses.

### Actual Behavior
Resources were not created and here is the error output after running terraform apply. 

bigip_bigiq_as3.COMMON: Creating...
│ Error: Error creating json  Common: HTTP 422 :: {"code":422,"message":"status:422, body:{\"code\":422,\"errors\":[\"/Common/Shared/labve01-02.test.com/devices: should NOT have more than 1 items\"],\"declarationFullId\":\"\",\"message\":\"declaration is invalid\"}","originalRequestBody":"{\"code\":422,\"errors\":[\"/Common/Shared/labve01-02.test.com/devices: should NOT have more than 1 items\"],\"declarationFullId\":\"\",\"message\":\"declaration is invalid\"}","referer":"172.28.14.99","restOperationId":138302734,"errorStack":[],"kind":":resterrorresponse"}

**Comment by trinaths** [comment]
Created INFRAANO-563 for internal tracking

**Comment by RavinderReddyF5** [comment]
@nobiac0922 
this problem i have seen with using postman client, it is not specific to Terraform provider. i think we need to find proper declaration to do successful post.

**Error response from POSTMAN client**
```
{
    "code": 422,
    "message": "status:422, body:{\"code\":422,\"errors\":[\"/Common/Shared/labve01-02.test.com/devices: should NOT have more than 1 items\"],\"declarationFullId\":\"\",\"message\":\"declaration is invalid\"}",
    "originalRequestBody": "{\"code\":422,\"errors\":[\"/Common/Shared/labve01-02.test.com/devices: should NOT have more than 1 items\"],\"declarationFullId\":\"\",\"message\":\"declaration is invalid\"}",
    "referer": "172.18.233.215",
    "restOperationId": 74848270,
    "errorStack": [],
    "kind": ":resterrorresponse"
}
```

**Comment by nobiac0922** [comment]
Thanks @RavinderReddyF5 for checking, I have a case open with F5 support and we observed the same behavior when posting the same declaration directly to BIG-IQ. I'm still waiting for a feedback from F5 product development about the issue and I agree this is not specific to terraform provider.
