### ISSUE TITLE
Cloud-init with Vmware VCENTER 6.5 

### ISSUE THREAD

**Issue by Killer2171** [F5Networks/terraform-provider-bigip#565]
I am using terraform in order to deploy F5 with basic configuration via cloud-init but its not working,
VM up but without the expected basic configuration
i've tried also to install manually cloud-init rpm but still the same.
F5 version - 141.4.3
Vcenter version -  6.5.0.35000
**Terraform version** - Terraform v0.15.1
on windows_amd64
+ provider registry.terraform.io/hashicorp/vsphere v2.0.2

F5 cloud init logs output :

2021-10-25 03:42:13,634 - util.py[WARNING]: Getting data from <class 'cloudinit.sources.DataSourceVMwareGuestInfo.DataSourceVMwareGuestInfo'> failed
Cloud-init v. 0.7.5 running 'init' at Mon, 25 Oct 2021 10:42:14 +0000. Up 56.05 seconds.
ci-info: +++++++++++++++++++++++++++Net device info++++++++++++++++++++++++++++
ci-info: +--------+-------+---------------+---------------+-------------------+
ci-info: | Device |   Up  |    Address    |      Mask     |     Hw-Address    |
ci-info: +--------+-------+---------------+---------------+-------------------+
ci-info: | eth4:  | False |       .       |       .       | 00:50:56:b4:98:ec |
ci-info: | eth5:  | False |       .       |       .       | 00:50:56:b4:c4:df |
ci-info: | eth8:  | False |       .       |       .       | 00:50:56:b4:53:ec |
ci-info: | eth6:  | False |       .       |       .       | 00:50:56:b4:89:44 |
ci-info: | eth7:  | False |       .       |       .       | 00:50:56:b4:18:cb |
ci-info: | eth0:  |  True |       .       |       .       | 00:50:56:b4:59:60 |
ci-info: | eth1:  | False |       .       |       .       | 00:50:56:b4:17:d7 |
ci-info: | eth2:  | False |       .       |       .       | 00:50:56:b4:56:11 |
ci-info: | eth3:  | False |       .       |       .       | 00:50:56:b4:12:de |
ci-info: |  lo:   |  True |   127.0.0.1   | 255.255.255.0 |         .         |
ci-info: | mgmt:  |  True | 192.168.1.245 | 255.255.255.0 | 00:50:56:b4:59:60 |
ci-info: | lo:1:  |  True |   127.2.0.2   | 255.255.255.0 |         .         |
ci-info: +--------+-------+---------------+---------------+-------------------+
ci-info: +++++++++++++++++++++++++++++Route info++++++++++++++++++++++++++++++
ci-info: +-------+-------------+---------+---------------+-----------+-------+
ci-info: | Route | Destination | Gateway |    Genmask    | Interface | Flags |
ci-info: +-------+-------------+---------+---------------+-----------+-------+
ci-info: |   0   | 192.168.1.0 | 0.0.0.0 | 255.255.255.0 |    mgmt   |   U   |
ci-info: +-------+-------------+---------+---------------+-----------+-------+
2021-10-25 03:42:14,185 - util.py[WARNING]: Failed to get guestinfo value for key metadata: Unexpected error while running command.
Command: ['/usr/bin/vmtoolsd', '--cmd', 'info-get guestinfo.metadata']
Exit code: 1
Reason: -
Stdout: ''
Stderr: 'No value found\n'

**Comment by nmenant** [comment]
Hi,

The BIG-IP Terraform provider is not related to Cloud-init. I would suggest using the following repos to ask for help on Cloud-init: 
https://github.com/f5devcentral/tmos-cloudinit

Regarding Cloud init and VMware, have you created the relevant ISO containing your user-data? 
https://cloudinit.readthedocs.io/en/latest/topics/datasources/altcloud.html
When you want to leverage cloud init with VMware, you're supposed to create a config drive. Have you done all the required tasks to generate your config as an ISO ? 

Here are some useful links: 
https://clouddocs.f5.com/cloud/public/v1/vmware/vmware_setup.html
https://github.com/f5devcentral/tmos-cloudinit#creating-openstack-formatted-cloudinit-configdrive-isos(it is the same for VMware) - This repo can help you generate the relevant config drive file

**Comment by Killer2171** [comment]
Hi,

I solved the issue , by install the relevant RPM and edit the cloud-init
cfg file
thanks,

‫בתאריך יום ג׳, 26 באוק׳ 2021 ב-15:04 מאת ‪Nicolas Ménant‬‏ <‪
***@***.***‬‏>:‬

**Comment by trinaths** [comment]
closing this issue. User resolved the same.
