### ISSUE TITLE
Big IP F5 - Ansible Error - Removing a node from the pool - \"code\":400,\"message\":\" \\\\' is referenced by a member of pool \\\\'.\",\"errorStack\":[],\"apiError\" - Error

### ISSUE THREAD

**Issue by NGSri** [F5Networks/terraform-provider-bigip#568]
\"code\":400,\"message\":\" \\\\' is referenced by a member of pool \\\\'.\",\"errorStack\":[],\"apiError\"

When I'm deleting a node (state: absent) from the pool USING ANSIBLE SCRIPT, I'm getting the above error. But It does delete, I don't want to see the error.  Anyone could you help me?

**Comment by papineni87** [comment]
is it terraform or ansible ?

**Comment by NGSri** [comment]
> is it terraform or ansible ?

it is ansible

**Comment by papineni87** [comment]
if it is ansible issue , then it should go  to different repo ( https://github.com/F5Networks/f5-ansible/issues)

**Comment by RavinderReddyF5** [comment]
as per last comments closing this issue
