### ISSUE TITLE
Need terraform module bigip-example to be published 

### ISSUE THREAD

**Issue by scshitole** [F5Networks/terraform-provider-bigip#569]
### Is your feature request related to a problem? Please describe.

 We need to publish the existing terraform module https://github.com/hashicorp/f5-terraform-consul-sd-webinar/tree/master/nia/bigip-example this module is currently local.

We just need to publish the module at hashiCorp terraform module registry   at https://registry.terraform.io/namespaces/F5Networks

### Describe the solution you'd like
This terraform module can be used with consul terraform sync to deploy event based service discovery so that whenever there are new services registered to consul, these services will be pushed to BIG-IP by consul terraform sync, also another requirement is to also include the fast template configuration to the same bigip-example module so that everything happens with single event. Here is the fast template which we need to include in the terraform module as well https://github.com/hashicorp/f5-terraform-consul-sd-webinar/tree/master/fast

We just need to publish the module at hashiCorp terraform module registry at https://registry.terraform.io/namespaces/F5Networks

**Comment by trinaths** [comment]
@scshitole - Please review the suggestions shared in the mail conversation. Closing this issue.
