### ISSUE TITLE
bigip_ltm_monitor of parent type mssql

### ISSUE THREAD

**Issue by steina1989** [F5Networks/terraform-provider-bigip#580]
### Is your feature request related to a problem? Please describe.
I want to be able to create a health monitor that inherits from mssql.

### Additional context
resource "bigip_ltm_monitor" "mssql_monitor" {
  name     = "/Common/mssqlmonitor"
  parent   = "/Common/mssql"
...}

Error: parent must be one of /Common/udp, /Common/postgresql, /Common/http, /Common/https, /Common/icmp, /Common/gateway-icmp, /Common/tcp-half-open, /Common/tcp, /Common/ftp

**Comment by trinaths** [comment]
@steina1989 - Only standard monitors are supported to be inherited. User defined monitors are not. Please revisit this RFE.

**Comment by steina1989** [comment]
It is possible to create such a monitor that inherits from mssql in the web gui. Should we not be able to create any Type of monitor from within Terraform?

**Comment by trinaths** [comment]
@steina1989 - Is this possible to create via BIGIP GUI ?

**Comment by steina1989** [comment]
Yes,
![image](https://user-images.githubusercontent.com/20731036/150319704-98fae37d-9656-4921-9fc5-b88a1d62499c.png)
The parent monitor here ships with bigip, I did not create it.

**Comment by trinaths** [comment]
Created INFRAANO-651 for internal tracking.

**Comment by RavinderReddyF5** [comment]
fixed in v1.13.0
