### ISSUE TITLE
Feature Request : Terraform resource for external data group creation on F5(Currently it only supports internal data group)

### ISSUE THREAD

**Issue by kiranjagtap41** [F5Networks/terraform-provider-bigip#583]
### Is your feature request related to a problem? Please describe.
In order to create external data group on F5 we have to use null_resource and create it suing F5 CLI commands , this feature request is to have resource for external data groups just like internal data group which currently exists.

### Describe the solution you'd like
o have resource for external data groups just like internal data group which currently exists

### Describe alternatives you've considered
Create external data group using null_resource passing F5 CLI commands.

**Comment by trinaths** [comment]
Created INFRAANO-647 for internal tracking

**Comment by RavinderReddyF5** [comment]
fixed in v1.13.0, please refer documentation for same: https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_ltm_datagroup#example-usage-for-creating-external-datagroup
