### ISSUE TITLE
node in bigip_ltm_pool_attachment resource should be a list(string)

### ISSUE THREAD

**Issue by Tokynet** [F5Networks/terraform-provider-bigip#586]
### Environment
Terraform v1.0.8
on darwin_amd64
+ provider registry.terraform.io/terraform-providers/bigip v1.11.0
BIG-IP LTM 15.1.2.1

### Summary

Not sure if its a bug or a feature request, but I think the "node" argument in the bigip_ltm_pool_attachment resource should be a list(string) to allow for multiple nodes to be defined in 1 pool_attachment resource.

This is the example code in the documentation:
```
resource "bigip_ltm_pool_attachment" "attach_node" {
  pool = bigip_ltm_pool.pool.name
  node = "${bigip_ltm_node.node.name}:80"
}
```

As it currently stands, if i have 5 nodes which I need to add to the same pool, I would need 5 bigip_ltm_pool_attachment resources, whereas a list(string) would allow me to list them in 1 resource.

What I'm asking for should look like this:

```
resource "bigip_ltm_pool_attachment" "k8sprod" {
  pool = bigip_ltm_pool.k8s_prod.name
  node = [
    "${bigip_ltm_node.k8sworker1.name}:3901",
    "${bigip_ltm_node.k8sworker2.name}:3901",
    "${bigip_ltm_node.k8sworker3.name}:3901"
  ]
}
```
Just FYI, here is the output when I try to define the resource as listed above:

```
│ Error: Incorrect attribute value type
│ 
│   on provider.tf line 82, in resource "bigip_ltm_pool_attachment" "k8sprod":
│   82:   node = [
│   83:     "${bigip_ltm_node.k8sworker1.name}:3901",
│   84:     "${bigip_ltm_node.k8sworker2.name}:3901",
│   85:     "${bigip_ltm_node.k8sworker3.name}:3901"
│   86:   ]
│     ├────────────────
│     │ bigip_ltm_node.k8sworker1.name will be known only after apply
│     │ bigip_ltm_node.k8sworker2.name will be known only after apply
│     │ bigip_ltm_node.k8sworker3.name will be known only after apply
│ 
│ Inappropriate value for attribute "node": string required.
```

**Comment by trinaths** [comment]
Created INFRAANO-646 for internal tracking.

**Comment by RavinderReddyF5** [comment]
@Tokynet hope this example pretty much solves your requirement:

```
resource "bigip_ltm_node" "node1" {
  name    = "/Common/terraform_node1"
  address = "192.168.30.1"
}

resource "bigip_ltm_node" "node2" {
  name    = "/Common/terraform_node2"
  address = "192.168.30.2"
}

resource "bigip_ltm_pool" "k8s_prod" {
  name = "/Common/k8prod_Pool"
}

resource "bigip_ltm_pool_attachment" "k8sprod" {
  for_each = toset([bigip_ltm_node.node1.name, bigip_ltm_node.node2.name])
  pool     = bigip_ltm_pool.k8s_prod.name
  node     = "${each.key}:80"
}
```

Modifying node attribute to list might lead to different problems for other using it same resource. and your requirement pretty much addressed with foreach/count on resources.

**Comment by Tokynet** [comment]
Thanks for the quick response. I noticed this option from another github-issue but still thought the list(String) is the right type for this.

This would be the first use-case that I have for "for_each", lets see how it goes.

I'm going to close this issue because it seems the use of "for_each" is the preferred method for this.

**Comment by Hoonigan-013** [comment]
Hello,

But i am using a different for_each in pool resources to create more than one pool with the same resource and another for_each in node to create new nodes with the same resources. So, if I try to use for_each in pool attachment I receive index error because pool is using one for_each and nodes another for_each.

Could you help me, how can I solve this issue?
