### ISSUE TITLE
getting "invalid character '<' looking for beginning of value" error when using terraform and pulumi import

### ISSUE THREAD

**Issue by Asiya-Yunusa** [F5Networks/terraform-provider-bigip#588]
I am trying to import some bigip resources using terraform but after running the import command i get this error "invalid character '<' looking for beginning of value"  I first got it when using pulumi and decided to try terraform but got the same error

`invalid character '<' looking for beginning of value`

**Comment by RavinderReddyF5** [comment]
@Asiya-Yunusa can you please specify which resources you are seeing this issue.

**Comment by Asiya-Yunusa** [comment]
Hi @RavinderReddyF5 it turns out the URL I used wasn't pointing to the right API endpoint, so after fixing that it worked. 

I used the iControl API documentation for f5.

Thank you.

**Comment by RavinderReddyF5** [comment]
@Asiya-Yunusa thanks for update. i am closing issue. please reopen new issue if u any issue again.
