### ISSUE TITLE
panic runtime error: index out of range

### ISSUE THREAD

**Issue by Jeroensum** [F5Networks/terraform-provider-bigip#592]
I believe the crash below is due to the fact that I specified an  Irule instead of iRule component in the json file. When I correct the statement the crash does not happen.

I've attached the json file as test.txt
[test.txt](https://github.com/F5Networks/terraform-provider-bigip/files/8042328/test.txt)

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

bigip_as3.as3_test_1: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with bigip_as3.as3_test_1,
│   on main.tf line 1, in resource "bigip_as3" "as3_test_1":
│    1: resource "bigip_as3" "as3_test_1" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-bigip_v1.12.2 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 42 [running]:
github.com/f5devcentral/go-bigip.(*BigIP).PostAs3Bigip(0xc0002840e0, 0xc00013ea00, 0x4d1, 0xc0003f2198, 0x17, 0x0, 0x0, 0x2, 0x2, 0xffffffffffffffff, ...)
	github.com/f5devcentral/go-bigip@v0.0.0-20220119082918-5f215f878998/as3bigip.go:87 +0x1cfe
github.com/F5Networks/terraform-provider-bigip/bigip.resourceBigipAs3Create(0xc000284700, 0x10262e0, 0xc0002840e0, 0x0, 0x0)
	github.com/F5Networks/terraform-provider-bigip/bigip/resource_bigip_as3.go:190 +0x43b
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0004ccf00, 0xc0003f6550, 0xc0007a4440, 0x10262e0, 0xc0002840e0, 0xefd701, 0xc0004e9118, 0xc0003f5440)
	github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/resource.go:305 +0x375
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc0004cd700, 0xc0001398e8, 0xc0003f6550, 0xc0007a4440, 0xc0004e9198, 0xc000506030, 0xeff4c0)
	github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000ebd0, 0x11ba050, 0xc0003f47b0, 0xc0003fe660, 0xc00000ebd0, 0xc0003f47b0, 0xc000a1ba50)
	github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/helper/plugin/grpc_provider.go:885 +0x8a5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xfe5160, 0xc00000ebd0, 0x11ba050, 0xc0003f47b0, 0xc0003fe600, 0x0, 0x11ba050, 0xc0003f47b0, 0xc0002eda80, 0x1a00)
	github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000e4000, 0x11c2838, 0xc000103680, 0xc00014a100, 0xc0008843f0, 0x171fca0, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.23.0/server.go:995 +0x482
google.golang.org/grpc.(*Server).handleStream(0xc0000e4000, 0x11c2838, 0xc000103680, 0xc00014a100, 0x0)
	google.golang.org/grpc@v1.23.0/server.go:1275 +0xd2c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000128170, 0xc0000e4000, 0x11c2838, 0xc000103680, 0xc00014a100)
	google.golang.org/grpc@v1.23.0/server.go:710 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.23.0/server.go:708 +0xa5

Error: The terraform-provider-bigip_v1.12.2 plugin crashed!
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by RavinderReddyF5** [comment]
@Jeroensum do you still any issue here ? please share reproduction if you still see issue

**Comment by Jeroensum** [comment]
Hi RavinderReddyF5,

This is still an issue. You can reproduce it by calling Terraform using the json file I provided.

**Comment by RavinderReddyF5** [comment]
tracking through: INFRAANO-687
