### ISSUE TITLE
Network resource bigip_net_selfip documentation missing correct port_lockdown explanation

### ISSUE THREAD

**Issue by Otimun** [F5Networks/terraform-provider-bigip#594]
### Environment

 * TMOS/Bigip Version: 15.1.3
 * Terraform Version: v1.1.5
 * Terraform bigip provider Version: 1.12.2

### Summary
Unable to use "none" as port lockdown option in resource bigip_net_selfip.

If there is an ability for this, it is not documented on the terraform provider website.

The reason this might not work is because the api call is a little different for the none setting, it is outside of an array the json parameter is: "allowService": "none" instead of for example "allowService": [ "default" ].

### Steps To Reproduce

Tried different ways to configure this:
resource "bigip_net_selfip" "Local-selfIPs" {
  port_lockdown = "none"
}
gives the following error:
│ Error: Incorrect attribute value type
│ 
│   on bigip.tf line 76, in resource "bigip_net_selfip" "Local-selfIPs":
│   76:   port_lockdown = "none"
│ 
│ Inappropriate value for attribute "port_lockdown": list of string required.

When trying to put none inside of list:
resource "bigip_net_selfip" "Local-selfIPs" {
  port_lockdown = ["none"]
}

│ Error: Error modifying SelfIP /Test2/Local-test-self2: HTTP 400 :: {"code":400,"message":"\"allow-service\" invalid entry \"none\", format must be protocol:port","errorStack":[],"apiError":26214401}
│ 
│   with bigip_net_selfip.Local-selfIPs["test-self2"],
│   on bigip.tf line 70, in resource "bigip_net_selfip" "Local-selfIPs":
│   70: resource "bigip_net_selfip" "Local-selfIPs" {
│ 

### Expected Behavior
Ability to configure a self IP completely locked down.

### Actual Behavior
When trying to configured none, there is either an error in before the apply/plan output or a HTTP 400 error not allowing the configuration.

**Comment by Otimun** [comment]
Just ran the code again, but this time without the port lockdown configuration. It seems that without specifying portlockdown it will default to "none".

This means that the documentation is actually what needs to be adjusted:
https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_net_selfip#port_lockdown
[port_lockdown](https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_net_selfip#port_lockdown) - (Optional) Specifies the port lockdown, defaults to Allow Default if not specified.

It mentions that it defaults to Allow Default, but it should be to Allow None.

**Comment by urohit011** [comment]
Tracking through: INFRAANO-689

**Comment by RavinderReddyF5** [comment]
fixed in v1.13.1
