### ISSUE TITLE
Basic Auth sent with token request to mgmt/shared/authn/login

### ISSUE THREAD

**Issue by scoffeyfv** [F5Networks/terraform-provider-bigip#602]
### Environment

 * TMOS/Bigip Version: any
 * Terraform Version: any
 * Terraform bigip provider Version: 1.13.0

### Summary

When provider requests a token from mgmt/shared/authn/login, Basic Auth headers are added.  These are not necessary as this endpoint is anonymous, or rather the credentials are provided in the JSON body.

Whilst this may appear to be harmless, it may unnecessarily trigger this issue in the REST API:
https://cdn.f5.com/product/bugtracker/ID1035661.html

### Steps To Reproduce

Configure provider to use token auth (requested by provider, not a token provided by the user) i.e.:

    username = "admin"
    password = "admin"
    login_ref = "tmos"
    token_auth = "true"

Trigger some deployment.

### Expected Behavior
Provider should POST to mgmt/shared/authn/login without Basic Auth or X-F5-Auth-Token header.
 
### Actual Behavior
Provider POSTs to mgmt/shared/authn/login with Basic Auth.
 
We can see this code in APICall which results in either sending a (existing) token as a header,  or if none present, sending Basic Auth.  

_if b.Token != "" {
		req.Header.Set("X-F5-Auth-Token", b.Token)
	} else {
		req.SetBasicAuth(b.User, b.Password)
	}_

Fix would be something like
 
_if b.Token != "" {
		req.Header.Set("X-F5-Auth-Token", b.Token)
	} else if options.URL != "mgmt/shared/authn/login" {
		req.SetBasicAuth(b.User, b.Password)
	}_

**Comment by trinaths** [comment]
Created [INFRAANO-702] for internal tracking.
