### ISSUE TITLE
Update the terraform documentation for BIG-IQ

### ISSUE THREAD

**Issue by ictabc** [F5Networks/terraform-provider-bigip#606]
Not really a bug, or feature request, maybe a little bit at the end.

On the following page:

https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_common_license_manage_bigiq

bigiq_login_ref is mentioned, needed for external authentication.

But on:

https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_bigiq_as3

There is no mention of this option. I tried to set this option as I saw the login_ref in the provider settings. And found out it was working, which would be unnecessary if this was documented.

Would be nicer if this could be integrated into the provider config, instead doing this at every resource request. Maybe by just setting an bigiq = true in the resource option, and using the provider settings for login.

**Comment by trinaths** [comment]
Created [INFRAANO-722] for internal tracking.

**Comment by RavinderReddyF5** [comment]
@ictabc fixed in v1.14.0
