### ISSUE TITLE
Handling of Self IPs within a route domain

### ISSUE THREAD

**Issue by andyburridge** [F5Networks/terraform-provider-bigip#608]
### Environment

 * TMOS/Bigip Version: BIG-IP 16.1.2.1
 * Terraform Version: 1.17
 * Terraform bigip provider Version: 1.13

### Summary

When using the bigip_net_selfip module to create self IPs within a route domain using the % nomenclature, e.g.

```
resource "bigip_net_selfip" "dmz_local" {
  name       = "/Common/dmz_local"
  ip         = "10.165.64.11%1/24"
  vlan       = "/Common/dmz"
}
```

It creates the resource correctly within the BIG-IP, but when the plan is re-rerun, it forces a replacement as below:

```
# module.big_ip_networking.bigip_net_selfip.big_ip_self_ips_floating["/Common/dmz_local"] must be replaced
-/+ resource "bigip_net_selfip" "dmz_local" {
      ~ id            = "/Common/dmz_local" -> (known after apply)
      ~ ip            = "10.165.64.11/24" -> "10.165.64.11%1/24" # forces replacement
        name          = "/Common/dmz_local"
        # (3 unchanged attributes hidden)
    }
```

This has the downstream effect of breaking the plan, because it tries to delete a local selfip that is associated to a floating selfip, or a route, for example:

`│ Error: Error deleting SelfIP /Common/dmz_local: HTTP 400 :: {"code":400,"message":"01070604:3: Cannot delete IP 10.165.64.11%1 because it would leave a route unreachable.","errorStack":[],"apiError":3}`

This seems to be because within the tfstate file, the ip address is stored without the '%1', despite it being provided within the plan, and accurately programmed into the BIG-IP:

```
"instances": [
        {
          "index_key": "/Common/dmz_local",
          "schema_version": 0,
          "attributes": {
            "id": "/Common/dmz_local",
            "ip": "10.165.64.11/24",
            "name": "/Common/dmz_local",
            "port_lockdown": [],
            "traffic_group": "traffic-group-local-only",
            "vlan": "/Common/dmz"
          },
          "sensitive_attributes": [],
          "private": "bnVsbA==",
        }

```
### Steps To Reproduce
Create a selfip within a specific route domain and re-run the plan.  It will be deleted and recreated due to the tfstate file not referencing the %.

### Expected Behavior
The plan to identify that the selfip exists and not try to force replacement.

### Actual Behavior
Replacement of selfip, which breaks downstream plan elements that rely on the presence of the selfip.

**Comment by trinaths** [comment]
Created [INFRAANO-724] for internal tracking.
