### ISSUE TITLE
resource bigip_as3 plugin does not respond and throws a runtime error and crashes

### ISSUE THREAD

**Issue by gwolfis** [F5Networks/terraform-provider-bigip#611]
Using terraform provider plugin v1.11.0

TMOS v16.0.101000
terraform version
Terraform v1.1.4
on darwin_amd64

    provider registry.terraform.io/hashicorp/azurerm v2.94.0
    provider registry.terraform.io/hashicorp/local v2.1.0
    provider registry.terraform.io/hashicorp/null v3.1.1
    provider registry.terraform.io/hashicorp/random v3.1.0
    provider registry.terraform.io/hashicorp/template v2.2.0
    provider registry.terraform.io/terraform-providers/bigip v1.11.0

Essential Terraform code:
```
resource "bigip_as3" "app_services" {
  as3_json = local.as3_json
}

resource "local_file" "as3" {
    content     = local.as3_json
    count       = var.default_instance_count
    filename    = "${path.module}/as3-bigip${count.index}.json"
}

locals {
    count       = var.default_instance_count
    as3_json = templatefile("${path.module}/as3.tpl", {
    
    resource_group_name = azurerm_resource_group.rg.name
    discovery           = var.service_discovery_value
    subscription_id     = var.subscription_id
    //ext_vip             = "${element(azurerm_network_interface.external.*.private_ip_addresses, 1)}"
  })
}
```
error output:
```
bigip_as3.app_services: Creating...
╷
│ Error: Plugin did not respond
│
│ with bigip_as3.app_services,
│ on bigip.tf line 155, in resource "bigip_as3" "app_services":
│ 155: resource "bigip_as3" "app_services" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
```
Stack trace from the terraform-provider-bigip_v1.11.0 plugin:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x133e05e]

goroutine 27 [running]:
github.com/f5devcentral/go-bigip.(*BigIP).APICall(0x0, 0xc0005ed2b0, 0x0, 0x0, 0x0, 0x0, 0x0)
github.com/f5devcentral/go-bigip@v0.0.0-20210804055259-11b1d1a8dd26/bigip.go:177 +0x7e
github.com/f5devcentral/go-bigip.(*BigIP).getForEntity(0x0, 0x1b22a60, 0xc00057eec0, 0xc0005ed350, 0x4, 0x4, 0xa, 0x1b32760, 0xc0001aee78)
github.com/f5devcentral/go-bigip@v0.0.0-20210804055259-11b1d1a8dd26/bigip.go:451 +0xe6
github.com/f5devcentral/go-bigip.(*BigIP).getAs3version(0x0, 0x40e, 0x480, 0x1b32760)
github.com/f5devcentral/go-bigip@v0.0.0-20210804055259-11b1d1a8dd26/as3bigip.go:302 +0xfb
github.com/f5devcentral/go-bigip.(*BigIP).AddTeemAgent(0x0, 0x1b50700, 0xc0005ed5f8, 0x1b50700, 0xc0002ae3f0, 0x0, 0x0)
github.com/f5devcentral/go-bigip@v0.0.0-20210804055259-11b1d1a8dd26/as3bigip.go:417 +0x116
github.com/F5Networks/terraform-provider-bigip/bigip.resourceBigipAs3Create(0xc0005210a0, 0x1cd1020, 0x0, 0x0, 0x0)
github.com/F5Networks/terraform-provider-bigip/bigip/resource_bigip_as3.go:180 +0x356
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000548b80, 0xc000572c30, 0xc000580460, 0x1cd1020, 0x0, 0x1b95201, 0xc000197488, 0xc000486a50)
github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/resource.go:305 +0x375
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000549300, 0xc0005ed8e8, 0xc000572c30, 0xc000580460, 0xc0001974d8, 0xc0001aec30, 0x1b96f00)
github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0001aebb0, 0x1e7efb0, 0xc0004860f0, 0xc00004f500, 0xc0001aebb0, 0xc0004860f0, 0xc00012ca50)
github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/helper/plugin/grpc_provider.go:885 +0x88b
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1c8d3a0, 0xc0001aebb0, 0x1e7efb0, 0xc0004860f0, 0xc00004f4a0, 0x0, 0x1e7efb0, 0xc0004860f0, 0xc0005f8000, 0xd7d)
github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001e6000, 0x1e87a98, 0xc000102f00, 0xc00011ea00, 0xc000094690, 0x2441a20, 0x0, 0x0, 0x0)
google.golang.org/grpc@v1.23.0/server.go:995 +0x482
google.golang.org/grpc.(*Server).handleStream(0xc0001e6000, 0x1e87a98, 0xc000102f00, 0xc00011ea00, 0x0)
google.golang.org/grpc@v1.23.0/server.go:1275 +0xd2c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0001161d0, 0xc0001e6000, 0x1e87a98, 0xc000102f00, 0xc00011ea00)
google.golang.org/grpc@v1.23.0/server.go:710 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.23.0/server.go:708 +0xa5

Error: The terraform-provider-bigip_v1.11.0 plugin crashed!

```

**Comment by RavinderReddyF5** [comment]
@gwolfis is this reproducible ? can you please retest on latest version of terraform provider and share terraform config/as3 template being used for this issue

**Comment by gwolfis** [comment]
@RavinderReddyF5 Just updated both TF and the BIGIP provider and rerun the script.

╷
│ Error: Plugin did not respond
│
│ with bigip_as3.app_services,
│ on bigip.tf line 155, in resource "bigip_as3" "app_services":
│ 155: resource "bigip_as3" "app_services" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
Stack trace from the terraform-provider-bigip_v1.13.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x133fefe]

goroutine 28 [running]:
github.com/f5devcentral/go-bigip.(*BigIP).APICall(0x0, 0xc00068f288, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/f5devcentral/go-bigip@v0.0.0-20220302174144-f3febbee09dd/bigip.go:177 +0x7e
github.com/f5devcentral/go-bigip.(*BigIP).getForEntity(0x0, 0x1a8d5a0, 0xc00029b880, 0xc00068f328, 0x4, 0x4, 0xa, 0x1a9d2e0, 0xc00014c6c0)
        github.com/f5devcentral/go-bigip@v0.0.0-20220302174144-f3febbee09dd/bigip.go:451 +0xe6
github.com/f5devcentral/go-bigip.(*BigIP).getAs3version(0x0, 0x40e, 0x480, 0x1a9d2e0)
        github.com/f5devcentral/go-bigip@v0.0.0-20220302174144-f3febbee09dd/as3bigip.go:304 +0xfb
github.com/f5devcentral/go-bigip.(*BigIP).AddTeemAgent(0x0, 0x1abaa60, 0xc00068f600, 0x1abaa60, 0xc00011eaf0, 0x0, 0x0)
        github.com/f5devcentral/go-bigip@v0.0.0-20220302174144-f3febbee09dd/as3bigip.go:442 +0x116
github.com/F5Networks/terraform-provider-bigip/bigip.resourceBigipAs3Create(0xc000526d20, 0x1c28080, 0x0, 0x0, 0x0)
        github.com/F5Networks/terraform-provider-bigip/bigip/resource_bigip_as3.go:185 +0x35c
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000165d00, 0xc000112d20, 0xc0004d8440, 0x1c28080, 0x0, 0x1aff301, 0xc0000d8e18, 0xc000654240)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/resource.go:305 +0x375
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc0000a6580, 0xc00068f8e8, 0xc000112d20, 0xc0004d8440, 0xc0000d8e70, 0xc00014c450, 0x1b01040)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00014c180, 0x1dbd010, 0xc000121620, 0xc00038cd80, 0xc00014c180, 0xc000121620, 0xc00055ba50)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/helper/plugin/grpc_provider.go:885 +0x8a5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1be7560, 0xc00014c180, 0x1dbd010, 0xc000121620, 0xc00038cd20, 0x0, 0x1dbd010, 0xc000121620, 0xc000268000, 0xd91)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001d8160, 0x1dc59b8, 0xc000683500, 0xc0000bcb00, 0xc000121260, 0x2326dc0, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.23.0/server.go:995 +0x482
google.golang.org/grpc.(*Server).handleStream(0xc0001d8160, 0x1dc59b8, 0xc000683500, 0xc0000bcb00, 0x0)
        google.golang.org/grpc@v1.23.0/server.go:1275 +0xd2c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00047e010, 0xc0001d8160, 0x1dc59b8, 0xc000683500, 0xc0000bcb00)
        google.golang.org/grpc@v1.23.0/server.go:710 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.23.0/server.go:708 +0xa5

Error: The terraform-provider-bigip_v1.13.0 plugin crashed!

**Comment by trinaths** [comment]
Created [INFRAANO-725] for internal tracking.

**Comment by urohit011** [comment]
Hi @gwolfis , could you please share the as3 template file you're using.

**Comment by gwolfis** [comment]
Not able to find the issue again or reproduce it. I continued into another direction I guess.
