### ISSUE TITLE
Deleting AS3 declaration with bigip-as3 resource throws an errror.

### ISSUE THREAD

**Issue by gwolfis** [F5Networks/terraform-provider-bigip#620]
Using big-as3 resource as part of the big-ip terraform provider works when an AS3 deployed app service gets deleted, but it throws an error.

### Environment

 * TMOS/Bigip Version: 16.0.1
 * Terraform Version: 1.1.7
 * Terraform bigip provider Version: 13.1

### Summary
Using resource bigip_as3 to deploy applications and making mods is working correctly. Soon when you want to use the resource to delete a tenant it throws an error. (yes, the tenant will get removed from BIG-IP)

Method used to delete a tenant is by deploying an 'empty' AS3 json which has only the class tenant defined with the name of the tenant which needs to get deleted.

### Steps To Reproduce

1. Deploy an AS3 declaration via terraform using the resource bigip-as3.

2. Remove that same AS3 declaration eg:

{
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.0.0",
        "label": "LAB 2",
        "remark": "Two applications sharing a pool",
        "lab_2": {
            "class": "Tenant"
        }
    }
}

### Expected Behavior
The tenant will get removed from the BIG-IP without the terraform bigip provider throwing an errror

### Actual Behavior
Terraform out put after 'terraform apply -auto-approve'

Plan: 0 to add, 1 to change, 0 to destroy.
bigip_as3.as3_use_case_6: Modifying... [id=lab_2]
bigip_as3.as3_use_case_6: Still modifying... [id=lab_2, 10s elapsed]
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to bigip_as3.as3_use_case_6, provider "provider[\"registry.terraform.io/f5networks/bigip\"]" produced an unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Comment by trinaths** [comment]
Created [INFRAANO-766] for internal tracking.

**Comment by RavinderReddyF5** [comment]
@gwolfis fixed in latest release, please reopen new issue if you still see any issue
