### ISSUE TITLE
Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by gwolfis** [F5Networks/terraform-provider-bigip#628]
Situation:
Using the big-ip Terraform in Azure to deploy applications via AS3 templates (.tpl). Adding applications by declaring them via template works. When you want to remove a tenant by creating an 'empty' AS3.tpl like below, the bigip provider produces this error.

Error: Provider produced inconsistent result after apply
│
│ When applying changes to bigip_as3.as3_use_case_6, provider "provider["registry.terraform.io/f5networks/bigip"]" produced an unexpected new value: Root resource was
│ present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

AS3.tpl used to remove the tenant:
{
"class": "AS3",
"action": "deploy",
"persist": true,
"declaration": {
"class": "ADC",
"schemaVersion": "3.0.0",
"label": "LAB 2",
"remark": "Two applications sharing a pool",
"lab_2": {
"class": "Tenant"
}
}
}

When checking the BIG-IP the tenant did got removed.

Used software versions:
Terraform v1.1.9
on linux_amd64
    provider registry.terraform.io/f5networks/bigip v1.13.1
    provider registry.terraform.io/hashicorp/azurerm v2.94.0
TMOS 16.0.1
AS3 3.35

Can it be reproduced:
Yes, tried this a couple of times and seeing the same behavior.
1. Deploy an application service via an AS3 declaration using the bigip_as3 TF resource
2. Check the deployment on the BIG-IP
3. Delete the application service via an 'empty' AS3 declaration as shown in the above example using bigip_as3 TF resource

**Comment by trinaths** [comment]
Created [INFRAANO-767] for internal tracking.

**Comment by trinaths** [comment]
Recommend TF destroy to delete the AS3 partition in BIGIP. @gwolfis

**Comment by RavinderReddyF5** [comment]
please check on latest version
