### ISSUE TITLE
bigip_ltm_monitor based on ldap parent monitor

### ISSUE THREAD

**Issue by pzamoran** [F5Networks/terraform-provider-bigip#632]
### Is your feature request related to a problem? Please describe.
I would like to create ltm monitors based on ldap monitor, however, I can not use "username, password, filters" attributes. I another hand, I can not get data from a ltm monitor based on ldap monitor.

### Describe the solution you'd like
Be able to create and get data from ltm monitors based on ldap monitor.

**Comment by trinaths** [comment]
Created [INFRAANO-768] for internal tracking.

**Comment by marsu-p** [comment]
It's still not possible to set filters or basedn. See also here available parameters for monitors of type ldap:
https://clouddocs.f5.com/api/icontrol-rest/APIRef_tm_gtm_monitor_ldap.html


Name | Type | Default Value | Required | Access | Description
-- | -- | -- | -- | -- | --
appService | string |   | optional | read/write | The application service to which the object belongs.
base | string |   | optional | read/write | Specifies the location in the LDAP tree from which the monitor starts the health check. A sample value is dc=bigip-test,dc=net.
chaseReferrals | string |   | optional | read/write | Specifies whether the system will query the LDAP servers pointed to by any referrals in the query results.
debug | string |   | optional | read/write | Specifies whether the monitor sends error messages and additional information to a log file created and labeled specifically for this monitor. The default setting is no. You can use the log information to help diagnose and troubleshoot unsuccessful health checks. The options are ‘no’ (specifies that the system does not redirect error messages and additional information related to this monitor to the log file) and ‘yes’ (specifies that the system redirects error messages and additional information to the /var/log/monitors/<monitor_name>-<node_name>-<port>.log file).
defaultsFrom | string |   | optional | read/write | Specifies the existing monitor from which the system imports settings for the new monitor.
description | string |   | optional | read/write | User defined description.
destination | string |   | optional | read/write | Specifies the IP address and service port of the resource that is the destination of this monitor. Possible values are: *:* (Specifies to perform a health check on the IP address and port supplied by a pool member), *:port (Specifies to perform a health check on the server with the IP address supplied by the pool member and the port you specify.), and <IP>:<port> (Specifies to mark a pool member up or down based on the response of the server at the IP address and port you specify.).
filter | string |   | optional | read/write | Specifies an LDAP key for which the monitor searches. A sample value is: objectclass=*.
ignoreDownResponse | string |   | optional | read/write | Specifies whether the monitor ignores a down response from the system it is monitoring. The default value is disabled.
interval | integer |   | optional | read/write | Specifies the frequency at which the system issues the monitor check. The default value is 10 seconds.
mandatoryAttributes | string |   | optional | read/write | Specifies whether the target must include attributes in its response to be considered up. The options are no (Specifies that the system performs only a one-level search (based on the Filter setting), and does not require that the target returns any attributes.) and yes (Specifies that the system performs a sub-tree search, and if the target returns no attributes, the target is considered down.)
tmPartition | string |   | optional | read/write | Displays the administrative partition within which the monitor resides.
password | string |   | optional | read/write | Specifies the password if the monitored target requires authentication.
probeTimeout | integer |   | optional | read/write | Specifies the number of seconds after which the BIG-IP system times out the probe request to the BIG-IP system. The default value is 5 seconds.
security | string |   | optional | read/write | Specifies the secure communications protocol that the monitor uses to communicate with the target. The options are none (Specifies that the system does not use a security protocol for communications with the target.), ssl (Specifies that the system uses the SSL protocol for communications with the target.), and tls (Specifies that the system uses the TLS protocol for communications with the target.)
timeout | integer |   | optional | read/write | Specifies the number of seconds the target has in which to respond to the monitor request. The default value is 31 seconds. If the target responds within the set time period, it is considered up. If the target does not respond within the set time period, it is considered down. Also, if the target responds with a RESET packet, the system immediately flags the target as down without waiting for the timeout interval to expire.
username | string |   | optional | read/write | Specifies the user name if the monitored target requires authentication.
