### ISSUE TITLE
bigip_ltm_policy cannot be  created with an additional path

### ISSUE THREAD

**Issue by Pushmis** [F5Networks/terraform-provider-bigip#634]
### Environment

 * TMOS/Bigip Version: 15.1.0.3 build 0.0.12
 * Terraform Version: 1.1.4
 * Terraform bigip provider Version: 1.13.0

### Summary

I`m try to create ltm policy : /Partition/Path/PolicyName

    resource "bigip_ltm_policy" "test-policy" {
        name = "Partition/Path/Name" 
        strategy = "first-match"
        requires = ["http"]
        controls = ["forwarding"]
        rule { 
            name = "rest-rule"
            condition { . . . }
            action { 
                forward = true
                pool = bigip_ltm_pool.pool.name
            }
        }
    
        depends_on = ["bigip_ltm_pool.mypool"]
    }

EXPECTED RESULTS:

  created ltm policy  in partition "Partition" with path "Path" name "PolicyName"  like pools  
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/22854846/169895018-a1c93a0b-56a6-48f9-9e2f-e315bb2a8a5c.png">
 but policy is created not in the expected directory with name "Name", It was created on root directory of Partition with name "Path"

I see in code remark "Policy name failed to match the regex, and should be of format /partition/policy_name"  in https://github.com/F5Networks/terraform-provider-bigip/blob/master/bigip/resource_bigip_ltm_policy.go 

As I understand, it has not yet been implemented. 

Can you implement to add policy in a directory  (like pools): partition + directory + name ?

**Comment by trinaths** [comment]
@Pushmis What would be an example path you want to refer. Were you able to refer this path from BIGIP GUI ?
