### ISSUE TITLE
Feature Request: GTM/Wide IP DNS support

### ISSUE THREAD

**Issue by dresken** [F5Networks/terraform-provider-bigip#65]
I know the front page states "A Terraform provider for F5 BigIP LTM." and the Doco website says "Resources are currently available for LTM." - however is the plan to eventually include GTM with this provider as well?

**Comment by erjac77** [comment]
I'm also interested by this. I think the following resources would be very useful and could be a good starting point:

- GTM WideIP
- GTM Pool
- GTM Server

**Comment by KrithikaChidambaram** [comment]
Hi, closing this request now. 
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
