### ISSUE TITLE
bigip_ltm_policy: Condition "exists/does not exist" is not available

### ISSUE THREAD

**Issue by mdan366** [F5Networks/terraform-provider-bigip#651]
bigip_ltm_policy: Condition "exists/does not exist" is not available
Policy cannot be created with a rule that contains the operand 'http-header' and the condition 'exists/does not exist'.

The rest of the dropdown options are configurable:
is/is not --> not
starts with/does not start with --> start_with
end with/does not end with --> end_with
contains/does not contains --> contains
exists/does not exists --> ???? which field does it correspond to?

If i use operand http-header with not (instead of exists that not appears), it shows the error "Operand 'http-header' with condition 'equals' requires at least 1 value". 
These error can be normal with "not", but the option "exists/does not exist" dont have value , so it can not be validated. 

I`m trying to create the next policy:

resource "bigip_ltm_policy" "test-policy" {
    name = "Partition/Name" 
    strategy = "first-match"
    requires = ["http"]
    controls = ["forwarding"]
	rule { 
		name = "replace_if_not_exist_rule" 
		action { 
			replace = true
			http_header = true 
			tm_name = X-Forwarded-Prueba 
			value = https 
			}
		condition { 
			http_header = true 
			tm_name = X-Forwarded-Prueba
			exist??? = true    
			}
		}
	}

### Describe the solution you'd like  
Create attribute "exists" and remove validate value associated to http-header. This field value doesnt appear in "exists/does not exist".

**Comment by trinaths** [comment]
Created [INFRAANO-810] for internal tracking
