### ISSUE TITLE
Cannot create ltm_pool_attachments with route domains

### ISSUE THREAD

**Issue by braunsonm** [F5Networks/terraform-provider-bigip#661]
### Environment

* TMOS/Bigip Version: 15.1.5
* Terraform Version: 1.0.4
* Terraform bigip provider Version: 1.13.0

### Summary

As far as I know it is not possible to use `ltm_pool_attachment` with route domains. The provider incorrectly sends the request as an FDQN when you use an IP with a route domain.

### Steps To Reproduce

```terraform
resource "bigip_ltm_node_attachment" "attach" {
  pool = "/Common/somepool"
  node = "1.1.1.1%10:8080"
}
```

### Expected Behavior
Node with route domain attached

### Actual Behavior
Error that it is an invalid FQDN, even though it should be treated as an IP.

**Comment by braunsonm** [comment]
This is possible using the node name if you don't try to use the direct address.

**Comment by RavinderReddyF5** [comment]
@braunsonm yes as you stated please use 
```
resource "bigip_ltm_pool" "example_pool" {
  name                = "/Common/test-pool-issue92"
  load_balancing_mode = "round-robin"
  description         = "Example pool"
  allow_snat          = "yes"
  allow_nat           = "yes"
}
resource "bigip_ltm_node" "node1" {
  name        = "/Common/test-node-issue92"
  description = "Terraform managed"
  address     = "172.17.240.182%10"
}
resource "bigip_ltm_pool_attachment" "example_pool_member_1" {
  pool = bigip_ltm_pool.example_pool.name
  node = format("%s:%s", bigip_ltm_node.node1.name, 0)
}
```

**Comment by braunsonm** [comment]
That's a workaround and not a solution to the problem. This should still be fixed or documented as it causes unforseen issues.
