### ISSUE TITLE
Auto decryption encrypted private key not supported

### ISSUE THREAD

**Issue by jkacou** [F5Networks/terraform-provider-bigip#675]
### Is your feature request related to a problem? Please describe.
Currently, use the provider to push certificate private key to bigip force to use a plain text version of the key (witch is not allowed in my company for now) when we want to have the clear private key rather than the encrypted version
There is no way to add the password key so the *bigip_ssl_key* resource could automatically decrypt it before push

### Describe the solution you'd like
Currently the bigip_ssl_key resource is:
resource "bigip_ssl_key" "test-key" {
  name      = "serverkey.key"
  content   = file("serverkey.key")
  partition = "Common"
}
And it wild be really cool to have an optional field for the key password like
resource "bigip_ssl_key" "test-key" {
  name      = "serverkey.key"
  content   = file("serverkey.key")
  **encryption_key = "very_secret_password"**
  partition = "Common"
}

### Describe alternatives you've considered
For now we have to do it through local-exec, not really good actually in a security view

**Comment by jkacou** [comment]
Hi,
Is any solution about this issue is available ?
Additionally I noticed even working with encripted key doesn't work also (since there is no way to enter the key password)

Will apreciate to have a solution for this one

Thank you

**Comment by KrithikaChidambaram** [comment]
Please refer to this, a vault like HashiCorp might help:  https://community.f5.com/t5/technical-articles/automating-certificate-lifecycle-management-with-hashicorp-vault/ta-p/287131?tab=My%20Articles&tag=&page=1

**Comment by pgouband** [comment]
Hi, closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
