### ISSUE TITLE
When providing a null username or null password Provider error -  panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mrhorrible78** [F5Networks/terraform-provider-bigip#676]
### Environment

 * TMOS/Bigip Version: v15.1.5.1
 * Terraform Version: 1.2.8
 * Terraform bigip provider Version: 1.15.1

### Summary

If you provide either a null password or null username the provider panics and produces a stack trace.  I was able to do this with Terraform Cloud where I defined variables in my workspace, but embarrassingly, forgot to assign values to the variables.  I would expect that this exception would be caught and a more useful error message indicating a failure to provide a valid username or password to be created instead.  I think this is a pretty low severity issue, just something that I think might be helpful and save someone else some embarrassing troubleshooting later on.

### Steps To Reproduce

This is what I did to reproduce this behavior
1. Create some terraform that creates any resource that requires the bigip provider
2. Create a workspace in Terraform Cloud to run that Terraform plan 
3. Create variables for providing a username and password but then don't assign any value (note if the variable existed before and you erased the value it doesn't seem to reproduce the error)
4. Run the plan and try and apply it.
5. Receive Stack Trace

I have played around with it a bit and this happens if you have both user and password as null, or either one as null.
I can also recreate this using terraform on my workstation by exporting empty username and password environment variables.
`export TF_VAR_username=
export TF_VAR_password=`

And my provider block looks like this
`provider "bigip" {
  address = var.hostname
  username = var.username
  password = var.password
}`

### Expected Behavior
I expect an error message indicating an authorization failure or that no username or password was provided

### Actual Behavior
A stack trace was created like this:
Stack trace from the terraform-provider-bigip_v1.15.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x72555f]

goroutine 29 [running]:
github.com/f5devcentral/go-bigip.(*BigIP).APICall(0x0, 0xc0004d55a8)
github.com/f5devcentral/go-bigip@v0.0.0-20220817175609-60a96e5b7c18/bigip.go:177 +0x7f
github.com/f5devcentral/go-bigip.(*BigIP).getForEntity(0x16b2e00?, {0xd99320, 0xc00031cac8}, {0xc0004d5638?, 0xc000134000?, 0xc0004d5610?})
github.com/f5devcentral/go-bigip@v0.0.0-20220817175609-60a96e5b7c18/bigip.go:451 +0xb8
github.com/f5devcentral/go-bigip.(*BigIP).VirtualAddresses(0xc0004d56d0?)
github.com/f5devcentral/go-bigip@v0.0.0-20220817175609-60a96e5b7c18/ltm.go:2541 +0x8c
github.com/F5Networks/terraform-provider-bigip/bigip.resourceBigipLtmVirtualAddressExists(0xc0004c4380, {0xf19b20?, 0x0})
github.com/F5Networks/terraform-provider-bigip/bigip/resource_bigip_ltm_virtual_address.go:156 +0x15a
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000569280, 0xc000134dc0, {0xf19b20, 0x0})
github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/resource.go:440 +0x131
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00012ebf0, {0xc000134cd0?, 0x51f946?}, 0xc000134cd0)
github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/helper/plugin/grpc_provider.go:525 +0x365
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0xee1b20?, 0xc00012ebf0}, {0x10df7b0, 0xc0002f9170}, 0xc0004063c0, 0x0)
github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/tfplugin5/tfplugin5.pb.go:3153 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001ae480, {0x10e3820, 0xc00024a000}, 0xc000326300, 0xc00008d7a0, 0x16a3370, 0x0)
google.golang.org/grpc@v1.23.0/server.go:995 +0xe1e
google.golang.org/grpc.(*Server).handleStream(0xc0001ae480, {0x10e3820, 0xc00024a000}, 0xc000326300, 0x0)
google.golang.org/grpc@v1.23.0/server.go:1275 +0xa16
google.golang.org/grpc.(*Server).serveStreams.func1.1()
google.golang.org/grpc@v1.23.0/server.go:710 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.23.0/server.go:708 +0xea

Error: The terraform-provider-bigip_v1.15.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by RavinderReddyF5** [comment]
Created Internal : INFRAANO-879 for tracking
