### ISSUE TITLE
facing error "A dns-resolver must be specified on the HTTP profile."

### ISSUE THREAD

**Issue by rakotkar0608** [F5Networks/terraform-provider-bigip#677]
When we are going to add http profile in Virtual Server properties of WAF, we are facing error "A dns-resolver must be specified on the HTTP profile."
Please help to resolve this error.

**Comment by RavinderReddyF5** [comment]
@rakotkar0608 please share terraform config and debug logs

**Comment by rakotkar0608** [comment]
We are not facing this issue now. You can close it.

**Comment by rakotkar0608** [comment]
We are not facing this issue now. You can close it.
