### ISSUE TITLE
In Our WAF architecture we need to configure the  bigip_ltm_virtual_server from the Local Traffic Menu (LTM) - missing Argument request

### ISSUE THREAD

**Issue by rakotkar0608** [F5Networks/terraform-provider-bigip#680]
### request arguments for bigip_ltm_virtual_server

In Our WAF architecture we need to configure the bigip_ltm_virtual_server from the Local Traffic Menu (LTM) - missing Argument request

We are automating the F5 WAF configuration using terraform. We are using bigip_ltm_virtual_server to add virtual servers in Local Traffic section of WAF but we haven't find any argument to pass values to Virtual Servers below Properties.
Please help and create below arguments for bigip_ltm_virtual_server.

- Protocol Profile (Client)
- Protocol Profile (Server)
- HTTP Profile (Client)
- HTTP Profile (Server)
- HTTP Compression Profile
- Web Acceleration Profile

### Describe the solution you'd like
We want the arguments for bigip_ltm_virtual_server which can assign values to below properties.

- Protocol Profile (Client)
- Protocol Profile (Server)
- HTTP Profile (Client)
- HTTP Profile (Server)
- HTTP Compression Profile
- Web Acceleration Profile

**Comment by RavinderReddyF5** [comment]
@rakotkar0608 User can specify all the required profiles using `profiles` input argument, but they need to make sure `protocol` field also specified properly based on profile type.


```
# A Virtual server with separate client and server profiles
resource "bigip_ltm_virtual_server" "https" {
  name                       = "/Common/terraform_vs_https"
  destination                = "10.255.255.254"
  description                = "VirtualServer-test"
  port                       = 443
  profiles                   = ["/Common/tcp","/Common/http"]
  client_profiles            = ["/Common/clientssl"]
  server_profiles            = ["/Common/serverssl"]
  security_log_profiles      = ["/Common/global-network"]
  source_address_translation = "automap"
}
```

**Comment by rakotkar0608** [comment]
We are checking it

**Comment by rakotkar0608** [comment]
We use this format but no luck

**Comment by RavinderReddyF5** [comment]
@rakotkar0608 can you please share terraform config file and debug logs for further debug on this issue

**Comment by rakotkar0608** [comment]
The provided code can configure only Profiles like Protocol profile (client) and HTTP Profile (client). We are not able to configure attributes like Protocol profile (server), HTTP Profile (server), HTTP Compression Profile and Web Accelelration Profile for Virtual Servers.

**Comment by rakotkar0608** [comment]
We need the attribute format to define client and server profiles for tcp and http using context.

**Comment by rakotkar0608** [comment]
Hello @RavinderReddyF5,
We are able to configure the other profiles like http compression and web acceleration profiles using below mentioned profile attribute format. But for the profiles like http and protocol, we can configure only for client context and not for server context. Please provide us attribute format to define both client and server context.

profiles    = ["/Common/tcp","/Common/http"]

**Comment by rakotkar0608** [comment]
Hello @RavinderReddyF5, please help us.

**Comment by RavinderReddyF5** [comment]
@rakotkar0608 we are tracking internally for your requests. will update as and when it completed

**Comment by G-gonzalezjimenez** [comment]
@rakotkar0608 can you provide the logs please?

**Comment by rakotkar0608** [comment]
Hi Guillermo, this has been resolved by using client profile and server profile attributes of Virtual Server.
