### ISSUE TITLE
In Our WAF architecture we need to configure the bigip_ltm_profile_http  from the Local Traffic Menu (LTM) - missing Argument request

### ISSUE THREAD

**Issue by rakotkar0608** [F5Networks/terraform-provider-bigip#681]
**request arguments for bigip_ltm_profile_http (Local Traffic -> Profiles)**

In Our WAF architecture we need to configure the bigip_ltm_profile_http from the Local Traffic Menu (LTM) - missing Argument request 

We are automating the F5 WAF configuration using terraform. We are using bigip_ltm_profile_http to add http profiles in Local Traffic section of WAF but we haven't find any argument to pass values to http profiles below Properties.
Please help and create below arguments for bigip_ltm_profile_http.

- Settings -> LWS Maximum Columns
- Enforcement -> Known Methods
- HTTP Strict Transport Security -> mode
- HTTP Strict Transport Security -> Maximum age
- HTTP Strict Transport Security -> Preload

**Describe the solution you'd like**
We want the arguments for bigip_ltm_profile_http which can assign values to below properties.

- Settings -> LWS Maximum Columns
- Enforcement -> Known Methods
- HTTP Strict Transport Security -> mode
- HTTP Strict Transport Security -> Maximum age
- HTTP Strict Transport Security -> Preload

**Comment by RavinderReddyF5** [comment]
@rakotkar0608 can you please check will this be any helpfull for your need. 
https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_waf_policy

**Comment by rakotkar0608** [comment]
We checked it but we haven't found any arguments.

**Comment by RavinderReddyF5** [comment]
@rakotkar0608 will take a look and create backlog. thanks for notifying us. i think it will be more helpful what additional parameter support u need from `bigip_waf_policy` resource

**Comment by rakotkar0608** [comment]
We have followed the page https://registry.terraform.io/providers/F5Networks/bigip/latest/docs but we haven't found any resource type. How bigip_waf_policy can help for bigip_ltm_profile_http?

**Comment by KrithikaChidambaram** [comment]
Hi, please try AS3: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/ and https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/modules_2_0/bigip_as3_deploy_module.html#bigip-as3-deploy-module-2

Closing this request now. 
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
