### ISSUE TITLE
In Our WAF architecture we need to configure the  bigip_ltm_profile_fastl4 from the Local Traffic Menu (LTM) - missing Argument request

### ISSUE THREAD

**Issue by rakotkar0608** [F5Networks/terraform-provider-bigip#682]
**request arguments for bigip_ltm_profile_fastl4 [Path: Locall Traffic -> Profiles -> Protocol -> FastL4]**

In Our WAF architecture we need to configure the bigip_ltm_profile_fastl4 from the Local Traffic Menu (LTM) - missing Argument request

We are automating the F5 WAF configuration using terraform. We are using bigip_ltm_profile_fastl4 to add FastL4 protocol profiles in Local Traffic section of WAF but we haven't find any argument to pass values to FastL4 protocol profiles below Properties.
Please help and create below arguments for bigip_ltm_profile_fastl4.

- Settings -> Loose Initiation
- Settings -> Loose Close

**Describe the solution you'd like**
We want the arguments for bigip_ltm_profile_fastl4 which can assign values to below properties.

- Settings -> Loose Initiation
- Settings -> Loose Close

**Comment by RavinderReddyF5** [comment]
Hi @rakotkar0608 ,fixed in v1.16.0 ,please verify and open new issue if any problem seen
