### ISSUE TITLE
In Our WAF architecture we need to configure the bigip_ltm_profile_httpcompress from the Local Traffic Menu (LTM) - missing Argument request

### ISSUE THREAD

**Issue by rakotkar0608** [F5Networks/terraform-provider-bigip#684]
**Request arguments for bigip_ltm_profile_httpcompress [Path: Locall Traffic -> Profiles -> Services -> HTTP Compression]**

In Our WAF architecture we need to configure the bigip_ltm_profile_httpcompress from the Local Traffic Menu (LTM) - missing Argument request

We are automating the F5 WAF configuration using terraform. We are using bigip_ltm_profile_httpcompress to add HTTP Compression services in Local Traffic section of WAF but we haven't find any argument to pass values to HTTP Compression services below Properties.
Please help and create below arguments for bigip_ltm_profile_httpcompress.

Compression -> Compression Buffer Size
Compression -> gzip Compression Level
Compression -> gzip Memory Level
Compression -> gzip Window Size
Compression -> Keep Accept Encoding

**Describe the solution you'd like**
We want the arguments for bigip_ltm_profile_httpcompress which can assign values to below properties.

Compression -> Compression Buffer Size
Compression -> gzip Compression Level
Compression -> gzip Memory Level
Compression -> gzip Window Size
Compression -> Keep Accept Encodinge

**Comment by RavinderReddyF5** [comment]
Hi @rakotkar0608 ,fixed in v1.16.0 ,please verify and open new issue if any problem seen
