### ISSUE TITLE
In Our WAF architecture we need to configure the SIP message routing session profile from the Local Traffic Menu (LTM)

### ISSUE THREAD

**Issue by rakotkar0608** [F5Networks/terraform-provider-bigip#685]
**Create BIGIP Terraform Provider Resource Type for SIP message routing seesion [Path: Local Traffic -> Profiles -> Message Routing -> SIP]**

In Our WAF architecture we need to configure the SIP message routing session profile from the Local Traffic Menu (LTM)

We are automating the F5 WAF configuration using terraform. We haven't found any resource type to create the  SIP message routing seesion [Path: Local Traffic -> Profiles -> Message Routing -> SIP] in the F5 WAF. We have to configure SIP message routing session using terraform. Please help to create BIGIP Terraform Provider resource type to create  the  SIP message routing session.

**Comment by KrithikaChidambaram** [comment]
Hi, please try AS3: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/ and https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/modules_2_0/bigip_as3_deploy_module.html#bigip-as3-deploy-module-2

Closing this request now. 
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
