### ISSUE TITLE
In Our WAF architecture we need to configure the RequestLogging profile from the Local Traffic Menu (LTM)

### ISSUE THREAD

**Issue by rakotkar0608** [F5Networks/terraform-provider-bigip#686]
**Create BIGIP Terraform Provider Resource Type for RequestLogging [Path: Local Traffic -> Profiles -> Other -> RequestLogging]**

In Our WAF architecture we need to configure the RequestLogging profile from the Local Traffic Menu (LTM)

We are automating the F5 WAF configuration using terraform. We haven't found any resource type to create RequestLogging [Path: Local Traffic -> Profiles -> Other -> RequestLogging] in the F5 WAF. We have to create and configure RequestLogging using terraform. Please help to create BIGIP Terraform Provider resource type to create the RequestLogging.

**Comment by G-gonzalezjimenez** [comment]
Hi, can you reach out on the slack channel on terraform so we can setup a meeting to discuss this and other items?

Thank you

**Comment by rakotkar0608** [comment]
Please give us the slack channel details.

**Comment by G-gonzalezjimenez** [comment]
https://f5cloudsolutions.herokuapp.com/ 

 can you  contact us directly at solutionsfeedback@f5.com with the subject GITHUB issue #686 (I know you have more open issues, but we can start tracking from there) I think the email option will be faster and we can start discussing directly there. 

Thank you

**Comment by rakotkar0608** [comment]
Sure, I am sending you the email with the details of issues
 created

**Comment by KrithikaChidambaram** [comment]
Hi, please try AS3: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/ and https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/modules_2_0/bigip_as3_deploy_module.html#bigip-as3-deploy-module-2

Closing this request now. 
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
