### ISSUE TITLE
In Our WAF architecture we need to configure the device pairing and synchronization from Device Management menu

### ISSUE THREAD

**Issue by rakotkar0608** [F5Networks/terraform-provider-bigip#688]
In Our WAF architecture we need to configure the device pairing and synchronization from Device Management menu

We are automating the F5 WAF configuration using terraform. We are using bigip_command resource type to do the WAF device pairing and synchronization where we are defining tmsh commands to configure. As checked, currently there is no terraform f5 resource type to perform this activity. Hence please create terraform f5 resource types to perform WAF device pairing and synchronization activity.

1. Resource type to create high availability configuration for waf device
2. Resource type to add waf device in trust-domain
3. Resource type for The device group (/Common/Sync) addition in partition Common
4. Resource type for The device group (/Common/sync-only) added in partition Common
5. Resource type for Synchronizing sync-only device group
6. Resource type fo Synchronizing sync device group

**Comment by KrithikaChidambaram** [comment]
Hi, please try DO: [https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/ and https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/modules_2_0/bigip_as3_deploy_module.html#bigip-as3-deploy-module-2](https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/)

Closing this request now. 
Please re-open if required or send an email to [[automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com)](mailto:[automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com)). Thanks!
