### ISSUE TITLE
In Our WAF architecture we need to configure the application security policy from the Security menu

### ISSUE THREAD

**Issue by rakotkar0608** [F5Networks/terraform-provider-bigip#695]
In Our WAF architecture we need to configure the application security policy from the Security menu

We are automating the F5 WAF configuration using terraform. We need to configure the WAF application security policy. Please help to create BIGIP terraform resource type for the same. It should configure all the security components (we can configure all the security component if we import the existing policy.)

**Comment by rakotkar0608** [comment]
we are facing error while configuring security policy using bigip_waf_policy resource type. 
Error Message: "Error: Error in Importing AWAF json (testpolicyravi): [ERROR] WafPolicy import failed with :{File: Message:Cannot read exported policy file. │ Cannot read from input file.}"

**Comment by RavinderReddyF5** [comment]
@rakotkar0608 can you please share terraform config file and debug logs ?

**Comment by vainiusd** [comment]
Hi there, jumping in on this issue too, since from the output I see that the names are from the terraform registry example so I'm hitting the same issue when testing.

Attaching min.tf and debug outputs.
[debug.txt](https://github.com/F5Networks/terraform-provider-bigip/files/9692121/debug.txt)
[main.tf.txt](https://github.com/F5Networks/terraform-provider-bigip/files/9692122/main.tf.txt)

F5 VE. Version: 14.1.2.3 Build: 0.0.5

**Comment by pgouband** [comment]
Hi @vainiusd,

Could you test with version 16.1?

**Comment by vainiusd** [comment]
Already doing an upgrade for testing since found this:
> (BIG-IP 16.1.0 and later) To save the security policy as an JSON file, select JSON format.

Will share an update.

**Comment by pgouband** [comment]
Hi @vainiusd 

A series of articles on AWAF and Terraform has started to be published since yesterday.
https://community.f5.com/t5/technical-articles/manage-f5-big-ip-advanced-waf-policies-with-terraform-intro/ta-p/300828

**Comment by vainiusd** [comment]
Verified with Version: 16.1.3.2.
Terraform examples work.

Would be great to add to Terraform registry docs that this feature only works for versions 16.1+, because under the provider this is stated:
> This provider uses the iControlREST API. All the resources are validated with BigIP v12.1.1 and above

**Comment by pgouband** [comment]
Hi @vainiusd 

Thanks for the feedback

**Comment by KrithikaChidambaram** [comment]
Hi, this documentation change has been added to our backlog. Internal tracking ID INFRAANO-912.

**Comment by pgouband** [comment]
Documentation has been updated
