### ISSUE TITLE
In Our WAF architecture we need to configure the "web acceleration" service profile from the Local Traffic Menu (LTM)

### ISSUE THREAD

**Issue by rakotkar0608** [F5Networks/terraform-provider-bigip#697]
In Our WAF architecture we need to configure the "web acceleration" service profile from the Local Traffic Menu (LTM)

We are automating the F5 WAF configuration using terraform. We haven't found any resource type to create web acceleration [Path: Local Traffic -> Profiles -> Services -> web-acceleration] in the F5 WAF. We have to create and configure web acceleration using terraform. Please help to create BIGIP Terraform Provider resource type to create the web acceleration.

**Comment by KrithikaChidambaram** [comment]
Hi, please try AS3: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/ and https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/modules_2_0/bigip_as3_deploy_module.html#bigip-as3-deploy-module-2

Closing this request now. 
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
