### ISSUE TITLE
In Our WAF architecture we need to configure the AD integration Authentication from the System Menu

### ISSUE THREAD

**Issue by rakotkar0608** [F5Networks/terraform-provider-bigip#699]
In Our WAF architecture we need to configure the AD integration Authentication from the System Menu

We are automating the F5 WAF configuration using terraform. We haven't found any resource type to setup a authentication [ PATH: System  ››  Users : Authentication] in the F5 WAF. We have to setup authentication (like AD integration) using terraform. Please help to create BIGIP Terraform Provider resource type to setup the authentication. So that domain user can login into the WAF portal using their domain credentials.

**Comment by KrithikaChidambaram** [comment]
Hi, please try DO: [https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/ and https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/modules_2_0/bigip_as3_deploy_module.html#bigip-as3-deploy-module-2](https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/)

Closing this request now. 
Please re-open if required or send an email to [[automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com)](mailto:[automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com)). Thanks!
