### ISSUE TITLE
In Our WAF architecture we need to configure the Preferences (System > Preferences) from System Menu

### ISSUE THREAD

**Issue by rakotkar0608** [F5Networks/terraform-provider-bigip#700]
In Our WAF architecture we need to configure the Preferences (System > Preferences) from System Menu

We are automating the F5 WAF configuration using terraform. We haven't found any resource type to setup  Preferences (PATH: System > Preferences) in the F5 WAF. We have to configure preferences using terraform. Please help to create BIGIP Terraform Provider resource type to configure preferences (System > Preferences).

**Comment by KrithikaChidambaram** [comment]
Hi, please try DO: [https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/ and https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/modules_2_0/bigip_as3_deploy_module.html#bigip-as3-deploy-module-2](https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/)

Closing this request now. 
Please re-open if required or send an email to [[automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com)](mailto:[automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com)). Thanks!
