### ISSUE TITLE
ltm policy rule in order to permit the configuration of a datagroup for TCP address filtering

### ISSUE THREAD

**Issue by diaconud007** [F5Networks/terraform-provider-bigip#706]
### Is your feature request related to a problem? Please describe.

With current implementation of the provider you are not able to configure a ltm_policy rule for filtering - for example -  the access to a specific context-path from a predefined list of IPs.

This could be done (manually) by configuring a rule condition to match the TCP address within a datagroup of address type:

![image](https://user-images.githubusercontent.com/45786269/195561425-21dc6f6c-dc4f-4ef7-a784-61928e54f082.png)
 

### Describe the solution you'd like
A future implementation should permit a user to fill the the name of a datagroup in a rule condition like this:

```
condition {
      tcp = true
      address          = true
      case_insensitive = true
      external         = true
      request          = true
      matches          = true
      present          = true
      remote           = true
      datagroup        = "/k8s-platformtools/test-platformops"
    }
```

**Comment by KrithikaChidambaram** [comment]
Hi, internal tracking ID for this request is: INFRAANO-933, thanks!
