### ISSUE TITLE
Use of Deprecated Option for Virtual Servers 

### ISSUE THREAD

**Issue by dugwa** [F5Networks/terraform-provider-bigip#713]
### Environment

 * TMOS/Bigip Version: 16
 * Terraform Version: 1.3.3
 * Terraform bigip provider Version: 1.14.0

### Summary

when defining my virtual_server resource, I have used the following option to define my snat-pool

```
resource "bigip_ltm_virtual_server" "vs" {
  snatpool         = "snat-pool-1234"
  source_address_translation = "snat"
  pool = "terraform-pool-8443"
}
```

This does the job very well with no issues. 

However, in the official [terraform documentation](https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_ltm_virtual_server) and also [F5 documentation](https://clouddocs.f5.com/cli/tmsh-reference/v14/modules/ltm/ltm_virtual.html), it has been mentioned that snatpool "Specifies the name of an existing SNAT pool that you want the virtual server to use to implement selective and intelligent SNATs. DEPRECATED - see Virtual Server Property Groups source-address-translation"

I will like to stop using snatpool since it has been DEPRECATED and use only source address translation (it still works but there is no point to continue using something that is deprecated)

maybe something like this ?

```
source_address_translation = {
  type = "snat-pool-xxx"
  pool = "terraform-pool-8443"
}
```

Unfortunately the snippet of code above does not work.  Instead I get this error below 

```
Inappropriate value for attribute "source_address_translation": string required.
```

Please can you advise on what I need to do to stop using this deprecated feature?

Thanks

**Comment by dugwa** [comment]
Please can anyone @ivey  @gliptak @catsby @smerrell  take a look at my request ?

Thanks

**Comment by RavinderReddyF5** [comment]
hi @dugwa, as per tmsh command guide, `snatpool` && `snat` setting is deprecated and it mapped inside of `source-address-translation`.

there is nothing like `snatpool` is deprecated. only the way tmsh command accepts inputs is changed. even though we accept inputs through different parameters `source_address_translation` translates to `source_address_translation.type`  && `snatpool` --> `source_address_translation.pool`


```
source_address_translation = {
  type = "snat"
  pool = "/Common/testsnatpool"
}
```

**Comment by RavinderReddyF5** [comment]
working for above is :
```
resource "bigip_ltm_virtual_server" "http" {
  name                       = "/Common/terraform_vs_http"
  destination                = "10.12.12.12"
  port                       = 80
  snatpool                   = "/Common/testsnatpool"
  source_address_translation = "snat"
}
```

**Comment by dugwa** [comment]
@RavinderReddyF5  - I appreciate your comment but my point is that the recommended (non-deprecated solution does not work)

```
resource "bigip_ltm_virtual_server" "http" {
  name                       = "/Common/terraform_vs_http"
  destination                = "10.12.12.12"
  port                       = 80
  snatpool                   = "/Common/testsnatpool"
  source_address_translation = "snat"
}
```

The above code clearly works but the documentation clearly states this 

```
[snatpool](https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_ltm_virtual_server#snatpool) - (Optional) Specifies the name of an existing SNAT pool that you want the virtual server to use to implement selective and intelligent SNATs. DEPRECATED - see Virtual Server Property Groups source-address-translation
```

So i have decided to use the new (non-deprecated) solution

```
resource "bigip_ltm_virtual_server" "http" {
  name                       = "/Common/terraform_vs_http"
  destination                = "10.12.12.12"
  port                       = 80
  source_address_translation = {
    type = "snat"
    pool = "/Common/testsnatpool"
  }
}
```

but then I get the this error 

```
│ Error: Incorrect attribute value type
│
│   on ../modules/f5/virtual_server.tf line 10, in resource "bigip_ltm_virtual_server" "vs":
│   10:   source_address_translation = {
│   11:     type = "snat"
│   12:     pool = "/Common/testsnatpool"
│   13:   }
│
│ Inappropriate value for attribute "source_address_translation": string required.
```

**Comment by dugwa** [comment]
@ivey @gliptak @catsby 
please can soemone advise on this ?

Thanks a lot

**Comment by dugwa** [comment]
@RavinderReddyF5 


source_address_translation is expected to be a string and not a map object. Is this expected ?

**Comment by RavinderReddyF5** [comment]
Hi @dugwa, this is implementation from terraform bigip resource side, provider plug-in internally convert this parameters from terraform resource into BIG-IP acceptable icontrol REST Json payload.

please use working config :
```
resource "bigip_ltm_virtual_server" "http" {
  name                       = "/Common/terraform_vs_http"
  destination                = "10.12.12.12"
  port                       = 80
  snatpool                   = "/Common/testsnatpool"
  source_address_translation = "snat"
}
```

**Comment by KrithikaChidambaram** [comment]
Hi, are you able use the configuration provided in the message above?

**Comment by KrithikaChidambaram** [comment]
Hi, closing this request now. 
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
