### ISSUE TITLE
bigip_ltm_monitor - custom parent monitor is not allowed

### ISSUE THREAD

**Issue by robertoo9** [F5Networks/terraform-provider-bigip#721]
Hi,

Terraform provider is not allowing to specify custom parent monitor. 
We can configure parent attribute which is pointing to built-in F5 monitor:
` parent      = "/Common/http"`

But we can't point "parent" parameter to other monitor, that was created by user :
`  parent      = "/Common/HC4_HTTP_OUR_CUSTOM_MONITOR_PARENT"`

When I try to use custom parent monitor as shown above, I get following error:
![image](https://user-images.githubusercontent.com/115872793/201062873-c9944d08-395e-4fa0-ad27-844a9387a5b0.png)

For your reference, same issue was reporet in 2019, closed as solved however for me this is still not working:
https://github.com/F5Networks/terraform-provider-bigip/issues/45

May you please try to introduce this feature?

**Environment**
TMOS/Bigip Version: 13.1.3.6
Terraform Version: 1.3.4
Terraform bigip provider Version: 1.16.0

Regards,
Robert

**Comment by KrithikaChidambaram** [comment]
Hi, internal ID to track this item is: INFRAANO-974, thanks!

**Comment by RavinderReddyF5** [comment]
HI @robertoo9 issue fixed in v1.18.0, please use : https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_ltm_monitor#custom_parent for setting custom type parent

**Comment by RavinderReddyF5** [comment]
please open new issue if v1.18.0 not solves your Requirements
