### ISSUE TITLE
Impossible importing existing datagroup resource

### ISSUE THREAD

**Issue by jazzista88** [F5Networks/terraform-provider-bigip#730]
Hello,

I have my root module calling a child module for datagroup creation.

I need to import some already existing datagroup within my terraform state but i think there is a bug.

I have reproduced the recource in this way:
```
resource "bigip_ltm_datagroup" "test_datagroup" {
  name        = "/Common/test"
  type        = "string"
  record {
    name = "key1"
    data = "value1"
  }
}
```

the resource on the F5 is existing, just created for test, then launched the following command to import the resource:

`terraform import module.root-apitools.bigip_ltm_datagroup.test_datagroup /Common/test`

I always get:
```
module.root-apitools.bigip_ltm_datagroup.test_datagroup: Import prepared!
  Prepared bigip_ltm_datagroup for import
module.root-apitools.bigip_ltm_datagroup.test_datagroup: Refreshing state... [id=/Common/test]
```

But every time at the end of the process i got:

```
╷
│ Error: Cannot import non-existent remote object
│
│ While attempting to import an existing object to "module.root-apitools.bigip_ltm_datagroup.test_datagroup", the provider detected that no object exists with the given id. Only pre-existing objects can be
│ imported; check that the id is correct and that it is associated with the provider's configured region or endpoint, or use "terraform apply" to create a new remote object for this resource.
╵
```

It seems i am not giving the right id.

Since i have created from scratch with terraform a new datagroup before, for other purpose, i tried to inspect it.

```
tf state show module.root-apitools.bigip_ltm_datagroup.api_backend_datagroup
```

and i see that the id is the following:

```
resource "bigip_ltm_datagroup" "api_backend_datagroup" {
    id       = "/DEV/api_be_pools"
    internal = true
    name     = "/DEV/api_be_pools"
    type     = "string"

    record {
.....
```

But again, by using that id format so /DEV/<datagroup_name> the import is not working.

Is there any way to solve this issue?
Thanks

**Comment by yunal** [comment]
Hi, I'm not a developer here and I have my own problems with this provider. I have been able to import VIPs, pools and nodes by just providing the the name attribute inside the resource in the skeleton tf file. Nothing else.  I've never tried data groups though.

**Comment by jazzista88** [comment]
Hello @yunal thanks for your reply.

Yes i have imported an already existing pool attachments with no problems, but when i try doing the same with datagroups i get that message.

**Comment by RavinderReddyF5** [comment]
Hi @jazzista88 , identified issue, this is because of by default import is picking data group type as external, which making import fail.

**Comment by jazzista88** [comment]
Hello @RavinderReddyF5 
This means i should reproduce a resource on my terraform files with internal = false?

**Comment by RavinderReddyF5** [comment]
HI @jazzista88, yes there is bug which needs to fixed for importing datagroups

**Comment by KrithikaChidambaram** [comment]
Hi, thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1106, thanks!
