### ISSUE TITLE
trying to deploy with port variable -> contains invalid UTF-8

### ISSUE THREAD

**Issue by de1chk1nd** [F5Networks/terraform-provider-bigip#732]
### Environment

 * TMOS/Bigip Version: 16.1.3
 * Terraform Version: v1.3.5
 * Terraform bigip provider Version: v1.15.2

### Summary

I have some scripts to deploy bigip in aws and than run some other terraform scripts via bigip provider. Everything worked fine, since recently.

When I try to deploy some virtual server, pools etc, I get following error, when plan/apply the scripts:

> │ Error: Plugin error
> │
> │   with provider["registry.terraform.io/f5networks/bigip"],
> │   on provider.tf line 1, in provider "bigip":
> │    1: provider "bigip" {
> │
> │ The plugin returned an unexpected error from plugin.(*GRPCProvider).ConfigureProvider: rpc error: code = Internal desc = grpc: error while marshaling: proto: field "tfplugin5.Diagnostic.Summary" contains invalid UTF-8
> 

I assume it is related to the port - when removing single variables, it "works" (in context of the utf8), until I add/remove the port.

### Steps To Reproduce

1. Provide terraform resource config which you are facing trouble along with the output of it.

```
provider "bigip" {
  address  = var.hostname
  username = var.username
  password = var.password
  port     = var.port
}

terraform {
  required_providers {
    bigip = {
      source  = "F5Networks/bigip"
      version = "1.15.2"

    }
    random = {
      source  = "hashicorp/random"
      version = ">2.3.0"
    }
    template = {
      source  = "hashicorp/template"
      version = ">2.1.2"
    }
    null = {
      source  = "hashicorp/null"
      version = ">2.1.2"
    }
    local = {
      source  = "hashicorp/local"
      version = "2.1.0"
    }
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.8.0"
    }
  }
}
```

3. To get to know more about the issue, provide terraform debug logs

see attachment

### Expected Behavior
can apply tf scripts

### Actual Behavior
stops after tf apply with utf8 error (see above)

[tf-debug.txt](https://github.com/F5Networks/terraform-provider-bigip/files/10094853/tf-debug.txt)

**Comment by KrithikaChidambaram** [comment]
Hi, can you provide main.tf and providers.tf files?

**Comment by KrithikaChidambaram** [comment]
Closing this now. Reopen if you still face the issue. Thanks!
