### ISSUE TITLE
bigip provider version 1.15.0 crashes with error "The plugin encountered an error and failed to respond to the plugin. (*GRPCProvider).ApplyResourceChange call."

### ISSUE THREAD

**Issue by samnuga** [F5Networks/terraform-provider-bigip#733]
### Environment

 * TMOS/Bigip Version: BIG-IP 16.1.3 Build 0.0.12 Final
 * Terraform Version: 1.2.5
 * Terraform bigip provider Version: 1.15.0

### Summary

Communication with plugin error appears when creating a new HTTP profile.
"The plugin encountered an error and failed to respond to the plugin. (*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details."

### Steps To Reproduce

1. Provide terraform resource config which you are facing trouble along with the output of it.

resource "bigip_ltm_profile_http" "f5vm02-rechunk-http" {
  name                  = "/Common/rechunk-http"
  defaults_from         = "/Common/http"
  response_chunking     = "rechunk"
}

3. To get to know more about the issue, provide terraform debug logs

4. To capture debug logs, export TF_LOG variable with debug ( export TF_LOG= DEBUG ) before 
  runnning terraform apply/plan

> │ Error: Plugin did not respond
> │ 
> │   with bigip_ltm_profile_http.f5vm01_rechunk_http,
> │   on profiles.tf line 35, in resource "bigip_ltm_profile_http" "f5vm01_rechunk_http":
> │   35: resource "bigip_ltm_profile_http" "f5vm01_rechunk_http" {
> │ 
> │ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
> ╵
> ╷
> │ Error: Plugin did not respond
> │ 
> │   with bigip_ltm_profile_http.f5vm02_rechunk_http,
> │   on profiles.tf line 75, in resource "bigip_ltm_profile_http" "f5vm02_rechunk_http":
> │   75: resource "bigip_ltm_profile_http" "f5vm02_rechunk_http" {
> │ 
> │ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
> ╵
> 
> Stack trace from the terraform-provider-bigip_v1.15.0 plugin:
> 
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x131439f]
> 
> goroutine 83 [running]:
> github.com/f5devcentral/go-bigip.(*BigIP).APICall(0x0, 0xc00045d438)
> 	github.com/f5devcentral/go-bigip@v0.0.0-20220707052421-ba37a3db5d51/bigip.go:177 +0x7f
> github.com/f5devcentral/go-bigip.(*BigIP).post(0x1b1c6ba?, {0x1978320?, 0xc0000001e0?}, {0xc00045d5a0, 0x3, 0x3})
> 	github.com/f5devcentral/go-bigip@v0.0.0-20220707052421-ba37a3db5d51/bigip.go:284 +0x148
> github.com/f5devcentral/go-bigip.(*BigIP).AddHttpProfile(...)
> 	github.com/f5devcentral/go-bigip@v0.0.0-20220707052421-ba37a3db5d51/ltm.go:3712
> github.com/F5Networks/terraform-provider-bigip/bigip.resourceBigipLtmProfileHttpCreate(0x19e6360?, {0x1af61e0?, 0x0?})
> 	github.com/F5Networks/terraform-provider-bigip/bigip/resource_bigip_ltm_profile_http.go:214 +0x1cf
> github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0001b2a80, 0xc0004b2aa0, 0xc0004010a0, {0x1af61e0, 0x0})
> 	github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/resource.go:305 +0x438
> github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000418800, 0xc00045d810, 0x1b04106?, 0xf?)
> 	github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/provider.go:294 +0x70
> github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00013e8d0, {0xc00069e300?, 0x1114ec6?}, 0xc00069e300)
> 	github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/helper/plugin/grpc_provider.go:885 +0x7c5
> github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1abf1c0?, 0xc00013e8d0}, {0x1cb0480, 0xc00046d8c0}, 0xc00069e2a0, 0x0)
> 	github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x170
> google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001bc480, {0x1cb34b0, 0xc0001c8000}, 0xc0000fee00, 0xc000581170, 0x225f2c0, 0x0)
> 	google.golang.org/grpc@v1.23.0/server.go:995 +0xe07
> google.golang.org/grpc.(*Server).handleStream(0xc0001bc480, {0x1cb34b0, 0xc0001c8000}, 0xc0000fee00, 0x0)
> 	google.golang.org/grpc@v1.23.0/server.go:1275 +0xa05
> google.golang.org/grpc.(*Server).serveStreams.func1.1()
> 	google.golang.org/grpc@v1.23.0/server.go:710 +0x98
> created by google.golang.org/grpc.(*Server).serveStreams.func1
> 	google.golang.org/grpc@v1.23.0/server.go:708 +0xea
> 
> Error: The terraform-provider-bigip_v1.15.0 plugin crashed!
> 
> This is always indicative of a bug within the plugin. It would be immensely
> helpful if you could report the crash with the plugin's maintainers so that it
> can be fixed. The output above should help diagnose the issue.

5. As3/DO json along with the resource config( for AS3/DO resource issues )

### Expected Behavior
A new profile named http_rechunk should be created like:

> resource "bigip_ltm_profile_http" "f5vm01_rechunk_http" {
>   name                  = "/Common/rechunk_http"
>   defaults_from         = "/Common/http"
>   response_chunking     = "rechunk"
> }

### Actual Behavior
A clear and concise description of what actually happens.
Please include any applicable error output.

> │ Error: Plugin did not respond
> │ 
> │   with bigip_ltm_profile_http.f5vm02_rechunk_http,
> │   on profiles.tf line 75, in resource "bigip_ltm_profile_http" "f5vm02_rechunk_http":
> │   75: resource "bigip_ltm_profile_http" "f5vm02_rechunk_http" {
> │ 
> │ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.

**Comment by RavinderReddyF5** [comment]
Hi @samnuga ,
i am not able to reproduce this issue, just try on latest version of provider

```
resource "bigip_ltm_profile_http" "f5vm02-rechunk-http" {
  name = "/Common/rechunk-http"
  defaults_from = "/Common/http"
  response_chunking = "rechunk"
}
```

**Comment by samnuga** [comment]
Hi @RavinderReddyF5 !
I have upgraded the provider version and that error is not appearing anymore.
However I have another odd error:

│ Error: Post "https:///mgmt/tm/ltm/profile/http": http: no Host in request URL
│ 
│   with bigip_ltm_profile_http.f5vm01_rechunk_http,
│   on profiles.tf line 35, in resource "bigip_ltm_profile_http" "f5vm01_rechunk_http":
│   35: resource "bigip_ltm_profile_http" "f5vm01_rechunk_http" {

I was wondering if the Error message has a typo mistake when post the message (it uses https:///)

**Comment by samnuga** [comment]
another issue will be opened to deal with this new error.
