### ISSUE TITLE
Error when creating a new http profile: http: no Host in request URL

### ISSUE THREAD

**Issue by samnuga** [F5Networks/terraform-provider-bigip#743]
**Environment**
TMOS/Bigip Version: BIG-IP 16.1.3 Build 0.0.12 Final
Terraform Version: 1.2.5
Terraform bigip provider Version: 1.15.2
**Summary:**
HTTP profile is not created and terraform apply fails with error:
_│ Error: Post "https:///mgmt/tm/ltm/profile/http": http: no Host in request URL
│
│ with bigip_ltm_profile_http.f5vm01_rechunk_http,
│ on profiles.tf line 35, in resource "bigip_ltm_profile_http" "f5vm01_rechunk_http":
│ 35: resource "bigip_ltm_profile_http" "f5vm01_rechunk_http" {_

**Steps To Reproduce**

Provide terraform resource config which you are facing trouble along with the output of it.
_resource "bigip_ltm_profile_http" "f5vm02-rechunk-http" {
name = "/Common/rechunk-http"
defaults_from = "/Common/http"
response_chunking = "rechunk"
}_

To get to know more about the issue, provide terraform debug logs

To capture debug logs, export TF_LOG variable with debug ( export TF_LOG= DEBUG ) before
runnning terraform apply/plan

**Comment by samnuga** [comment]
Can anyone take a look on this?

**Comment by RavinderReddyF5** [comment]
Hi @samnuga,can you please try it on latest provider bigip v1.16.1 ?

**Comment by samnuga** [comment]
Hi @RavinderReddyF5 ,

I tried upgrading to 1.16.1 but the error still persists.

**Comment by RavinderReddyF5** [comment]
Hi @samnuga ca you please provide complete reproduction steps of issue?

**Comment by samnuga** [comment]
Hi @RavinderReddyF5,
We create the resource under the profiles file:

_resource "bigip_ltm_profile_http" "f5vm02_rechunk_http" {
  name                  = "/Common/rechunkhttp"
  defaults_from         = "/Common/http"
  response_chunking     = "Rechunk"
}_

This resource is then attached to the vs,

_resource "bigip_ltm_virtual_server" "f5vm02_vs_github_test_443" {
  provider                   = bigip.f5vm02
  name                       = "/Common/vs_github_test_443"
  source_address_translation = "automap"
  destination                = var.public_vip
  port                       = "443"
[...]
  pool                       = bigip_ltm_pool.f5vm02_github_test_pool_443.name
  ip_protocol                = "tcp"
  /*profiles                   = ["/Common/tcp","/Common/stream"]*/
  profiles                   = ["/Common/tcp",bigip_ltm_profile_http.f5vm02_rechunk_http.name,"/Common/stream"]
[...]_

After this we run the plan by means of atlantis and then the apply.
The result is always the same.

**Comment by RavinderReddyF5** [comment]
Hi @samnuga , i tried using below config, i didnot see any issue, may be are u using provider bigip with deploying BIG-IP in any cloud ? are you referencing proper dependency ?
```
resource "bigip_ltm_profile_http" "f5vm02-rechunk-http" {
  name = "/Common/rechunk-http"
  defaults_from = "/Common/http"
  response_chunking = "rechunk"
}

# A Virtual server with separate client and server profiles
resource "bigip_ltm_virtual_server" "https" {
  name                       = "/Common/vs_github_test_443"
  destination                = "10.255.255.254"
  description                = "VirtualServer-test"
  port                       = 443
  profiles                   = ["/Common/tcp",bigip_ltm_profile_http.f5vm02-rechunk-http.name]
  client_profiles            = ["/Common/clientssl"]
  server_profiles            = ["/Common/serverssl"]
  security_log_profiles      = ["/Common/global-network"]
  source_address_translation = "automap"
}
```

**Comment by samnuga** [comment]
Hi @RavinderReddyF5,

We are deploying this infra in GCP
Do you have the list of dependencies? I'm not sure what dependencies could be missing.

**Comment by RavinderReddyF5** [comment]
HI @samnuga, created example [here](https://github.com/F5Networks/terraform-gcp-bigip-module/tree/main/examples/bigip_gcp_1nic_deploy_provider_integration) and run it through without any issues. please let me know did i miss anything.

**Comment by pgouband** [comment]
Hi, closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
