### ISSUE TITLE
missing source_address_translation property when doing "terraform import" of bigip_ltm_virtual_server

### ISSUE THREAD

**Issue by niclan** [F5Networks/terraform-provider-bigip#755]
### Environment

 * TMOS/Bigip Version: 15.1.8
 * Terraform Version: 1.3.7
 * Terraform bigip provider Version: v1.16.1

### Summary

When doing `terraform import` of a `bigip_ltm_virtual_server` the `source_address_translation` property is not included.

### Steps To Reproduce

1. Set up a VIP resource with a Source Address Translation setting of "Auto Map". Mine is called `socialcanvas_vgnett_no-https`.

![image](https://user-images.githubusercontent.com/1439524/212004598-d86c33ab-2bb1-48c8-a62d-4bf5ec1f2775.png)

2. Put this in a .tf file along with setup and authentication

```
resource "bigip_ltm_virtual_server" "socialcanvas_vgnett_no-https" {
  name       = "/Common/socialcanvas.vgnett.no-https"
}
```

3. Run `terraform import bigip_ltm_virtual_server.socialcanvas_vgnett_no-https /Common/socialcanvas.vgnett.no-https`

4. `terraform show` now show the imported resource with all relevant properties.

```
$ terraform show
# bigip_ltm_virtual_server.socialcanvas_vgnett_no-https:
resource "bigip_ltm_virtual_server" "socialcanvas_vgnett_no-https" {
    client_profiles       = [
        "/Common/auto2_vgnett.no",
        "/Common/mptcp-mobile-optimized",
    ]
    description           = "socialcanvas.vgnett.no https"
    destination           = "195.88.55.57"
    id                    = "/Common/socialcanvas.vgnett.no-https"
    ip_protocol           = "tcp"
    irules                = [
        "/Common/add_X-VG-ClientInfo",
    ]
    mask                  = "255.255.255.255"
    name                  = "/Common/socialcanvas.vgnett.no-https"
    policies              = []
    pool                  = "/Common/red-apps-01"
    port                  = 443
    profiles              = [
        "/Common/http",
    ]
    security_log_profiles = []
    server_profiles       = [
        "/Common/tcp-lan-optimized",
    ]
    source                = "0.0.0.0/0"
    source_port           = "preserve"
    state                 = "enabled"
    translate_address     = "enabled"
    translate_port        = "enabled"
    vlans                 = []
    vlans_enabled         = false
}
```

But the `source_address_translation` property is not included.  This is true for all bigip_ltm_virtual_server resources in our environment.

Without this setting VIPs will not work in our environment.

### Expected Behavior

I expect `source_address_translation` to be included.

### Actual Behavior

As stated above.

**Comment by niclan** [comment]
I checked the terraform.tfstate file.  It has this after the import:
```
            "source_address_translation": null,
```
so it looks like the importer does not handle this property.

**Comment by KrithikaChidambaram** [comment]
Hi, thanks for reporting. Internal tracking ID for this issue is: INFRAANO-1049, thanks!
