### ISSUE TITLE
Error during WAF policy deployment when setting file_types

### ISSUE THREAD

**Issue by olegmukhin** [F5Networks/terraform-provider-bigip#765]
### Environment

 * TMOS/Bigip Version: 16.1.3
 * Terraform Version: 1.3.7
 * Terraform bigip provider Version: 1.16.2

### Summary

Providing the file_types block (with any name/type values) will cause the WAF policy deployment to fail with following error:

╷

│ Error: Error in Importing AWAF json (waf_policy_name): [ERROR] WafPolicy import failed with :{File: Message:Could not parse/validate the File Type.  Invalid value 'bak' for field 'type'.}

│

│   with bigip_waf_policy.waf-policy,

│   on [main.tf](http://main.tf/) line 24, in resource "bigip_waf_policy" "waf-policy":

│   24: resource "bigip_waf_policy" "waf-policy" {

│

╵

### Steps To Reproduce

Setting the file_types block with a name value will cause this issue.

On [line 487 of the resource_bigip_awaf_policy.go](https://github.com/F5Networks/terraform-provider-bigip/blob/master/bigip/resource_bigip_awaf_policy.go#L487) name is being passed to the file_types type which is causing this error.

### Expected Behavior
Deployment of WAF policy with file types configured.

### Actual Behavior
Error.

**Comment by RavinderReddyF5** [comment]
Hi @olegmukhin fixed in v1.17.0

**Comment by olegmukhin** [comment]
@RavinderReddyF5 tested the new provider and issue appears resolved. thanks!
