### ISSUE TITLE
Add Bot Profile resource with template argument

### ISSUE THREAD

**Issue by olegmukhin** [F5Networks/terraform-provider-bigip#775]
### Is your feature request related to a problem? Please describe.
Bigip Terraform module does not currently support configuring Bot Profiles. We have a requirement to deploy a (Bot Profile using the relaxed template) to the BIG-IP. 

### Describe the solution you'd like
A bot profile resource should be added to the bigip Terraform provider, which supports selection of [template](https://clouddocs.f5.com/cli/tmsh-reference/v15/modules/security/security_bot-defense_profile.html#:~:text=template%20%5Bbalanced%20%7C%20relaxed%20%7C%20strict%5D).

### Describe alternatives you've considered
We have considered doing this using AS3, however there is also no support for deploying a Bot Profile using the relaxed template (see related enhancement request: https://github.com/F5Networks/f5-appsvcs-extension/issues/674). We believe that this functionality should be implemented in the bigip Terraform provider instead.

It is possible to deploy a Bot Profile using the [restapi provider](https://registry.terraform.io/providers/Mastercard/restapi/latest) but this is just a workaround and should not be a long term solution.

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1416.
