### ISSUE TITLE
panic: runtime error:failed to respond to the plugin.(*GRPCProvider).ConfigureProvider call

### ISSUE THREAD

**Issue by skathiresan-hw** [F5Networks/terraform-provider-bigip#785]
### Environment

TMOS/Bigip Version: 16.1.2
Terraform Version: 1.3.9
Terraform bigip provider Version: 1.16.2

### Summary

Creating any resource in bigIP we get this error

### Steps To Reproduce

1. Provide terraform resource config which you are facing trouble along with the output of it.

Terraform v1.3.9
on linux_amd64
+ provider registry.terraform.io/f5networks/bigip v1.16.2

resource "bigip_ltm_datagroup" "datagroup" {
  name = "/Common/test-dg"
  type = "string"
  record {
    name = "abc.com"
    data = "pool1"
  }
  record {
    name = "test"
    data = "123"
  }
}

Initializing the backend...

Initializing provider plugins...
- Finding f5networks/bigip versions matching "1.16.2"...
- Installing f5networks/bigip v1.16.2...
- Installed f5networks/bigip v1.16.2

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

---
go version go1.18.9 linux/amd64

### Expected Behavior
deploy f5 resources using tf

### Actual Behavior
A clear and concise description of what actually happens.
Please include any applicable error output.

Terraform plan/apply throws an error.

╷
│ Error: Plugin did not respond
│
│   with provider["registry.terraform.io/f5networks/bigip"],
│   on provider.tf line 1, in provider "bigip":
│    1: provider "bigip" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ConfigureProvider call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-bigip_v1.16.2 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x726c76]

goroutine 30 [running]:
github.com/f5devcentral/go-bigip.(*BigIP).APICall(0xc0003460e0, 0xc000271628)
	github.com/f5devcentral/go-bigip@v0.0.0-20230130103147-d518375c1a35/bigip.go:244 +0x416
github.com/f5devcentral/go-bigip.NewTokenSession(0xc0002717a0)
	github.com/f5devcentral/go-bigip@v0.0.0-20230130103147-d518375c1a35/bigip.go:181 +0x31a
github.com/F5Networks/terraform-provider-bigip/bigip.Client(0xc0002717a0)
	github.com/F5Networks/terraform-provider-bigip/bigip/config.go:28 +0x6e
github.com/F5Networks/terraform-provider-bigip/bigip.providerConfigure(0xf4a01f?, {0xc000316060, 0x5})
	github.com/F5Networks/terraform-provider-bigip/bigip/provider.go:192 +0x385
github.com/F5Networks/terraform-provider-bigip/bigip.Provider.func1(0xc00050e2d0?)
	github.com/F5Networks/terraform-provider-bigip/bigip/provider.go:169 +0x3c
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Configure(0xc000623a80, 0xc000520208?)
	github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/provider.go:275 +0xbd
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).Configure(0xc0005201d8, {0xc0001fe240?, 0x59d806?}, 0xc0001fe240)
	github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/helper/plugin/grpc_provider.go:487 +0x1d2
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_Configure_Handler({0xef7320?, 0xc0005201d8}, {0x10fbc50, 0xc0000972c0}, 0xc0000827e0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/tfplugin5/tfplugin5.pb.go:3135 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000188480, {0x10ffcc0, 0xc0004de000}, 0xc00063c700, 0xc0005821e0, 0x16c5398, 0x0)
	google.golang.org/grpc@v1.23.0/server.go:995 +0xe1e
google.golang.org/grpc.(*Server).handleStream(0xc000188480, {0x10ffcc0, 0xc0004de000}, 0xc00063c700, 0x0)
	google.golang.org/grpc@v1.23.0/server.go:1275 +0xa16
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.23.0/server.go:710 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.23.0/server.go:708 +0xea

Error: The terraform-provider-bigip_v1.16.2 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by KrithikaChidambaram** [comment]
Hi, we are tracking this internally: INFRAANO-1120, thanks!

**Comment by RavinderReddyF5** [comment]
Hi @skathiresan-hw,
i don't see any issue. please provide reproduction steps

```
 # bigip_ltm_datagroup.datagroup will be created
  + resource "bigip_ltm_datagroup" "datagroup" {
      + id       = (known after apply)
      + internal = true
      + name     = "/Common/test-dg"
      + type     = "string"

      + record {
          + data = "123"
          + name = "test"
        }
      + record {
          + data = "pool1"
          + name = "abc.com"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

bigip_ltm_datagroup.datagroup: Creating...
bigip_ltm_datagroup.datagroup: Creation complete after 1s [id=/Common/test-dg]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by pgouband** [comment]
Hi @skathiresan-hw,

As there is no feedback, I'll close it.
