### ISSUE TITLE
Add ability to allow/disallow file_types for WAF policy

### ISSUE THREAD

**Issue by olegmukhin** [F5Networks/terraform-provider-bigip#799]
### Is your feature request related to a problem? Please describe.
We have different WAF baselines, some of which whitelist specific file types for a WAF policy. Currently, all file extensions passed via the file_types argument of the bigip_waf_policy resource are blocked and cannot be set to be allowed (i.e. whitelisted).

### Describe the solution you'd like
We would like the file_types block to allow setting the [allowed boolean value](https://clouddocs.f5.com/products/waf-declarative-policy/declarative_policy_v16_1.html#filetypes) defined in the WAF declarative schema.

### Describe alternatives you've considered
We do not see any other way to achieve allowing file types with the Terraform provider.

### Additional context
N/A

**Comment by pgouband** [comment]
Hi,
internal ID to track this request is: INFRAANO-1156
thanks!
