### ISSUE TITLE
Supporting F5OS-A

### ISSUE THREAD

**Issue by HSoulat** [F5Networks/terraform-provider-bigip#804]
There is no Terraform provider for F5OS-A, for now only an Ansible project exists. As this new platform is API ready a provider could be useful to manage the appliance system in addition of bigip vCMP.

**Comment by pgouband** [comment]
Thanks for this feedback. F5OS provider is in our roadmap but we don’t have an ETA at the moment.

**Comment by RavinderReddyF5** [comment]
Hi @HSoulat please find F5OS provider here: https://registry.terraform.io/providers/F5Networks/f5os/latest
