### ISSUE TITLE
Cannot update cert and key once both are changed

### ISSUE THREAD

**Issue by slawekww** [F5Networks/terraform-provider-bigip#813]
### Environment

 * TMOS/Bigip Version: BIG-IP v16.1.3.2 (Build 0.0.4)
 * Terraform Version: 1.3.9
 * Terraform bigip provider Version: 1.17.1

### Summary

Once SSL cert and key is changed, it cannot be modified on F5:
- first run completed with err
- the next run completed with success but TF does not detected that SSL cert is not really updated on F5
 
Cert is not even used by any SSL profile on F5 and it is self-signed cert (just created for testing however problem is seen for all types of SSL certificates).

### Steps To Reproduce

1. Provide terraform resource config which you are facing trouble along with the output of it.

```hcl
data "azurerm_key_vault_certificate_data" "cert" {

  name         = "certficate-test"
  key_vault_id = "myazurekeyvault"
}

resource "bigip_ssl_certificate" "cert" {

  name      = "ssl-test-certificate"
  content   = data.azurerm_key_vault_certificate_data.cert.pem
  partition = "partition"
}

resource "bigip_ssl_key" "key" {
  name      =  "ssl-test-key"
  content   = data.azurerm_key_vault_certificate_data.cert.key
  partition = "partition"
}
```

2. To get to know more about the issue, provide terraform debug logs

3. To capture debug logs, export TF_LOG variable with debug ( export TF_LOG= DEBUG ) before 
  runnning terraform apply/plan

I may try to collect debug logs but afraid to share sensitive information.

4. As3/DO json along with the resource config( for AS3/DO resource issues ): N/A

### Expected Behavior
SSL cert should be able to modify regarless if key/cert is changed and if it is already used by any SSL profile at F5.

### Actual Behavior

Error:
```
module.f5.bigip_ssl_certificate.cert: Modifying... [id=ssl-test-certificate]
╷
│ Error: error in Importing certificate (ssl-test-certificate): HTTP 400 :: {"code":400,"message":"01070317:3: profile /partition/ssl-test-certificate's  key(/partition/ssl-test-key) and certificate(/partition/ssl-test-certificate) do not match.","errorStack":[],"apiError":3}
│ 
│   with module.f5.bigip_ssl_certificate.cert,
│   on ../../modules/f5/certs.tf line 8, in resource "bigip_ssl_certificate" "cert":
│    8: resource "bigip_ssl_certificate" "cert" {
```

**Comment by G-gonzalezjimenez** [comment]
Thank you for reporting, tracking internally with 1188

**Comment by RavinderReddyF5** [comment]
Hi @slawekww I think this is duplicate of https://github.com/F5Networks/terraform-provider-bigip/issues/562, it will be same behaviour through iControl REST, if you want to update certificate/key please deference it from profile and update.

this behaviour you will see from GUI as well:

<img width="912" alt="image" src="https://github.com/F5Networks/terraform-provider-bigip/assets/45624469/1c8a51b4-abc4-40e1-92e4-3f6e200f6923">

**Comment by slawekww** [comment]
HI @RavinderReddyF5, my use case is the following:
1. cert/key is added by TF to F5, it is not used in any SSL profile
2. cert/key is changed in the same time e.g. Azure KeyVault contains new cert/key (maybe new CA for cert)

In this case, TF is not able to update cert on F5.
I do not think so it is related to #562.
For now, I have no chance to check if this scenario works via ansible https://docs.ansible.com/ansible/latest/collections/f5networks/f5_modules/bigip_ssl_certificate_module.html

**Comment by slawekww** [comment]
Hi, I've double tested scenario.
If certificate/key is attached to SSL profile, certificate/key cannot be changed via TF and F5 UI - it is consistent.
Once certificate/key is detached from SSL profile, it is possible to change certificate/key via TF.
The only problem is automation in TF how to make it consistent - as SSL profile depends on ssl_cert and ssl_key,
during cert update it should detached from SSL profile - I do not know how to automate it.

Only way I may see is to change cert/key name in F5 so F5 would try to remove old cert and create new entry in F5.
Anyway lets close this issue.
