### ISSUE TITLE
Use of ssh keys for authentication in bigip provider

### ISSUE THREAD

**Issue by manutn1988** [F5Networks/terraform-provider-bigip#816]
_**provider.tf**_
__________

```
terraform {
  required_providers {
    bigip = {
      source = "terraform-providers/bigip"
    }
  }
  required_version = ">= 0.13"
}

provider "bigip" {
  address  = "xx.xx.xx.xxx"
  username = "admin"
  password = "/Users/xyz/abc/keys/mykeys.ppk"
}
```

**_main.tf_**
__________

```
resource "bigip_command" "test-command" {
  commands = ["show sys version"]
}

```

We have enabled ssh key based authentication on F5 server and does not have password based login. I am trying to pass ssh keys path to "password" argument in provider block. But it does not work. 

How can authenticate with ssh keys using bigip provider?

**Comment by pgouband** [comment]
Hi @manutn1988,

If I understand correctly, you have enabled remote authentication with SSL-based authentication following:
https://techdocs.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/tmos-implementations-13-0-0/10.html

Useful link:
https://cdn.f5.com/websites/devcentral.f5.com/downloads/icontrol-rest-api-user-guide-16-1-0.pdf

From page 21/22:
Note: Before you make a REST request using token-based authentication, you must obtain a token from an external authentication provider.

From:
https://registry.terraform.io/providers/F5Networks/bigip/latest/docs

the two following parameters can be used with LDAP remote auth to get a token.

token_auth - (Optional, Default false) Enable to use an external authentication source (LDAP, TACACS, etc). Can be set via the BIGIP_TOKEN_AUTH environment variable.
token_value - (Optional) A token generated outside the provider, in place of password

**Comment by manutn1988** [comment]
@pgouband Sorry, No i have not enabled SSL-based authentication. 

I use SSH Public Key to login to Big IP server. And not enabled **PasswordAuthentication**

**Comment by pgouband** [comment]
Hi @manutn1988,

Terraform is using iControl Rest so it's HTTPS not SSH.
