### ISSUE TITLE
EOF Error with BigIP v17.10.1 running FIPS 

### ISSUE THREAD

**Issue by JPatC** [F5Networks/terraform-provider-bigip#817]
### Environment

 * TMOS/Bigip Version: BIG-IP 17.1.0.1 Build 0.0.4 Point Release 1 Cryptographic Module for BIG-IP 
 * Terraform Version: 1.4.4
 * Terraform bigip provider Version: 1.12.2

### Summary

We receive an EOF error when trying to connect to our VE BIGIPs running with the FIPS module and version 17.1.0.1 of the software. We had no issues with 17.1.0.0 but a mere patch upgrade with no code changes and now we cannot connect.

### Steps To Reproduce
All we did was patch the device to 17.1.0.1 and now we get this EOF error. Here's our Code:
provider "bigip" {
alias = "f5-provider-for-az-A"
address = "f5-mgmt-01.${var.domain}"
username = jsondecode(data.aws_secretsmanager_secret_version.f5_creds.secret_string).adm_user_01
password = jsondecode(data.aws_secretsmanager_secret_version.f5_creds.secret_string).adm_pass_01
}

here's the error:
Error: Get "https://f5-mgmt-01.example.com/mgmt/tm/net/self": EOF
│
│ with provider["registry.terraform.io/f5networks/bigip"].f5-provider-for-az-A,
│ on phase2.tf line 8, in provider "bigip":
│ 8: provider "bigip" {
│
╵
We can run a curl with the user and password without issue. Also, when we tested the exact code against our lab instances without FIPS, they work fine. Anyone know when they'll be added v17 support to this module? Also before patching, to 17.1.01 this worked fine with version v17.1.0.0

We use an internal enterprise certificate but adding the root CA and intermediary CA trust is part of our build 

### Expected Behavior
We can run the provider and query Get "https://f5-mgmt-01.example.com/mgmt/tm/net/self"

### Actual Behavior
Error: Get "https://f5-mgmt-01.example.com/mgmt/tm/net/self": EOF

**Comment by ghost** [comment]
I ran into the same issue when using F5Networks/bigip provider v18, The version is BIG-IP 13.1.5.1.

Authentication required!
│
│ │ │ This server could not verify that you are authorized to access │ the URL "/mgmt/tm/net/self". │ You either supplied the wrong credentials (e.g., bad password), or your │ browser doesn't understand how to supply the credentials required. │ │

│
│ │ │ In case you are allowed to request the document, please │ check your user-id and password and try again. │ │

│ │
Error 401
│ Wed Jun 14 09:30:31 2023
│ │ │
Any suggestion?
The user is administrator and the password does not contain special characters or spaces.

**Comment by ghost** [comment]
> I ran into the same issue when using F5Networks/bigip provider v18, The version is BIG-IP 13.1.5.1.
> 
> Authentication required! │ │ │ │ This server could not verify that you are authorized to access │ the URL "/mgmt/tm/net/self". │ You either supplied the wrong credentials (e.g., bad password), or your │ browser doesn't understand how to supply the credentials required. │ │
> 
> │ │ │ │ In case you are allowed to request the document, please │ check your user-id and password and try again. │ │
> 
> │ │ Error 401 │ Wed Jun 14 09:30:31 2023 │ │ │ Any suggestion? The user is administrator and the password does not contain special characters or spaces.

It works fine with external token

terraform {
  required_providers {
    bigip = {
      source = "F5Networks/bigip"
      version = "1.18.0"
    }
  }
}
provider "bigip" {
    address  = var.f5_hostname
    username = var.f5_username
    token_auth = "true"
    token_value = var.f5_token
  }

**Comment by pgouband** [comment]
Hi @JPatC and @mhcmind,

Thank you for letting us know.
We are checking.

**Comment by pgouband** [comment]
Hi,
internal ID to track this request is: INFRAANO-1201
thanks!

**Comment by pgouband** [comment]
Hi @JPatC,

We are investigating as the issue could be on TMOS (license, Hotfix, ...)

**Comment by pgouband** [comment]
Hi @JPatC,

From our investigation it's a license issue so please open a ticket support to http://myf5.com/
You can reference the internal case: 00435103

**Comment by pgouband** [comment]
Hi @JPatC,

Can you share the ticket support number?

**Comment by JPatC** [comment]
It’s case 00437901.

Sent from my iPhone

On Jul 12, 2023, at 12:14 PM, Patrick ***@***.***> wrote:

﻿

Hi @JPatC<https://github.com/JPatC>,

Can you share the ticket support number?

**Comment by JPatC** [comment]
Can you let me know what the license issue is? As indicated below, I opened up case 00437901 and they keep asking me why I think this is a licensing issue. This is a VE product and it’s fully licensed and I can renew the license without issues. F5 did change the IPs they use for licensing so I had to add a new management route but what’s odd is there’s a lot of IPs still in the old range so I had to keep the old route so I can get the threat, AV, etc updates. 

- Patrick

**Comment by pgouband** [comment]
Hi @JPatC,

When we try to create a auth token through the endpoint: /mgmt/shared/authn/login it works fine, but when we try to to do the same thing after adding an add-on key for FIPS to the box I get error.
I have shared the same information in your case. Let me try to reach the engineer managing your case.

**Comment by JPatC** [comment]
I believe I put this in the issue. It works fine on my lab license that doesn’t have the FIPS add on. I was told that terraform tries to open a non-FIPS validated connection that fails when the FIPS add on is active. Isn’t Hashicorp addressing that issue?

Sent from my iPhone

On Jul 17, 2023, at 3:27 AM, Patrick ***@***.***> wrote:

﻿

Hi @JPatC<https://github.com/JPatC>,

When we try to create a auth token through the endpoint: /mgmt/shared/authn/login it works fine, but when we try to to do the same thing after adding an add-on key for FIPS to the box I get error.
I have shared the same information in your case. Let me try to reach the engineer managing your case.

**Comment by pgouband** [comment]
Hi @JPatC,

Currently Golang (used by Terraform) doesn't support Extended Master Secret (introduce in BIG-IP v17.1.0.1).
From this github request https://github.com/golang/go/issues/43922#issuecomment-1525827665 it'll be implemented in a future release.
When Golang will support Extended Master Secret, we will update our Terraform provider to work with the new release of Golang.
