### ISSUE TITLE
Is v17.x supported?

### ISSUE THREAD

**Issue by jakauppila** [F5Networks/terraform-provider-bigip#820]
The README states that v16.x is supported; is there any support for v17.x?

**Comment by RavinderReddyF5** [comment]
Hi @jakauppila  do you see any issues with v17.x ? Actually those are versions we tested for BIGIP provider. please let me know if you see any issues on v17.x

**Comment by jakauppila** [comment]
@RavinderReddyF5 No issues, more just curious from a supported/tested perspective.

We are planning an upgrade soon and we're deciding between v16 and v17 based on the compatibility of this provider.

**Comment by pgouband** [comment]
Hi @jakauppila,

Our next release coming in July will be tested with version v15.x, v16.x and v17.x
