### ISSUE TITLE
Unable to deploy a parameter when the level is set to "global" using  data.bigip_waf_entity_parameter json.

### ISSUE THREAD

**Issue by chanjansen** [F5Networks/terraform-provider-bigip#822]
### Environment

-  TMOS/Bigip Version: 16.1.3
-  Terraform Version: 1.3.7
-  Terraform bigip provider Version: 1.18.0
### Summary

When attempting to deploy a parameter using the bigip_waf_entity_parameter data source in Terraform, with the level attribute set to "global", the deployment fails. The error message is:

**Error: Error in Importing AWAF json (my-waf-policy): [ERROR] WafPolicy import failed with :{File: Message: Could not add the Parameter "global-params-1". Invalid value for Parameter Level to set.}**

### Steps To Reproduce

data "bigip_waf_entity_parameter" "global_params" {
  for_each = { for item in var.parameters : item.name => item }

  name                          = each.value.name
  level                         = each.value.level
  type                          = each.value.type
  data_type                     = each.value.data_type
  mandatory                     = each.value.mandatory
  value_type                    = each.value.value_type
  allow_empty_type              = each.value.allow_empty_type
  allow_repeated_parameter_name = each.value.allow_repeated_parameter_type
  sensitive_parameter           = each.value.sensitive_parameter
}

parameters = [
  { name = "global-params-1"
  level = "global" 
  ........................
}
]

resource "bigip_waf_policy" "my-waf-policy" {

.........................................................................................
parameters = [for param in data.bigip_waf_entity_parameter.global_params : param.json]

output of data.bigip_waf_entity_paramter.global_params json

**"json" = {\"name\":\"global-params-1\",............\"level\":\"global\",\"url\":{}}"**

### Expected Behavior
Policy to be deployed with specified global parameters.

### Actual Behavior
Error in the middle of deployment.

**Error: Error in Importing AWAF json (my-waf-policy): [ERROR] WafPolicy import failed with :{File: Message: Could not add the Parameter "global-params-1". Invalid value for Parameter Level to set.}**

**Comment by pgouband** [comment]
Hi,
internal ID to track this request is: INFRAANO-1207
thanks!
