### ISSUE TITLE
F5 sending a GET instead of a CONNECT when retrieving open api spec file via a configured proxy during build of an API WAF policy

### ISSUE THREAD

**Issue by afhamilton** [F5Networks/terraform-provider-bigip#823]
### Environment

 * TMOS/Bigip Version: 16.1.3.4
 * Terraform Version: 1.4.4
 * Terraform bigip provider Version: 1.18.0

### Summary

When we add a destination in the open_api_files attribute of the bigip_waf_policy with a proxy configured on the BIGIP the request from the F5 uses a GET instead of a CONNECT when trying to retrieve the spec file from the location specified in the value of the open_api_files.

### Steps To Reproduce

1. Configure a waf policy in Terraform:
resource "bigip_waf_policy" "api_endpoint" {
  name                 = "api_endpoint"
  partition            = "api"
  template_name        = "POLICY_TEMPLATE_API_SECURITY"
  application_language = "utf-8"
  enforcement_mode     = "blocking"
  description          = "Test API policy"
  server_technologies  = ["Unix/Linux", "Redis"]
  open_api_files       = ["https://testrepo.example/stash/projects/testproject/repos/public_repo/raw/api_spec"]
}

2. Run a terraform plan + apply to build the WAF policy on a F5 ASM appliance that has a proxy configured.

3. Capture a tcpdump during the terraform plan with the proxy IP & port 443 filters

4. tcpdump will show a GET being used after handshake is successful which causes proxy connection to fail and respond with a 404.

### Expected Behavior
A proxy CONNECT is issue to the configured proxy destination when the api WAF policy is being built.

### Actual Behavior
GET is sent to configured proxy.

**Comment by pgouband** [comment]
Hi @afhamilton,

Did you get the same result using a curl or postman to do the request?
Using the AWAF declarative API:
https://clouddocs.f5.com/products/waf-declarative-policy/schema_v16_1.html

**Comment by afhamilton** [comment]
Hi,
No, I was able to retrieve the file when I made the request with an HTTP
data object and view the output.

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1218.

**Comment by pgouband** [comment]
Hi @afhamilton,

We are trying to reproduce the issue.
The proxy configuration is done under System -> Configuration -> Device -> Upstream proxy?

**Comment by afhamilton** [comment]
The proxy is configured via cli using the commands:

modify /sys db proxy.host value proxy.example.com
modify /sys db proxy.port value 3128

**Comment by pgouband** [comment]
Hi @afhamilton,

The issue is not on Terraform provider but on AWAF API.
