### ISSUE TITLE
RFE: new resource bigip_ssl_key_certificate

### ISSUE THREAD

**Issue by amolari** [F5Networks/terraform-provider-bigip#832]
### Is your feature request related to a problem? Please describe.
We need to manage the SSL certificate/key lifecycle beyond the first-time import. Today it's not possible as the cert and key import are 2 different resources.

### Describe the solution you'd like
Implement a new resource bigip_ssl_key_certificate similar (including attribute `true_name`) to what the F5 Ansible module [bigip_ssl_key_cert](https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_ssl_key_cert_module.html) does.
That way, we provide the key name+content, cert name+content and eventually set true_name (false/true) as attributes to the resources and we can import _and_ update the key/cert pair.
Of course, the key content is a sensitive attribute.

### Additional context
Issue somehow/possibly related to https://github.com/F5Networks/terraform-provider-bigip/issues/813 except that we want to manage the renewal of cert/key when these objects are refered in a SSL (client/server)ssl profile, bound to a VS.
In that issue, @RavinderReddyF5 refers to the GUI (BIGIP legacy). That's unfortunately still not supported in the BIGIP legacy GUI but as done with the Ansible module, possible with the use of tmsh transactions.

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1246.

**Comment by amolari** [comment]
@RavinderReddyF5 : I've tested this resource and there is an issue.
After creating the resource and having a SSL client profile (bound to a VS) using the cert/key, when I modify the key+cert in the same TF run, I get the error:
bigip_ssl_key_cert.testkeycert: Modifying... [id=ssl-test.key_ssl-test.crt]
╷
│ Error: error while trying to modify the ssl key (/Common/ssl-test.key): 01070317:3: profile /Common/clientssl_t1_sandbox1's  key(/Common/ssl-test.key) and certificate(/Common/ssl-test.crt) do not match.
│
│   with bigip_ssl_key_cert.testkeycert,
│   on partition-common-certkey.tf line 1, in resource "bigip_ssl_key_cert" "testkeycert":
│    1: resource "bigip_ssl_key_cert" "testkeycert" {

In the /var/log/audit log it seems the provider wants to change first the key name and not both objects together in a transaction:
Aug 28 17:45:56 xxxxxxxxxxx notice mcpd[5474]: 01070417:5: AUDIT - client tmsh, tmsh-pid-14160, user admin - transaction #36478959-2 - object 0 - modify { certificate_key_file_object { certificate_key_file_object_name "/Common/ssl-test.key" certificate_key_file_object_source_path_password "***" certificate_key_file_object_source_path_user "" certificate_key_file_object_source_path "file:///var/config/rest/downloads/ssl-test.key" certificate_key_file_object_local_path "/var/system/tmp/tmsh/JJ6Hrx/data" certificate_key_file_object_checksum "SHA1:1705:85c9e1cf249ed22b0b84632838c03014a9f32b49" } } [Status=Command OK]

Aug 28 17:45:56 xxxxxxxx notice icrd_child[14160]: 01420002:5: AUDIT - pid=14160 user=admin folder=/Common module=(tmos)# status=[01070317:3: profile /Common/clientssl_t1_sandbox1's  key(/Common/ssl-test.key) and certificate(/Common/ssl-test.crt) do not match.] cmd_data=modify sys file ssl-key /Common/ssl-test.key { source-path file:///var/config/rest/downloads/ssl-test.key }

**Comment by pgouband** [comment]
Hi @amolari,

Thanks for your feedback. This issue will be fixed in our next release.
