### ISSUE TITLE
RFE: add Server Agent Name support in resource bigip_ltm_profile_http

### ISSUE THREAD

**Issue by amolari** [F5Networks/terraform-provider-bigip#836]
### Is your feature request related to a problem? Please describe.
The resource bigip_ltm_profile_http currently doesn't support attributes to configure "Server Agent Name" setting.

### Describe the solution you'd like
We want to be able to configure HTTP profiles with specific settings for:
- Server Agent Name (corresponds to tmsh ltm profile http <name> server-agent-name)

### Describe alternatives you've considered
Current workaround is to use iRules

### Additional context
[K40243113: Overview of the HTTP profile](https://my.f5.com/manage/s/article/K40243113)

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1251.

**Comment by amolari** [comment]
@RavinderReddyF5 @pgouband 
Testing this feature in v1.20.0 I do see an issue:
once I set a value such as `server_agent_name = "abc"`  ( or `"none"` for empty), if I comment my change, and re-run, no change (in plan) is detected and it won't revert back to the value unset/default (= "BigIp").

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1347.

**Comment by pgouband** [comment]
Hi @amolari,

You can use the following line to get back to default value:
server_agent_name     = "default-value"

Terraform ressources are following tmsh design so it's working as expected.

**Comment by prateekramani** [comment]
Hi @amolari 
For Server Agent Name the default value is **"BigIP"**. If server_agent_name is commented (or not passed) during the update call, then no changes would be applied and previous value will persist ("abc" or "none" as per your case). In order to get back to default value **"BigIP"** is to be specified in Update call explicitly.
