### ISSUE TITLE
RFE: add support for description attribute in resource bigip_ltm_policy

### ISSUE THREAD

**Issue by amolari** [F5Networks/terraform-provider-bigip#838]
### Is your feature request related to a problem? Please describe.
The description attribute (at the LTM Policy and/or LTM Policy rule level) can bring some insightful information such as Service-Request tag, jira task etc...

### Describe the solution you'd like
We would like that you add the attribute description at the level of the resource (LTM Policy) and rule in resource bigip_ltm_policy.
Such as:

```
resource "bigip_ltm_policy" "test-policy" {
  name     = "/Common/test-policy"
  description = "my policy description"  <=====
  strategy = "first-match"
  requires = ["http"]
  controls = ["forwarding"]
  rule {
    name = "rule6"
    description = "my rule description" <=====
    action {
      forward    = true
      connection = false
      pool       = bigip_ltm_pool.mypool.name
    }
  }
  depends_on = [bigip_ltm_pool.mypool]
}

```
### Describe alternatives you've considered
None apparently possible

**Comment by G-gonzalezjimenez** [comment]
Hi @amolari could you send us an email at  <automation_ecosystem@f5.com> . Thank you!

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1252.

**Comment by amolari** [comment]
Just to make sure: is description in the Rule also implemented by your PR?
Alexandre

**Comment by RavinderReddyF5** [comment]
HI @amolari thanks for notifying me, I was looking into only policy level not in `irule` level. will check and see if I can fix in this release

**Comment by pgouband** [comment]
Hi @amolari,

Description field is available at policy and rule level.

**Comment by amolari** [comment]
Hi Patrick

yes, thank you. Tested successfully with 1.19.0
