### ISSUE TITLE
Getting error on make build

### ISSUE THREAD

**Issue by r-anthonypineda** [F5Networks/terraform-provider-bigip#840]
### Environment

 * TMOS/Bigip Version: 15
 * Terraform Version: 0.12.17
 * Terraform bigip provider Version: 1.18.1

### Summary

I get the following error when I ran make build after the git clone
```shell
[user@server terraform-provider-bigip]$ make build
==> Checking that code complies with gofmt requirements...
go install
# golang.org/x/sys/unix
vendor/golang.org/x/sys/unix/syscall.go:83:16: undefined: unsafe.Slice
vendor/golang.org/x/sys/unix/syscall_linux.go:2271:9: undefined: unsafe.Slice
vendor/golang.org/x/sys/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
vendor/golang.org/x/sys/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
# github.com/zclconf/go-cty/cty/set
vendor/github.com/zclconf/go-cty/cty/set/iterator.go:3:17: syntax error: unexpected any, expecting ]
vendor/github.com/zclconf/go-cty/cty/set/iterator.go:8:19: syntax error: unexpected [, expecting comma or )
vendor/github.com/zclconf/go-cty/cty/set/iterator.go:12:19: syntax error: unexpected [, expecting comma or )
make: *** [build] Error 2

```

**Comment by RavinderReddyF5** [comment]
Hi @r-anthonypineda,
as per terraform plugin sdkv2 requirement, to build binaries you should use GO version v1.19 and above.

https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2#section-readme

<img width="1043" alt="image" src="https://github.com/F5Networks/terraform-provider-bigip/assets/45624469/a6eee862-5b24-4708-8721-7621b60def70">

**Comment by RavinderReddyF5** [comment]
hi @r-anthonypineda closing this issue. please open new issue if you still see any issue
