### ISSUE TITLE
BIG-IP Provider create Partition

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/terraform-provider-bigip#844]
### Is your feature request related to a problem? Please describe.
Users can not create partition-specific objects without manually creating the partition first. This breaks the concept of a logical grouping of configuration resources as a best practice. Users can also be assigned rights into partitions with the current provider, but again the partition must be made manually before.

### Describe the solution you'd like
A resource added to the big-ip provider to create partitions. 

### Describe alternatives you've considered
Looking at the command resource it could be possible, however it doesn't work on destroy as the command would have to be specific on apply/destroy

### Additional context
Ansible does have a partition module, having a resource for Terraform would help balance the two choices. 
Customer requesting: @nickzxcv

**Comment by pgouband** [comment]
Hi @jmcalalang,

It's possible to create a partition using AS3 and AS3 Terraform resources.
Terraform AS3 integration:
https://clouddocs.f5.com/products/orchestration/terraform/latest/BIG-IP/as3-integration.html

AS3 documentation:
https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/

AS3 json file example on how to create a partition/tenant:
```json
{
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "declaration": {
    "class": "ADC",
    "schemaVersion": "3.37.0",
    "Part1": {
        "class": "Tenant",
        "example_app": {
            "class": "Application"
        }
    }
}
}
```

**Comment by jmcalalang** [comment]
So creating a blank partition could be an option, however, it's not something I need to do with Ansible. It also purposes a situation when upon reloading of AS3 (reboot pulling from data-group), everything from terraform in that partition could be lost.

**Comment by pgouband** [comment]
Hi @jmcalalang,

you refer to Ansible imperative collection, but in the declarative collection there is no partition module (link to declarative partition below).
https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/modules_2_0/module_index.html

**Comment by jmcalalang** [comment]
Correct, but the customer is also using Terraform imperatively.

**Comment by ar406** [comment]
AFAICT, this requires changes to the go-bigip package. 

For example, the VCMP Guest resource in the Terraform provider ends up calling [the CreateVcmpGuest function, which is defined in go-bigip](https://github.com/f5devcentral/go-bigip/blob/master/vcmp.go#L83). 

As it stands,  [the go-bigip package can only return a list of existing partitions](https://github.com/f5devcentral/go-bigip/blob/master/partitions.go).

**Comment by nickzxcv** [comment]
It's ok if this is hard to do in Terraform, but how about allowing it from DO then? If DO can make users with specific partition access, then shouldn't it also be able to create the partitions? All just to prepare the underlying configuration for Terraform/Ansible/AS3 to setup application stuff on top of what DO did.

**Comment by Tobse95** [comment]
We also need the possibility to create a partition through the terraform provider.

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1363.

**Comment by RavinderReddyF5** [comment]
Issue fixed in https://registry.terraform.io/providers/F5Networks/bigip/1.20.1/docs/resources/bigip_partition

**Comment by jmcalalang** [comment]
excellent, thank you!
