### ISSUE TITLE
RFE: Add new resource to create/manage DNS Resolver configuration

### ISSUE THREAD

**Issue by amolari** [F5Networks/terraform-provider-bigip#864]
### Is your feature request related to a problem? Please describe.
We would like to be able to create and manage DNS Resolver configuration (in the UI under Network >> DNS Resolvers ) with the BIGIP TF provider.

### Describe the solution you'd like
Add support for DNS Resolvers creation/management
Route Domain support should be provided.

**Comment by pgouband** [comment]
Hi @amolari,

DNs resolver is available on Declarative Onboarding.
Have you tried using Declarative Onboarding?

**Comment by amolari** [comment]
Hi @pgouband 
It's fine to configure it from DO. Closing this issue. Thank you.
