### ISSUE TITLE
RFE: Add support for Trusted/Advertised CAs in resource bigip_ltm_profile_client_ssl

### ISSUE THREAD

**Issue by amolari** [F5Networks/terraform-provider-bigip#872]
### Is your feature request related to a problem? Please describe.
The resource "bigip_ltm_profile_client_ssl" doesn't support the configuration of the settings "Trusted Certificate authorities" and "Advertised Certificate authorities"

### Describe the solution you'd like
We would like to be able to configure the following settings of a Client SSL profile with the TF resource "bigip_ltm_profile_client_ssl":
- Client Authentication > Trusted Certificate Authorities
- Client Authentication > Advertised Certificate Authorities

### Describe alternatives you've considered
Manually configuring a Client SSL profile

**Comment by DanielPlawiak** [comment]
Hi,

From my experience with "reverse engineering" this resource, it is possible to set both Trusted Certificate Authorities and Advertised Certificate Authorities options even though they are not listed in the docs.

Use the following parameters in the "clientssl" resource:

client_cert_ca - > Advertised CA (value should be set to a string representing the CA cert on the system)
ca_file - > Trusted CA (value should be set to a string representing the CA cert on the system)


Please note that I do not guarantee that this is the official / supported way - it is simply my solution based on some trial and error.

Nonetheless, it would be great to have a fully documented feature in the future release of the provider!

**Comment by amolari** [comment]
Thanks a lot @DanielPlawiak , great info. Indeed, that has been commited 4 years ago and it's not documented.

@pgouband : can we use those undocumented attributes (it's only a documentation issue)?

**Comment by pgouband** [comment]
Hi @amolari,

Yes you can use those attributes. We will update the documentation.

You can check in file:
https://github.com/F5Networks/terraform-provider-bigip/blob/master/bigip/resource_bigip_ltm_profile_ssl_client.go

Attributes are here:
"ca_file": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: "Client certificate file path.  Default None.",
			},
"client_cert_ca": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: "client certificate name",
			},

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog to update the documentation and internal tracking ID for this request is: INFRAANO-1372.
