### ISSUE TITLE
Add support for telemetry streaming declarative endpoint

### ISSUE THREAD

**Issue by olegmukhin** [F5Networks/terraform-provider-bigip#881]
### Is your feature request related to a problem? Please describe.
We use [telemetry streaming](https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/) to send logs from F5 BIG-IP. It is not possible to configure telemetry streaming using Terraform.

### Describe the solution you'd like
A resource should be added to the provider that will allow sending a JSON (similar to [bigip_as3](https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_as3) resource) to the telemetry streaming API endpoint (/mgmt/shared/telemetry/declare). It should also support [namespace-specific endpoint](https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/namespaces.html).

### Describe alternatives you've considered
We have considered using the [bigip_command](https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_command) resource, but tmsh does not support configuration of telemetry streaming.

### Additional context
N/A

**Comment by G-gonzalezjimenez** [comment]
Hi Oleg, thanks for reaching out.  TS was moved to maintenance mode at the beginning of 2023 as stated here:  
https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/

That means that we will slow down on our releases and only add bugs and security fixes. Supporting the product, here's the official statement:

F5 BIG-IP Telemetry Streaming is entering a phase of ongoing maintenance and support. A product in maintenance mode continues to receive support and ensures its stability with regular critical fixes and security updates. This maintenance approach helps maintain the longevity and reliability of the product for the long term. Enhancement requests for this product will be evaluated on an individual basis, taking into consideration their overall impact and alignment with our business objectives. Only those with a strong case for improvement will be considered for implementation. There is no plan to deprecate this product.

Thank you for understanding.
