### ISSUE TITLE
Add persistence_profiles argument for FAST TCP/HTTP(S) applications

### ISSUE THREAD

**Issue by ahadjiat** [F5Networks/terraform-provider-bigip#883]
Hello, I'm using **bigip_fast_tcp_app** and **bigip_fast_https_app** resources (_F5 Automation Tool Chain(ATC)_).

I'd like to be able to define one or more (existing) persistence profiles for the associated virtual server, as here:
https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_ltm_virtual_server#persistence_profiles

Can you please add this feature for resources that will create and manage FAST TCP/HTTP(S) applications on BIG-IP?

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1338 (TCP), INFRAANO-1339 (HTTP) and INFRAANO-1340 (HTTPS).
