### ISSUE TITLE
Missing Terraform resorce to "Create profile for request logging"

### ISSUE THREAD

**Issue by psjolin67** [F5Networks/terraform-provider-bigip#892]
### Is your feature request related to a problem? Please describe.
Unable to create request logging profile on BigIP

### Describe the solution you'd like

Need to be able to create request logging through Terraform

### Describe alternatives you've considered

We are missing full automation on BigIP and need to create this manual creating unnecessary time consuming with possible problems creating even more time..

**Comment by pgouband** [comment]
Hi @psjolin67,

Have you tried using AS3?
Is it the profile you want to create?
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#traffic-log-profile

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1407.
