### ISSUE TITLE
"...mgmt/shared/authn/login": EOF when connecting to bigip with 1.19.0 and 1.20.0

### ISSUE THREAD

**Issue by MasakariDOR** [F5Networks/terraform-provider-bigip#894]
### Environment

 * TMOS/Bigip Version: BIG-IP 14.1.5.5 Build 0.17.2 Engineering Hotfix 
 * AS3 version: 3.46.1
 * Terraform Version: 1.5.2
 * Terraform bigip provider Version: 1.20.0

### Summary

Terraform bigip providers 1.19.0 and 1.20.0 fail to authenticate with bigip and produce an error `Error: Post "https://bigip.localdomain/mgmt/shared/authn/login": EOF`

### Steps To Reproduce
Can be reproduced using ANY data, AS3 or resource call with bigip provider 1.19.0 or 1.20.0. Versions earlier than this do not have this issue (1.18.1 is the last working version).

```
data "bigip_ltm_pool" "Pool-Example" {
  name      = "default-pool"
  partition = "Common"
}

provider "bigip" {
  token_auth   = true
  address      = "bigip.localdomain"
  teem_disable = true
}

terraform {
  required_providers {

    bigip = {
      source  = "f5networks/bigip"
      version = "1.20.0"
    }
  }
}
```

1. Provide terraform resource config which you are facing trouble along with the output of it.
Provided above

2. To get to know more about the issue, provide terraform debug logs
[terraform_debug.log](https://github.com/F5Networks/terraform-provider-bigip/files/13232872/terraform_debug.log)

3. To capture debug logs, export TF_LOG variable with debug ( export TF_LOG= DEBUG ) before 
  runnning terraform apply/plan

4. As3/DO json along with the resource config( for AS3/DO resource issues )

### Expected Behavior
The call above should return the pool data as it does using provider version 1.18.1.

### Actual Behavior
Provider fails to authenticate with an error "EOF"

**Comment by RavinderReddyF5** [comment]
Hi @MasakariDOR,
It Might be same problem of : https://github.com/F5Networks/terraform-provider-bigip/issues/817
