### ISSUE TITLE
Possibility to configure the MTU size on a vlan

### ISSUE THREAD

**Issue by Tobse95** [F5Networks/terraform-provider-bigip#908]
### Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
We are using the f5 terraform provider to manage vlans on a f5 bigip device. In several use cases we need to set the MTU size of a vlan from 1500 to 9000. Actually the tf provider doesn't support this functionality to change the mtu size of a vlan.

### Describe alternatives you've considered
Configure manually is no option, because then the terraform provider crashs.
Declarative Onboarding also does not work in our use case.

### **should be:**

```
resource "bigip_net_vlan" "trans_1000" {
  name = "/Common/trans_1000"
  tag  = 1000
  interfaces {
    vlanport = "1.1"
    tagged   = false
  }
  mtu = "9000"
}
```

Please add the opportunity to manage the mtu size:

https://github.com/F5Networks/terraform-provider-bigip/blob/master/bigip/resource_bigip_net_vlan.go#L87

**Comment by pgouband** [comment]
Hi @Tobse95,

Thanks for reporting this RFE.
As a workaround, I tested to modify the MTU using the terraform command resource with success.

Here the example:
```terraform
resource "bigip_net_vlan" "vlan1" {
  name = "/Common/Internal"
  tag  = 101
  interfaces {
    vlanport = "1.1"
    tagged   = false
  }
}

resource "bigip_command" "test-command" {
  commands = ["modify net vlan Internal mtu 9000"]
}
```

**Comment by Tobse95** [comment]
Thanks for the reply. Nevertheless it would be nice (speed) to configure this in the vlan resource.

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1404.
The workaround provided is still a solution until we add it.
