### ISSUE TITLE
RFE: Add new resource to create/manage Rewrite profiles

### ISSUE THREAD

**Issue by amolari** [F5Networks/terraform-provider-bigip#924]
### Is your feature request related to a problem? Please describe.
At this time it's not possible to create/manage LTM profiles of type "rewrite"

### Describe the solution you'd like
Please add a Terraform resource to create/manage LTM rewrite profiles.
Our use-case is about using the mode "URI Translation" only.

**Comment by pgouband** [comment]
Hi @amolari,

Rewrite profiles are available in AS3.
Have you tried using AS3?

**Comment by amolari** [comment]
Hi @pgouband 
At this time we can't use AS3 at the customer side. It's in the project management pipeline but cannot be prioritized right now.

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1415.
