### ISSUE TITLE
Support for check_max_value_length in parameters for declarative WAF policy

### ISSUE THREAD

**Issue by curtkersey** [F5Networks/terraform-provider-bigip#925]
### Environment

 * TMOS/Bigip Version: 16.1.4
 * Terraform Version: 1.7.0
 * Terraform bigip provider Version: 1.20.2

### Summary

When working with a customer on using the "check_max_value_length” for a parameter in declarative WAF policy, it is not clear how to  set the value for the length.  We were using the reference at:
https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/data-sources/bigip_waf_entity_parameters#check_max_value_length  

I emailed internal to F5, and I received the response "The Terraform WAF resources leverage the AWAF declarative policy schema so there should be a maximum_length argument which I realize is not there. Please submit a GitHub issue for adding it."

I am submitting the issue for that.

In addition to adding support for it, it would be great to have an example in the documentation also.

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1421.
