### ISSUE TITLE
bigip_bigiq_as3 with provider 1.21.0 is returning  "Error: onPatch Not implemented"

### ISSUE THREAD

**Issue by karce25** [F5Networks/terraform-provider-bigip#953]
### Environment

 * TMOS/Bigip Version: BIG-IQ  8.3.0
 * Terraform Version: 1.7.5
 * Terraform bigip provider Version: 1.21.0

### Summary

Trying to use bigip_bigiq_as3 resource on BIG-IQ to create AS3 applications on BIG-IPs returns  "Error: onPatch Not implemented"
This happens with the latest version 1.21.0, tried using older versions like 1.14.0, and it works correctly.

### Steps To Reproduce

1. Tried to use basic auth and bigiq token like below

Provider config:

terraform {
  required_providers {
    bigip = {
      source  = "F5Networks/bigip"
      version = "1.21.0"
    }
  }
}
provider "bigip" {
  address    = var.hostname
  username   = var.username
  password   = var.password
  token_auth = true
  login_ref  = "local"
}

Resource config:

resource "bigip_bigiq_as3" "test" {
  bigiq_address    = var.hostname
  bigiq_user       = var.username
  bigiq_password   = var.password
  bigiq_token_auth = true
  bigiq_login_ref  = "local"
  as3_json         = file("bigiq_example.json")

}

### Error received

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: onPatch Not implemented
│ 
│   with provider["registry.terraform.io/f5networks/bigip"],
│   on providers.tf line 9, in provider "bigip":
│    9: provider "bigip" {
│ 
### Debug logs on terraform

2024-03-26T17:44:19.353-0600 [WARN]  ValidateProviderConfig from "provider[\"registry.terraform.io/f5networks/bigip\"]" changed the config value, but that value is unused
2024-03-26T17:44:19.354-0600 [INFO]  provider.terraform-provider-bigip_v1.21.0: Initializing BigIP connection: timestamp=2024-03-26T17:44:19.354-0600
2024-03-26T17:44:20.148-0600 [ERROR] provider.terraform-provider-bigip_v1.21.0: Error creating New Token Session onPatch Not implemented: timestamp=2024-03-26T17:44:20.148-0600
2024-03-26T17:44:20.148-0600 [ERROR] provider.terraform-provider-bigip_v1.21.0: Response contains error diagnostic: @module=sdk.proto tf_provider_addr=provider tf_rpc=Configure diagnostic_severity=ERROR diagnostic_summary="onPatch Not implemented" tf_proto_version=5.3 tf_req_id=a6249508-005a-0b54-38f8-14ebbc5030bd @caller=github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/diag/diagnostics.go:55 diagnostic_detail="" timestamp=2024-03-26T17:44:20.148-0600
2024-03-26T17:44:20.149-0600 [ERROR] vertex "provider[\"registry.terraform.io/f5networks/bigip\"]" error: onPatch Not implemented

### Logs on BIG-IQ with provider "1.21.0" Indicate an authz issue receiving a 400 response (not sure if the BIG-IQ expects a POST instead of a PATCH method according to the documentation is a POST method  https://clouddocs.f5.com/products/big-iq/mgmt-api/v5.4/ApiReferences/bigiq_api_ref/r_auth_login.html#examples)

[INFO][26 Mar 2024 16:05:14 PDT][ForwarderPassThroughWorker] {"user":"None","method":"POST","uri":"http://localhost:8100/mgmt/shared/authn/login","status":200,"from":"172.18.129.133"}
INFO][26 Mar 2024 16:05:14 PDT][ForwarderPassThroughWorker] {"user":"local/admin","method":"PATCH","uri":"http://localhost:8100/mgmt/shared/authz/tokens/eyJraWQiOiIxY2ZkMDIxMS1hNDUwLTRlZjItOTgzNy02OGRhYjYyMzFkM2QiLCJhbGciOiJSUzM4NCJ9.eyJpc3MiOiJCSUctSVEiLCJqdGkiOiJBVTVxb0MycWhXMndJRDNGUm9PR0R3Iiwic3ViIjoiYWRtaW4iLCJhdWQiOiIxNzIuMTguMTI5LjEzMyIsImlhdCI6MTcxMTQ5NDMxNCwiZXhwIjoxNzExNDk0NjE0LCJ1c2VyTmFtZSI6ImFkbWluIiwiYXV0aFByb3ZpZGVyTmFtZSI6ImxvY2FsIiwidXNlciI6Imh0dHBzOi8vbG9jYWxob3N0L21nbXQvc2hhcmVkL2F1dGh6L3VzZXJzL2FkbWluIiwidHlwZSI6IkFDQ0VTUyIsInRpbWVvdXQiOjMwMCwiZ3JvdXBSZWZlcmVuY2VzIjpbXX0.RHXSzIQcdl2mxaJ3znwzCzK8sZJwQIXNZ8N5AWR2Dl4bH1WjoV-1mq4jgnvRMyEqL8EpeW4c7lw9AZVNtK_vexbqtaQJ0F1BI6FeXMUxqMCQ2W-zTHRYPc1EPl7ygDq53gZorNuGNRLuC-VzA_a0ecWfbCkpA_CBdtadETbduF1sX9oymrw7QB7z8LwPFy4ciootFjFXFq4T5O3h-Gh7Rgpw5RiXdFzstP3HIdE1a_sAHmba_L0KqQgp5zKC9RnAVHNj1EkZ4lX3324zIslU2i9Mgi-As6DcO5F2z2g3ct4vxd4Px5OAooiE2Zg2eC7mL5iSV-lKmslVsp6XMqnUOI8zIHOlrXReXTCGoXZ5KVj7kt44ouYDWkpE85QgXiMK9sEmkNK08MpPGCgjP5o3XAvDhJMMnv21ElIGeXigNr6QtPzCj-lDqryhn1wH0REvD6_dwYJSypQ68WgikvhQKW_tpyhbbbH1HrwtgwGkkXWBF0h3lNZV7JNnhN3GDN-Y","status":400,"from":"172.18.129.133"}

### Logs on BIG-IQ with provider "1.14.0" working correctly

[INFO][26 Mar 2024 15:44:23 PDT][ForwarderPassThroughWorker] {"user":"local/admin","method":"POST","uri":"http://localhost:8100/mgmt/shared/authz/effective-permissions","status":200,"from":"172.18.129.133"}
[INFO][26 Mar 2024 15:44:24 PDT][ForwarderPassThroughWorker] {"user":"local/admin","method":"POST","uri":"http://localhost:8100/mgmt/shared/index/es-config","status":200,"from":"172.18.129.133"}
[INFO][26 Mar 2024 15:44:25 PDT][ForwarderPassThroughWorker] {"user":"local/admin","method":"POST","uri":"http://localhost:8100/mgmt/shared/authn/login","status":200,"from":"172.18.129.133"}
[INFO][26 Mar 2024 15:44:26 PDT][ForwarderPassThroughWorker] {"user":"None","method":"POST","uri":"http://localhost:8100/mgmt/shared/authn/login","status":200,"from":"172.18.129.133"}

### Expected Behavior
Work as an earlier version with or without basic auth

### Actual Behavior

 Error: onPatch Not implemented

**Comment by pgouband** [comment]
Hi @karce25,

Can you share the AS3 json file you are using?

**Comment by karce25** [comment]
Hi @pgouband  it is the below AS3 test declaration
{
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.0.0",
        "id": "example-declaration-01",
        "label": "Task1",
        "remark": "Task 1 - HTTP Application Service",
        "target": {
            "address": "10.86.9.161"
        },
        "Task1": {
            "class": "Tenant",
            "MyWebApp1http": {
                "class": "Application",
                "template": "http",
                "serviceMain": {
                    "class": "Service_HTTP",
                    "virtualAddresses": [
                        "10.1.2.10"
                    ],
                    "pool": "web_pool"
                },
                "web_pool": {
                    "class": "Pool",
                    "monitors": [
                        "http"
                    ],
                    "members": [
                        {
                            "servicePort": 80,
                            "serverAddresses": [
                                "192.0.2.33",
                                "192.0.2.13"
                            ],
                            "shareNodes": true
                        }
                    ]
                }
            }
        }
    }
}

**Comment by pgouband** [comment]
Hi @karce25,

Can you check the version of AS3 on BIG-IQ and BIG-IP?
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/big-iq.html

**Comment by karce25** [comment]
Hi, 
Both versions of the BIG-IP and BIG-IQ

{"version":"3.44.0","release":"3","schemaCurrent":"3.44.0","schemaMinimum":"3.0.0"}

{"version":"3.44.0","release":"3","schemaCurrent":"3.44.0","schemaMinimum":"3.0.0"}

Saw in the document that AS3 versions 3.42 and later are NOT compatible with BIG-IQ, I downgraded to 3.41.0, and the same error

{"version":"3.41.0","release":"1","schemaCurrent":"3.41.0","schemaMinimum":"3.0.0"}

{"version":"3.41.0","release":"1","schemaCurrent":"3.41.0","schemaMinimum":"3.0.0"}

**Comment by karce25** [comment]
Hi @pgouband 

I already managed to make it work, I have to disable the token auth on the provider and in the BIG-IQ resource, also set basic auth on the BIG-IQ "set-basic-auth on"

terraform {
  required_providers {
    bigip = {
      source  = "F5Networks/bigip"
      version = "1.21.0"
    }
  }
}
provider "bigip" {
  address    = var.hostname
  username   = var.username
  password   = var.password
  token_auth = false    <<<<<<<<<<<!

}

resource "bigip_bigiq_as3" "test" {
  bigiq_address    = var.hostname
  bigiq_user       = var.username
  bigiq_password   = var.password
  bigiq_token_auth = false          <<<<<<<<<!
  as3_json         = file("bigiq_example.json")


}
