### ISSUE TITLE
Addition of "Enforcement Mode" for Cross Domain Request Enforcement in URL properties

### ISSUE THREAD

**Issue by curtkersey** [F5Networks/terraform-provider-bigip#958]
Environment
TMOS/Bigip Version: 16.1.4
Terraform Version: 1.7.0
Terraform BIG-IP provider Version: 1.22.0

### Is your feature request related to a problem? Please describe.
I am helping a customer with their Terraform deployments for ASM policies.  Currently when deploying WAF policies on the BIG-IP and adding a URL entity, they choose the "Enforcement Mode" of "Disabled" for the Cross Domain Request Enforcement.  Now deploying via Terraform, they need to replicate current policy deployments, which is to specify "Disabled".  Currently the provider defaults to "Enforce on ASM".   I am attaching a document to show screen shots of BIG-IP.

[CORSheaders.pdf](https://github.com/F5Networks/terraform-provider-bigip/files/14910003/CORSheaders.pdf)

### Describe the solution you'd like
We would like to have this added to the Terraform provider and include the current options for Cross Domain Request Enforcement, which include: Disabled, Remove all CORS headers, Replace CORS headers, or Enforce on ASM.

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1538.
