### ISSUE TITLE
Documentation for Per-App feature with Terraform

### ISSUE THREAD

**Issue by skenderidis** [F5Networks/terraform-provider-bigip#973]
With TF v1.22 we released the Per-App functionality with AS3, but there is no documentation explaining how to use it. 

When using the same JSON (per-app) files that would work with Postman, terraform gives back an error.

Can we have have documentation on how this feature works

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1559.

**Comment by pgouband** [comment]
Hi @skenderidis,

Please check https://clouddocs.f5.com/products/orchestration/terraform/latest/BIG-IP/per-app-as3.html
