### ISSUE TITLE
bigip_waf_entity_param | level "none" or "global'

### ISSUE THREAD

**Issue by bwearp** [F5Networks/terraform-provider-bigip#998]
### Environment

 * TMOS/Bigip Version: 16.1.3.3
 * Terraform Version: v1.9.0-dev
 * Terraform bigip provider Version: 1.17.1

### Summary

when submitting a new parameter with:
level = "global" ==> "Error: Invalid value for Parameter Level to set"  - after terraform apply myplan
level = "none" ==> "Error: expected level to be one of [global url flow]" - after terraform plan -out myplan

The default setting is the wildcard URL - in the GUI/TMSH, the default setting is Global
Unfortunately I am working in a bank and so I do not have access to GitHub from my work pc....

Hope this is enough - apologies if not

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1619.

**Comment by bwearp** [comment]
Hiya. Sorry to hassle. Would you be able to give a very approximate fix date that I can tell the boss? 😊

**Comment by pgouband** [comment]
Hi,

For the release after the one we are working on so end of October but we will try to fix it earlier if possible.

**Comment by RavinderReddyF5** [comment]
Hi @bwearp,

I didn't see any issue. below is config I used. please let me know is this something missed from my config:

```
data "bigip_waf_entity_parameter" "Param1" {
  name                   = "Param1"
  type                   = "explicit"
  data_type              = "alpha-numeric"
  level                  = "global"
  check_max_value_length = true
  check_min_value_length = true
  max_value_length       = 30
  min_value_length       = 15
  perform_staging        = true
}

resource "bigip_waf_policy" "this" {
  name                 = "Test-ASM-Automation-Scenario2"
  partition            = "Common"
  template_name        = "POLICY_TEMPLATE_FUNDAMENTAL"
  application_language = "utf-8"
  enforcement_mode     = "blocking"
  server_technologies  = ["Apache Tomcat", "MySQL", "Unix/Linux"]
  parameters           = [data.bigip_waf_entity_parameter.Param1.json]
}

**Comment by bwearp** [comment]
Hi,

Thanks for looking into it.

I’m using a parameter map and json as recommended by f5 in:
https://community.f5.com/kb/technicalarticles/manage-f5-big-ip-advanced-waf-policies-with-terraform-part-4---policy-lifecycle-/300866

Setting the level to global or url  causes the error…

KR, Ben

**Comment by pgouband** [comment]
Hi @bwearp,

Can you share some examples causing the error?

**Comment by RavinderReddyF5** [comment]
hi @bwearp,can you please try with latest version of TF BIG-IP Version: [v1.22.3](https://github.com/F5Networks/terraform-provider-bigip/releases/tag/v1.22.3)

**Comment by bwearp** [comment]
Hi,

I can’t I’m in a bank…

KR, Ben

**Comment by bwearp** [comment]
Hi,

Ok will do thanks. 🙏

KR, Ben

**Comment by RavinderReddyF5** [comment]
Hi @bwearp did u verified issue from the above or version I specified ?

**Comment by bwearp** [comment]
Hi Ravindsr,

I didn’t I’m afraid. It takes a while for the bank to allow new software
versions to be used, and I’ve now started a new job…

KR, Ben

**Comment by pgouband** [comment]
Hi @bwearp,

Has the bank been able to test the latest version?
We were unable to reproduce the problem.
If there is no response by next week, we will close the ticket.

**Comment by bwearp** [comment]
Hi,

I’ve left that bank. Am at a different one.

Not sure which version they are using as am still waiting for access.

Please close the ticket.

Thanks for your help.

KR, Ben
